-- PRODUTO PAI 
SELECT
	B4.B4_XIDPROD IDPROD,
	B4.B4_COD CODIGO,
	B4.B4_DESC NAME,
	B4.B4_UM UNIDADE_01,
	AH_01.AH_DESCIN DESC_UNIDADE_01,
	B4.B4_SEGUM UNIDADE_02,
	AH_02.AH_DESCIN DESC_UNIDADE_02,
	B4.B4_TIPCONV TIPO_CONV,
	B4.B4_CONV FATOR,
	B4.B4_LARG LARGURA,
	B4.B4_LARUTIL LARGURA_UTIL,
	B4.B4_GRAMATU GRAMATURA,
	B4.B4_REND RENDIMENTO,
	B4.B4_PESO PESO_LIQUIDO,
	B4.B4_COMPTEC COMPOSICAO,	
	ISNULL(CAST(CAST(B4.B4_XDESCPR AS BINARY(2048)) AS VARCHAR(2048)),'') DESCPROD,
	ISNULL(CAST(CAST(B4.B4_XDESCSH AS BINARY(2048)) AS VARCHAR(2048)),'') DESCSHORT,
	ISNULL(CAST(CAST(B4.B4_XDESCAB AS BINARY(2048)) AS VARCHAR(2048)),'') DESCABOUT,
	ISNULL(CAST(CAST(B4.B4_XDESCTP AS BINARY(2048)) AS VARCHAR(2048)),'') DESCTECIDO,
	B4.B4_XSTATUS STATUS,
	B4.R_E_C_N_O_ RECNOSB4
FROM 
	SB4010 B4 (NOLOCK)
	LEFT JOIN SAH010 AH_01 (NOLOCK) ON AH_01.AH_FILIAL = '' AND AH_01.AH_UNIMED = B4.B4_UM AND AH_01.D_E_L_E_T_ = '' 
	LEFT JOIN SAH010 AH_02 (NOLOCK) ON AH_02.AH_FILIAL = '' AND AH_02.AH_UNIMED = B4.B4_SEGUM AND AH_02.D_E_L_E_T_ = ''  
WHERE
	B4.B4_FILIAL = '' AND 
	B4.B4_XUSAECO = 'S' AND 
	B4.B4_XENVECO = '1' AND 
	B4.D_E_L_E_T_ = ''
	
-- PRODUTO FILHO 
SELECT
	B1.B1_XIDSKU IDSKU,
	B1.B1_COD CODIGO,
	B1.B1_DESC NAME,
	B1.B1_UM UNIDADE_01,
	AH_01.AH_DESCIN DESC_UNIDADE_01,
	B1.B1_SEGUM UNIDADE_02,
	AH_02.AH_DESCIN DESC_UNIDADE_02,
	B1.B1_TIPCONV TIPO_CONV,
	B1.B1_CONV FATOR,
	B4.B4_LARG LARGURA,
	B4.B4_LARUTIL LARGURA_UTIL,
	B4.B4_GRAMATU GRAMATURA,
	B4.B4_REND RENDIMENTO,
	B4.B4_PESO PESO_LIQUIDO,
	B4.B4_COMPTEC COMPOSICAO,	
	ISNULL(CAST(CAST(B4.B4_XDESCPR AS BINARY(2048)) AS VARCHAR(2048)),'') DESCPROD,
	ISNULL(CAST(CAST(B4.B4_XDESCSH AS BINARY(2048)) AS VARCHAR(2048)),'') DESCSHORT,
	ISNULL(CAST(CAST(B4.B4_XDESCAB AS BINARY(2048)) AS VARCHAR(2048)),'') DESCABOUT,
	ISNULL(CAST(CAST(B4.B4_XDESCTP AS BINARY(2048)) AS VARCHAR(2048)),'') DESCTECIDO,
	B1.B1_XSTATUS STATUS,
	COALESCE(BV.BV_XIDITAT,0) IDCOLOR,
	B1.R_E_C_N_O_ RECNOSB1
FROM 
	SB1010 B1 (NOLOCK)
	INNER JOIN SB4010 B4 (NOLOCK) ON B4.B4_FILIAL = '' AND B4.B4_COD = B1.B1_ARTIGO AND B4.B4_XUSAECO = 'S' AND B4.B4_XENVECO = '2' AND B4.D_E_L_E_T_ = ''
	LEFT JOIN SBV010 BV ON BV.BV_FILIAL = '  ' AND BV.BV_CHAVE = SUBSTRING(B1.B1_COD,9,3) AND BV.BV_XIDITAT > 0 AND BV.BV_XENVECO = '2' AND BV.D_E_L_E_T_ = ''
	LEFT JOIN SAH010 AH_01 (NOLOCK) ON AH_01.AH_FILIAL = '' AND AH_01.AH_UNIMED = B4.B4_UM AND AH_01.D_E_L_E_T_ = '' 
	LEFT JOIN SAH010 AH_02 (NOLOCK) ON AH_02.AH_FILIAL = '' AND AH_02.AH_UNIMED = B4.B4_SEGUM AND AH_02.D_E_L_E_T_ = ''  
WHERE
	B1.B1_FILIAL = '' AND 
	B1.B1_XENVECO = '1' AND 
	B1.D_E_L_E_T_ = ''
ORDER BY B1.B1_ARTIGO,B1.B1_COD

-- ATRIBUTO
SELECT 
	BV.BV_CHAVE CODIGO, 
	BV.BV_DESCRI DESCRICAO,
 	BV.BV_XIDITAT ID_ATRIB,
	BV.R_E_C_N_O_ RECNOSBV
 FROM 
 	SBV010 BV 
 WHERE 
 	BV.BV_FILIAL = '' AND 
 	BV.BV_XENVECO = '1' AND 
	BV.BV_TABELA = 'C' AND 
    BV.BV_XIDATR > 0 AND 
	BV.BV_XIDITAT = 0 AND
 	BV.D_E_L_E_T_ = '' 
  ORDER BY BV.BV_TABELA, BV.BV_CHAVE

-- CORES 
SELECT 
    COD_PRODUTO, 
 	COD_SKU, 
 	DESC_SKU, 
 	IDATRIB, 
 	NOME_ATRIB, 
 	IDTERMO, 
 	RECNOSBV 
 FROM 
 ( 
 	SELECT  
        B4.B4_COD COD_PRODUTO,  
 		B1.B1_COD COD_SKU, 
 		B1.B1_DESC DESC_SKU, 
 		SBV_COLOR.BV_XIDATR IDATRIB, 
 		'color' NOME_ATRIB, 
 		SBV_ITEM_COLOR.BV_XIDITAT IDTERMO, 
 		SBV_ITEM_COLOR.RECNOSBV RECNOSBV 
 	FROM  
 		SB4010 B4   
 		INNER JOIN SB1010 B1 ON B1.B1_FILIAL = '' AND B1.B1_ARTIGO = B4.B4_COD AND B1.B1_XIDSKU > 0 AND B1.B1_XENVECO = '2' AND B1.D_E_L_E_T_ = '' 
		CROSS APPLY ( 
			SELECT 
				BV.BV_XIDATR
			FROM 
				SBV010 BV 
			WHERE 
				BV.BV_FILIAL = '' AND 
				BV.BV_TABELA = 'C' AND 
				BV.BV_XIDATR > 0 AND 
				BV.D_E_L_E_T_ = ''
			GROUP BY BV.BV_XIDATR
		) SBV_COLOR
		
		CROSS APPLY ( 
			SELECT 
				BV.BV_XIDITAT,
				BV.R_E_C_N_O_ RECNOSBV
			FROM 
				SBV010 BV 
			WHERE 
				BV.BV_FILIAL = '' AND 
				BV.BV_TABELA = 'C' AND 
				BV.BV_CHAVE = SUBSTRING(B1.B1_COD,9,3) AND
				BV.BV_XIDATR > 0 AND 
				BV.BV_XIDITAT > 0 AND 
				BV.BV_XENVECO = '1' AND 
				BV.D_E_L_E_T_ = ''
		) SBV_ITEM_COLOR
 	WHERE 
 		B4.B4_FILIAL = '  ' AND 
 		B4.B4_XENVECO = '2' AND 
		B4.B4_XUSAECO = 'S' AND 
 		B4.D_E_L_E_T_ = '' 
 )PROD_SKU 
 ORDER BY COD_SKU 

-- PRODUTO PAI X SKU 
SELECT 
    COD_PRODUTO, 
 	COD_SKU, 
 	DESC_SKU,
	RECNOSB1
 FROM 
 ( 
 	SELECT  
        B4.B4_COD COD_PRODUTO,  
 		B1.B1_COD COD_SKU, 
 		B1.B1_DESC DESC_SKU,
		B1.R_E_C_N_O_ RECNOSB1
 	FROM  
 		SB4010 B4  
 		INNER JOIN SB1010 B1 ON B1.B1_FILIAL = '  ' AND B1.B1_ARTIGO = B4.B4_COD AND B1.B1_XIDSKU > 0 AND B1.B1_XENVECO = '2' AND B1.D_E_L_E_T_ = '' 
		INNER JOIN SBV010 BV ON BV.BV_FILIAL = '  ' AND BV.BV_CHAVE = SUBSTRING(B1.B1_COD,9,3) AND BV.BV_XIDITAT > 0 AND BV.BV_XENVECO = '2' AND BV.D_E_L_E_T_ = ''
 	WHERE 
 		B4.B4_FILIAL = '  ' AND 
 		B4.B4_XENVECO = '2' AND 
		B4.B4_XUSAECO = 'S' AND
 		B4.D_E_L_E_T_ = '' 
 )PROD_SKU 
 ORDER BY COD_SKU 
 
-- ALTERA PREÇO 
SELECT  
	B4.B4_COD CODPAI,  
	B1.B1_XIDSKU IDSKU,  
	B1.B1_COD CODIGO_SKU,  
	B1.B1_DESC DESC_SKU,  
	B1.R_E_C_N_O_ RECNOSB1  
FROM  
	SB1010 B1 (NOLOCK)  
	INNER JOIN SB4010 B4 (NOLOCK) ON B4.B4_FILIAL = '  ' AND B4.B4_COD = B1.B1_ARTIGO AND B4.B4_XUSAECO = 'S' AND B4.B4_XENVECO = '2' AND B4.D_E_L_E_T_ = ''  
WHERE  
	B1.B1_FILIAL = '' AND  
	B1.B1_XENVECO IN('2','3') AND  
	B1.D_E_L_E_T_ = ''  
ORDER BY B1.B1_ARTIGO,B1.B1_COD

-- ESTOQUE

SELECT 
	COD_SKU, 
	DESCRI, 
	ID_SKU, 
	RECNOSB2 
 FROM 
 ( 
	SELECT   
		B1.B1_COD COD_SKU,
		B1.B1_DESC DESCRI, 
		B1.B1_XIDSKU ID_SKU, 
		B2.R_E_C_N_O_ RECNOSB2 
	FROM 
		SB1010 B1 
		INNER JOIN SB2010 B2 ON B2.B2_COD = B1.B1_COD AND B2.B2_MSEXP = '' AND B2.D_E_L_E_T_ = '' 
	WHERE 
		B1.B1_FILIAL = '' AND 
		B1.B1_XENVECO IN('2','3') AND 
		B1.B1_XIDSKU <> 0 AND 
		B1.D_E_L_E_T_ = '' 
	GROUP BY B1.B1_COD, B1.B1_DESC, B1.B1_XIDSKU, B2.R_E_C_N_O_ 
 ) SALDO_ECOMM 
 ORDER BY COD_SKU 
 
 
 exec prc_web_relatorio_r_net022_artigo_disponibilidade_usuario_simples 
	@int_id_usuario=1,
	@vch_origem_id_usuario=N'W',
	@vch_representante=N'00',
	@vch_unidade_negocio=N'01',
	@vch_codigo_artigo=N'225.090'


EXECUTE dbo.prc_web_relatorio_r_net022_artigo_disponibilidade_malha_usuario_simples @vch_codigo_artigo = '', -- varchar(7)
    @vch_codigo_artigo_2 = '', -- varchar(7)
    @int_id_usuario = 1, -- int
    @vch_origem_id_usuario = 'W', -- varchar(1)
    @vch_representante = '00', -- varchar(6)
    @vch_unidade_negocio = '01' -- varchar(2)