SELECT  
	YP.YP_CHAVE,
	COALESCE(
		(	SELECT CAST(RTRIM(SYP.YP_TEXTO) AS VARCHAR(80)) + ';' AS [text()]
			FROM 
				SYP010 SYP
			WHERE 
				SYP.YP_CHAVE = YP.YP_CHAVE AND
				SYP.YP_CAMPO = 'B1_DESC_P ' AND 
				SYP.D_E_L_E_T_ = ''
			ORDER BY SYP.YP_CHAVE
			FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '') AS DESCECO
FROM 
	SYP010 YP
WHERE
	YP.YP_CHAVE = '000007' AND 
	YP.D_E_L_E_T_ = ''
GROUP BY YP.YP_CHAVE


SELECT * FROM SYP010 WHERE D_E_L_E_T_ = ''