SELECT * FROM ACU010 WHERE D_E_L_E_T_ = ''
SELECT * FROM ACV010 WHERE D_E_L_E_T_ = ''
SELECT * FROM ZA1010 WHERE D_E_L_E_T_ = ''
SELECT * FROM ZA2010 WHERE D_E_L_E_T_ = ''
SELECT * FROM ZA3010 WHERE D_E_L_E_T_ = ''
SELECT * FROM ZA7010 WHERE D_E_L_E_T_ = ''
SELECT * FROM SB1010 WHERE D_E_L_E_T_ = ''

SELECT DISTINCT(ACU.ACU_COD),ACU.ACU_DESC,ACU.ACU_CODPAI,ZA3.ZA3_CODCAR,ZA1.ZA1_DESCRI,ZA7_SEQVAL,ZA7_VALOR,SB1.B1_COD
FROM
ACU010 ACU
LEFT OUTER JOIN ZA3010 ZA3 ON ZA3.ZA3_CODCAT = ACU.ACU_COD AND ZA3.ZA3_STATUS = '1' AND ZA3.D_E_L_E_T_ = ''
LEFT OUTER JOIN ZA1010 ZA1 ON ZA1.ZA1_CODIGO = ZA3.ZA3_CODCAR AND ZA1.ZA1_STATUS = '1' AND ZA1.D_E_L_E_T_ = ''
LEFT OUTER JOIN ZA7010 ZA7 ON ZA7.ZA7_CODCAR = ZA3.ZA3_CODCAR AND ZA7.ZA7_STATUS = '1' AND ZA7.D_E_L_E_T_ = ''
LEFT OUTER JOIN SB1010 SB1 ON SB1.B1_COD = ZA7.ZA7_PRODUT AND SB1.B1_USAECO = '1' AND SB1.D_E_L_E_T_ = ''
WHERE 
ACU.ACU_STATUS = '1' AND

SELECT * FROM SB2010
SELECT * FROM DA1010
ACU.D_E_L_E_T_ = ''
ORDER BY ACU_COD,B1_COD,ZA3_CODCAR,ZA7_SEQVAL






	
 

