
SELECT 
	FILIAL,
	VENDA,
	SERIE,
	DATA,
	MES,
	ANO,
	CLIENTE,
	LOJA,
	NOME,
	VLRMERC,
	VLRDESC,
	VLRPAGO,
	PERDESC,
	CODTPCLI,
	MOTDESC,
	OPERADOR,
	APROVADOR
	FROM
	(
		SELECT 
			SL2.L2_FILIAL FILIAL,
			SL2.L2_DOC VENDA,
			SL2.L2_SERIE SERIE,
			SL1.L1_EMISNF DATA,
			SUBSTRING(SL1.L1_EMISNF,5,2) MES,
			SUBSTRING(SL1.L1_EMISNF,1,4) ANO,
			SL1.L1_CLIENTE CLIENTE,
			SL1.L1_LOJA LOJA,
			SA1.A1_NOME NOME,
			SUM(SL2.L2_PRCTAB) VLRMERC,
			IIF(SUM(SL2.L2_VALDESC) > 0 ,SUM(SL2.L2_VALDESC),SUM(SL1.L1_DESCONT)) VLRDESC,
			SUM(SL2.L2_VLRITEM) VLRPAGO,
			IIF(SL2.L2_DESC > 0, SL2.L2_DESC, SL1.L1_DESCNF) PERDESC,
			IIF(LEN(MDU.MDU_CODIGO) > 0,MDT.MDT_CODIGO, SL1.L1_01TPCLI) CODTPCLI,
			IIF(LEN(MDU.MDU_CODIGO) > 0,MDT.MDT_DESCRI,Z30.Z30_DESCRI) MOTDESC,
			SA6.A6_NOME OPERADOR,
			' ' APROVADOR
		FROM
			SL2990 SL2
			INNER JOIN SL1990 SL1 ON SL1.L1_FILIAL = SL2.L2_FILIAL AND SL1.L1_NUM = SL2.L2_NUM AND SL1.L1_DOC = SL2.L2_DOC AND SL1.L1_SERIE = SL2.L2_SERIE AND SL1.D_E_L_E_T_ = ''
			INNER JOIN SA1990 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.A1_COD = SL1.L1_CLIENTE AND SA1.A1_LOJA = SL1.L1_LOJA AND SA1.D_E_L_E_T_ = ' '
			INNER JOIN SA6990 SA6 ON SA6.A6_FILIAL = '  ' AND SA6.A6_COD = SL1.L1_OPERADO AND SA6.D_E_L_E_T_ = ' '
			LEFT OUTER JOIN Z30990 Z30 ON Z30.Z30_FILIAL = ' ' AND Z30.Z30_CODIGO = SL1.L1_01TPCLI AND Z30.D_E_L_E_T_ = ' '
			LEFT OUTER JOIN Z31990 Z31 ON Z31.Z31_FILIAL = ' ' AND Z31.Z31_CODLOJ = SL1.L1_FILIAL AND Z31.Z31_CODTPC = SL1.L1_01TPCLI AND Z31.D_E_L_E_T_ = ''
			LEFT OUTER JOIN MDU990 MDU ON MDU.MDU_FILIAL = SL1.L1_FILIAL AND MDU.MDU_DOC = SL1.L1_DOC AND MDU.MDU_SERIE = SL1.L1_SERIE AND MDU.D_E_L_E_T_ = ' '
			LEFT OUTER JOIN MDT990 MDT ON MDT.MDT_CODIGO = MDU.MDU_CODIGO AND MDT.D_E_L_E_T_ = ' ' 

		WHERE
			SL1.L1_FILIAL BETWEEN '  ' AND 'ZZ' AND 
			SL1.L1_EMISSAO BETWEEN '20150101' AND '20151231' AND
			SL1.L1_DOC <> '' AND 
			SL1.L1_SERIE <> '' AND 
			SL1.L1_TIPO = 'V'AND 
			SL1.L1_SITUA = 'OK' AND
			SL1.D_E_L_E_T_ = ''
		GROUP BY L2_FILIAL, L2_DOC, L2_SERIE, L1_EMISNF, SUBSTRING(L1_EMISNF,5,2), SUBSTRING(L1_EMISNF,1,4),  
				 L1_CLIENTE, L1_LOJA, A1_NOME, IiF(SL2.L2_DESC > 0, SL2.L2_DESC, SL1.L1_DESCNF),L1_01TPCLI,Z30_DESCRI,
				 Z31_PERCEN,MDU_CODIGO,MDT_CODIGO,MDT_DESCRI,L1_OPERADO,A6_NOME
) AS MOTDESC
ORDER BY FILIAL,VENDA, SERIE

