	SELECT 
		FILIAL,
		SUM(VLRBRUTO) VLRBRUTO,
		SUM(VLRDESCONTO) VLRDESCONTO,
		CODTPDESC,
		DESCRTPDESC
	FROM
	(
		SELECT 
			SL1.L1_FILIAL FILIAL,
			SL1.L1_VALMERC VLRBRUTO,

			IIF(SL1.L1_DESCONT > 0, 
				SL1.L1_DESCONT, 
				(
					SELECT 
						SUM(SL2.L2_VALDESC) 
					FROM 
						SL2990 SL2 
					WHERE 
						SL2.L2_NUM = SL1.L1_NUM AND 
						SL2.D_E_L_E_T_ = ''
				 ) 
			) VLRDESCONTO,

			IIF(LEN(SL1.L1_01TPCLI) > 0,
				SL1.L1_01TPCLI,
				(
					SELECT 
						DISTINCT MDU.MDU_CODIGO
					FROM 
						MDU990 MDU 
					WHERE
						MDU.MDU_FILIAL = SL1.L1_FILIAL AND 
						MDU.MDU_DOC = SL1.L1_DOC AND 
						MDU.MDU_SERIE = SL1.L1_SERIE AND 
						MDU.D_E_L_E_T_ = ''					
				)	
			)  CODTPDESC,

			IIF(LEN(SL1.L1_01DESTP) > 0,
				SL1.L1_01DESTP,
				(
					SELECT 
						DISTINCT MDT.MDT_DESCRI
					FROM 
						MDU990 MDU 
						INNER JOIN MDT990 MDT ON MDT.MDT_FILIAL = MDU.MDU_FILIAL AND MDT.MDT_CODIGO = MDU.MDU_CODIGO AND MDT.D_E_L_E_T_ = ''	
					WHERE
						MDU.MDU_FILIAL = SL1.L1_FILIAL AND 
						MDU.MDU_DOC = SL1.L1_DOC AND 
						MDU.MDU_SERIE = SL1.L1_SERIE AND 
						MDU.D_E_L_E_T_ = ''	
				)
			)   DESCRTPDESC		
		FROM
			SL1990 SL1
		
		WHERE 
				SL1.L1_FILIAL BETWEEN '  ' AND 'ZZ' AND 
				SL1.L1_EMISNF BETWEEN '20150101' AND '20150618' AND 
				SL1.L1_DOC <> ' ' AND 
				SL1.L1_SERIE <> ' ' AND 
				SL1.L1_TIPO = 'V' AND 
				SL1.L1_SITUA = 'OK' AND 
				SL1.D_E_L_E_T_ = '' 
	) AS MOTDESC
	GROUP BY FILIAL, CODTPDESC, DESCRTPDESC 

