-- CATEGORIAS
SELECT 
	CATEG_PAI.ACU_COD CODPAI,
	CATEG_PAI.ACU_XIDLV IDVTPAI,
	ACU.ACU_FILIAL,
	ACU.ACU_COD,
	ACU.ACU_DESC,
	ACU.ACU_XTITUL,
	ACU.ACU_XKWORD,
	ACU.ACU_XLCMPC,
	ACU.ACU_XREMAR,
	ACU.ACU_XIDLV,
	ACU.R_E_C_N_O_ RECNOACU
FROM 
	ACU010 ACU (NOLOCK)
	OUTER APPLY(
		SELECT 
			ACU_PAI.ACU_COD,
			ACU_PAI.ACU_XIDLV
		FROM 
			ACU010 ACU_PAI (NOLOCK)
		WHERE 
			ACU.ACU_FILIAL = '' AND 
			ACU_PAI.ACU_COD = ACU.ACU_CODPAI AND 
			ACU_PAI.D_E_L_E_T_ = ''
	) CATEG_PAI
WHERE 
	ACU.ACU_FILIAL = '' AND 
	ACU.ACU_XINTLV = '2' AND
	ACU.D_E_L_E_T_ = ''
ORDER BY ACU.ACU_CODPAI,ACU.ACU_COD

-- MARCAS
SELECT 
	ZTD_COD,
	ZTD_DESC,
	ZTD_IDVTX,
	ZTD_NOME,
	ZTD_KWORD,
	ZTD_TITULO,
	ZTD.R_E_C_N_O_ RECNOZTD
FROM 
	ZTD010 ZTD (NOLOCK)
WHERE 
	ZTD.ZTD_FILIAL = '' AND 
	ZTD.ZTD_INTLV = '1' AND 
	ZTD.D_E_L_E_T_ = ''
	
-- PRODUTOS 
SELECT 
	GRADE,
	FILIAL,
	PR_IDPROD,
	PR_CODIGO,
	PR_DESCRICAO, 
	PR_DESC_TECNICA,
	PR_NCM,
	PR_DEPARTAMENTO,
	PR_CATEGORIA,
	PR_MARCA,
	PR_DESC_MARCA,
	PR_STATUS,
	EC_TITULO,
	EC_DESCRICAO,
	EC_CARACTERISTICA,
	EC_FLAG,
	EC_CUBAGEM,
	EC_PROFUNDIDADE,
	EC_COMPRIMENTO,
	EC_LARGURA,
	RECNOPROD
FROM (
	SELECT 
		'S' GRADE,
		B4.B4_FILIAL FILIAL,
		B4.B4_XIDPRD PR_IDPROD,
		B4.B4_COD PR_CODIGO,
		B4.B4_DESC PR_DESCRICAO, 
		ISNULL(CAST(CAST(B4_XDESCTE AS BINARY(2048)) AS VARCHAR(2048)),'') PR_DESC_TECNICA,
		B4_POSIPI PR_NCM,
		'' PR_DEPARTAMENTO,
		'' PR_CATEGORIA,
		ZTD.ZTD_IDLV PR_MARCA,
		ZTD.ZTD_DESC PR_DESC_MARCA,
		B4.B4_XATIVO PR_STATUS,
		ISNULL(CAST(CAST(MHH_ECTITU AS BINARY(2048)) AS VARCHAR(2048)),'') EC_TITULO,
		ISNULL(CAST(CAST(MHH_ECDESC AS BINARY(2048)) AS VARCHAR(2048)),'') EC_DESCRICAO,
		ISNULL(CAST(CAST(MHH_ECCARA AS BINARY(2048)) AS VARCHAR(2048)),'') EC_CARACTERISTICA,
		MHH_FLAG EC_FLAG,
		MHH_ECCUBA EC_CUBAGEM,
		MHH_ECPROF EC_PROFUNDIDADE,
		MHH_ECCOMP EC_COMPRIMENTO,
		MHH_ECLARG EC_LARGURA,
		B4.R_E_C_N_O_ RECNOPROD
	FROM 
		SB4010 B4 (NOLOCK)
		INNER JOIN MHH010 MHH (NOLOCK) ON MHH.MHH_FILIAL = B4.B4_FILIAL AND MHH.MHH_COD = B4.B4_COD AND MHH.D_E_L_E_T_ = ''
		INNER JOIN ZTD010 ZTD (NOLOCK) ON ZTD.ZTD_FILIAL = '' AND ZTD.ZTD_COD = B4.B4_XMARCA AND ZTD.D_E_L_E_T_ = ''
	WHERE 
		B4.B4_FILIAL = '' AND 
		B4.B4_XINTLV  = '1' AND 
		B4.B4_COD = 'VIC85104' AND
		B4.D_E_L_E_T_ = ''
	UNION ALL 
	SELECT 
		'N' GRADE,
		B1.B1_FILIAL FILIAL,
		B1.B1_XIDPRD PR_IDPROD,
		B1.B1_COD PR_CODIGO,
		B1.B1_DESC PR_DESCRICAO, 
		ISNULL(CAST(CAST(B1_XDESCTE AS BINARY(2048)) AS VARCHAR(2048)),'') PR_DESC_TECNICA,
		B1_POSIPI PR_NCM,
		'' PR_DEPARTAMENTO,
		'' PR_CATEGORIA,
		ZTD.ZTD_IDLV PR_MARCA,
		ZTD.ZTD_DESC PR_DESC_MARCA,
		B1.B1_XATIVO PR_STATUS,
		B5_ECTITU EC_TITULO,
		ISNULL(CAST(CAST(B5_ECDESCR AS BINARY(2048)) AS VARCHAR(2048)),'') EC_DESCRICAO,
		ISNULL(CAST(CAST(B5_ECCARAC AS BINARY(2048)) AS VARCHAR(2048)),'') EC_CARACTERISTICA,
		B5_ECFLAG EC_FLAG,
		B5_ECCUBAG EC_CUBAGEM,
		B5_ECPROFU EC_PROFUNDIDADE,
		B5_ECCOMP EC_COMPRIMENTO,
		B5_ECLARGU EC_LARGURA,
		B1.R_E_C_N_O_ RECNOPROD
	FROM 
		SB1010 B1 (NOLOCK)
		INNER JOIN SB5010 B5 (NOLOCK) ON B5.B5_FILIAL = B1.B1_FILIAL AND B5.B5_COD = B1.B1_COD AND B5.D_E_L_E_T_ = ''
		INNER JOIN ZTD010 ZTD (NOLOCK) ON ZTD.ZTD_FILIAL = '' AND ZTD.ZTD_COD = B1.B1_XMARCA AND ZTD.D_E_L_E_T_ = ''
	WHERE 
		B1.B1_FILIAL = '' AND 
		B1.B1_GRADE IN('','N') AND 
		B1.B1_XINTLV = '1' AND 
		B1.D_E_L_E_T_ = ''
)PRODUTOS 

-- SKU 
SELECT 
	GRADE,
	PR_CODPROD,
	PR_IDVTEX,
	PR_DESC,
	SKU_COD,
	SKU_IDVTEX,
	SKU_DESC,
	SKU_TITULO,
	SKU_EAN,
	SKU_ALTURA,
	SKU_LARGURA,
	SKU_PROFUNDIDADE,
	SKU_ALTURA_EMB,
	SKU_LARGURA_EMB,
	SKU_PROFUNDIDADE_EMB,
	SKU_CUBAGEM,
	SKU_PESO_LIQUIDO,
	SKU_FRABRICANTE,
	SKU_UNIDADE_MEDIDA,
	SKU_NCM,
	SKU_PRECO_CUSTO,
	SKU_PRECO_VENDA,
	SKU_STATUS,
	SKU_BLOQUEIO,
	SKU_RECNO
FROM (
	SELECT 
		B1.B1_GRADE GRADE,
		B4.B4_COD PR_CODPROD,
		B4.B4_XIDPRD PR_IDVTEX,
		B4.B4_DESC PR_DESC,
		B1.B1_COD SKU_COD,
		B1.B1_XIDSKU SKU_IDVTEX,
		B1.B1_DESC SKU_DESC,
		LINHA.BV_DESCRI + ' ' + COLUNA.BV_DESCRI SKU_TITULO,
		B1.B1_CODBAR SKU_EAN,
		B5.B5_ALTURA SKU_ALTURA,
		B5.B5_LARG SKU_LARGURA,
		B5.B5_COMPR SKU_PROFUNDIDADE,
		B5.B5_ALTURLC SKU_ALTURA_EMB,
		B5.B5_LARGLC SKU_LARGURA_EMB,
		B5.B5_COMPRLC SKU_PROFUNDIDADE_EMB,
		1 SKU_CUBAGEM,
		B1.B1_PESO SKU_PESO_LIQUIDO,
		B1_FABRIC SKU_FRABRICANTE,
		B1_UM SKU_UNIDADE_MEDIDA,
		B1.B1_POSIPI SKU_NCM,
		B1.B1_PRV1 SKU_PRECO_CUSTO,
		B1.B1_PRV1 SKU_PRECO_VENDA,
		B1.B1_XATIVO SKU_STATUS,
		B1.B1_MSBLQL SKU_BLOQUEIO,
		B1.R_E_C_N_O_ SKU_RECNO
	FROM 
		SB1010 B1 (NOLOCK) 
		INNER JOIN SB4010 B4 (NOLOCK) ON B4.B4_FILIAL = B1.B1_FILIAL AND B4.B4_COD = SUBSTRING(B1.B1_COD,1,10) AND B4.B4_XINTLV = '2' AND B4.B4_XIDPRD > 0 AND B4.D_E_L_E_T_ = ''
		INNER JOIN SB5010 B5 (NOLOCK) ON B5.B5_FILIAL = B1.B1_FILIAL AND B5.B5_COD = B1.B1_COD AND B5.D_E_L_E_T_ = '' 
		CROSS APPLY (
			SELECT 
				RTRIM(BV.BV_DESCRI) BV_DESCRI
			FROM 
				SBV010 BV (NOLOCK)
			WHERE 
				BV.BV_FILIAL = '' AND 
				BV.BV_TABELA = B4.B4_LINHA AND 
				BV.BV_TIPO = '1' AND 
				BV.BV_CHAVE = SUBSTRING(B1.B1_COD,11,3) AND 
				BV.D_E_L_E_T_ = ''
		) LINHA 
		CROSS APPLY (
			SELECT 
				RTRIM(BV.BV_DESCRI) BV_DESCRI
			FROM 
				SBV010 BV (NOLOCK)
			WHERE 
				BV.BV_FILIAL = '' AND 
				BV.BV_TABELA = B4.B4_COLUNA AND 
				BV.BV_TIPO = '2' AND 
				BV.BV_CHAVE = SUBSTRING(B1.B1_COD,14,2) AND 
				BV.D_E_L_E_T_ = ''
		) COLUNA
	WHERE 
		B1.B1_FILIAL = '' AND 
		B1.B1_GRADE = 'S' AND
		B1.B1_XINTLV = '1' AND 
		B1.D_E_L_E_T_ = ''	
	UNION ALL 
	SELECT 
		B1.B1_GRADE GRADE,
		B1.B1_COD PR_CODPROD,
		B1.B1_XIDPRD PR_IDVTEX,
		B1.B1_DESC PR_DESC,
		B1.B1_COD SKU_COD,
		B1.B1_XIDSKU SKU_IDVTEX,
		B1.B1_DESC SKU_DESC,
		B5_ECTITU SKU_TITULO,
		B1.B1_CODBAR SKU_EAN,
		B5.B5_ALTURA SKU_ALTURA,
		B5.B5_LARG SKU_LARGURA,
		B5.B5_COMPR SKU_PROFUNDIDADE,
		B5.B5_ALTURLC SKU_ALTURA_EMB,
		B5.B5_LARGLC SKU_LARGURA_EMB,
		B5.B5_COMPRLC SKU_PROFUNDIDADE_EMB,
		1 SKU_CUBAGEM,
		B1.B1_PESO SKU_PESO_LIQUIDO,
		B1_FABRIC SKU_FRABRICANTE,
		B1_UM SKU_UNIDADE_MEDIDA,
		B1.B1_POSIPI SKU_NCM,
		B1.B1_PRV1 SKU_PRECO_CUSTO,
		B1.B1_PRV1 SKU_PRECO_VENDA,
		B1.B1_XATIVO SKU_STATUS,
		B1.B1_MSBLQL SKU_BLOQUEIO,
		B1.R_E_C_N_O_ SKU_RECNO
	FROM 
		SB1010 B1 (NOLOCK) 
		INNER JOIN SB5010 B5 (NOLOCK) ON B5.B5_FILIAL = B1.B1_FILIAL AND B5.B5_COD = B1.B1_COD AND B5.D_E_L_E_T_ = '' 
	WHERE 
		B1.B1_FILIAL = '' AND 
		B1.B1_GRADE IN('','N') AND
		B1.B1_XINTLV = '1' AND 
		B1.B1_XIDPRD > 0 AND
		B1.D_E_L_E_T_ = ''
) SKU

-- GRUPOS ESPECIFICOS
SELECT 
	ZTI.ZTI_CODIGO,
	ZTI.ZTI_DESC,
	ZTI.ZTI_IDVTX,
	COALESCE(ACU.ACU_XIDLV,0) ACU_XIDLV,
	ZTI.R_E_C_N_O_ RECNOZTI
FROM 
	ZTI010 ZTI 
	LEFT JOIN ACU010 ACU (NOLOCK) ON ACU.ACU_FILIAL = '' AND ACU.ACU_COD = ZTI.ZTI_CATEG AND ACU.D_E_L_E_T_ = ''
WHERE 
	ZTI_FILIAL = '' AND 
	ZTI_INTLV = '1' AND 
	D_E_L_E_T_ = ''
	
-- CAMPOS ESPEFICICOS 
SELECT 
	ZTE.ZTE_COD,
	ZTE.ZTE_TPCAMP,
	ZTE.ZTE_IDGRUP,
	ZTE.ZTE_NOME,
	ZTE.ZTE_DESC,
	ZTE.ZTE_FILTRO,
	ZTE.ZTE_ATIVO,
	ZTE.ZTE_OBRIGA,
	ZTE.ZTE_IDCAMP,
	ZTE.ZTE_SKUPRD,
	ZTE.R_E_C_N_O_ RECNOZTE,
	ACU.ACU_XIDLV
FROM 
	ZTE010 ZTE 
	INNER JOIN ACU010 ACU (NOLOCK) ON ACU.ACU_FILIAL = '' AND ACU.ACU_COD = ZTE.ZTE_CATEGO AND ACU.D_E_L_E_T_ = ''
WHERE 
	ZTE.ZTE_FILIAL = '' AND 
	ZTE.ZTE_XINTLV = '1' AND 
	ZTE.D_E_L_E_T_ = ''