SELECT 
	distinct 
	A1_CGC,
	'EXTERNO BUNZL',
	'',
	'',
	CASE WHEN CharIndex(';', A1_EMAIL) > 0 THEN RTRIM(SUBSTRING(A1_EMAIL,1,CharIndex(';', A1_EMAIL) - 1)) ELSE RTRIM(A1_EMAIL) END A1_EMAIL,
	A1_INSCRM,
	A1_CGC,
	A1_COD,
	A1_LOJA,
	'004',
	A1_CGC,
	A1_NOME,
	CASE WHEN CharIndex(';', A1_EMAIL) > 0 THEN RTRIM(SUBSTRING(A1_EMAIL,1,CharIndex(';', A1_EMAIL) - 1)) ELSE RTRIM(A1_EMAIL) END A1_EMAIL,
	A1_DDD,
	REPLACE(REPLACE(REPLACE(A1_TEL,'.', ''),'-', ''),'/', '') A1_TEL,
	A1_CGC,
	A1_CGC,
	A1_NOME,
	A1_NREDUZ,
	A1_DTNASC,
	A1_CNAE,
	COALESCE(CC3_DESC,'') CC3_DESC,
	'',
	'',
	'',
	'(' + RTRIM(A1_DDD) + ') ' + RTRIM(A1_TEL) A1_TEL,
	CASE WHEN CharIndex(';', A1_EMAIL) > 0 THEN SUBSTRING(A1_EMAIL,1,CharIndex(';', A1_EMAIL) - 1) ELSE RTRIM(A1_EMAIL) END A1_EMAIL,
	A1_CEP,
	CASE WHEN CharIndex(',', A1_END) > 0 THEN SUBSTRING(A1_END,1,CharIndex(',', A1_END) - 1) ELSE A1_END END A1_END,
	CASE WHEN CharIndex(',', A1_END) > 0 THEN SUBSTRING(A1_END,CharIndex(',', A1_END) + 1, 10) ELSE '' END A1_NUMERO,
	A1_COMPLEM,
	A1_MUN,
	A1_BAIRRO,
	A1_EST,
	A1_CGC,
	'',
	'',
	'',
	A1_CGC,
	A1_INSCR,
	A1_NOME,
	A1_NREDUZ,
	A1_CGC,
	A1_SUFRAMA,
	A1_CGC,
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	A1_COD_MUN,
	A1_CGC,
	A1_NOME,
	A1_NREDUZ,
	A1_END
FROM 
	SA1010 A1 WITH(NOLOCK)
	LEFT JOIN CC3010 CC3 WITH(NOLOCK) ON CC3.CC3_COD = A1.A1_CNAE AND CC3.D_E_L_E_T_ = ''
WHERE 
	A1_FILIAL = '' AND 
	A1_PESSOA = 'J' AND 
	--A1_TIPO = 'X' AND
	--A1_MSBLQL <> '1' AND 
	( A1_CGC <> '00000000000000' AND A1_CGC <> '' ) AND 
	A1_CNAE = '' AND
	A1.D_E_L_E_T_ = ''

