SELECT 
		A1_COD
		,A1_LOJA
		,A1_NOME
		,[TTAT_FIELD]
		,[TTAT_COLD]
		,[TTAT_CNEW]
		,A1.A1_TIPO
		,A1_SATIV1
		--,CC3.CC3_XTIPO
		,A1.A1_TABELA
		,DA0.DA0_DESCRI
  FROM 
	SA1040_TTAT_LOG AUD
	INNER JOIN SA1040 A1 ON A1.A1_FILIAL = '' AND A1.R_E_C_N_O_ = AUD.TTAT_RECNO AND A1.D_E_L_E_T_ = ''
	INNER JOIN CC3040 CC3 ON CC3.CC3_FILIAL = '' AND CC3.CC3_COD = A1.A1_CNAE AND CC3.D_E_L_E_T_ = ''
	INNER JOIN DA0040 DA0 ON DA0.DA0_FILIAL = '0404' AND DA0.DA0_CODTAB = A1.A1_TABELA AND DA0.D_E_L_E_T_ = ''
	--INNER JOIN 
  WHERE 
	AUD.TTAT_DTIME > '20231211'
	AND AUD.TTAT_FIELD = 'A1_TIPO'
	AND AUD.TTAT_USER = 'gateway'
	AND AUD.TTAT_CNEW = 'F' 
	--AND AUD.TTAT_COLD = 'R' 
GROUP BY A1_COD
		,A1_LOJA
		,A1_NOME
		,[TTAT_FIELD]
		,[TTAT_COLD]
		,[TTAT_CNEW]
		,A1.A1_TIPO
		,A1_SATIV1
		,CC3.CC3_XTIPO
		,A1.A1_TABELA
		,DA0.DA0_DESCRI

