SELECT
	ROW_NUMBER() OVER(ORDER BY A2_TIPO DESC) NIF,
	'EXTORNO BUNZL',
	'',
	'',
	A2_COD,
	A2_NOME,
	A2_END,
	CASE WHEN CharIndex(',', A2_END) > 0 THEN RTRIM(SUBSTRING(A2_END,CharIndex(',', A2_END) + 1,30)) ELSE '' END A2_NUMERO,
	A2_COMPLEM,
	A2_BAIRRO,
	A2_MUN,
	A2_CODPAIS,
	A2_EST,
	A2_CEP,
	ROW_NUMBER() OVER(ORDER BY A2_TIPO DESC) NIF,
	A2_COD,
	A2_LOJA,
	'004',
	ROW_NUMBER() OVER(ORDER BY A2_TIPO DESC) NIF,
	A2_NOME,
	CASE WHEN CharIndex(';', A2_EMAIL) > 0 THEN RTRIM(SUBSTRING(A2_EMAIL,1,CharIndex(';', A2_EMAIL) - 1)) ELSE RTRIM(A2_EMAIL) END A1_EMAIL,
	A2_DDI,
	A2_TEL
	
FROM 
	SA2010 A2 
	LEFT JOIN SX5010 X5 ON X5.X5_FILIAL = '0404' AND X5_TABELA = '58' AND X5_CHAVE = A2.A2_FORMPAG AND X5.D_E_L_E_T_ = ''
WHERE 
	A2_EST = 'EX' AND 
	A2.D_E_L_E_T_ = '' 
