SELECT 
	ID_PAY, 
	DT_EMISS, 
	DT_PGTO, 
	PARCELA, 
	VALOR_TOTAL, 
	VALOR_LIQUIDO, 
	VALOR_TAXA, 
	VALOR_REEMBOLSO, 
	TITULO, 
	PREFIXO, 
	ID_PAY_TITULO, 
	DT_EMISS_TITULO, 
	DT_PGTO_TITULO, 
	PARCELA_TITULO, 
	VALOR_TOTAL_TITULO, 
    CASE 
		WHEN ( ( VALOR_TOTAL - VALOR_TOTAL_TITULO ) < -10  AND ( VALOR_TOTAL - VALOR_TOTAL_TITULO ) < 0 )   THEN 
			'2' 
		WHEN ( ( VALOR_TOTAL - VALOR_TOTAL_TITULO ) > 10 ) THEN 
			'2' 
		ELSE 
			'1' 
	END STATUS 
 FROM 
 ( 
	SELECT 
		XTP.XTP_IDPAY ID_PAY, 
		XTP.XTP_DTEMIS DT_EMISS, 
		XTP.XTP_DTPGTO DT_PGTO, 
		XTP.XTP_PARC PARCELA, 
		XTP.XTP_VALOR VALOR_TOTAL, 
		XTP.XTP_VLRLIQ VALOR_LIQUIDO, 
		XTP.XTP_TAXA VALOR_TAXA, 
		XTP.XTP_VLRREB VALOR_REEMBOLSO, 
		COALESCE(E1.E1_NUM,'') TITULO, 
		COALESCE(E1.E1_PREFIXO,'') PREFIXO, 
		COALESCE(E1.E1_DOCTEF,'') ID_PAY_TITULO, 
		COALESCE(E1.E1_EMISSAO,'') DT_EMISS_TITULO, 
		COALESCE(E1.E1_VENCREA,'') DT_PGTO_TITULO, 
		COALESCE(E1.E1_PARCELA,'') PARCELA_TITULO, 
		COALESCE(E1.E1_VALOR,0) VALOR_TOTAL_TITULO 
	FROM 
		XTP040 XTP  
		INNER JOIN SE1040 E1 ON E1.E1_FILORIG = XTP.XTP_FILIAL AND E1.E1_PARCELA = IIF(E1.E1_PARCELA = '','',XTP.XTP_PARC) AND E1.E1_DOCTEF = XTP.XTP_IDPAY AND E1.E1_BAIXA = '' AND E1.E1_SALDO > 0 AND E1.E1_TIPO = 'PGM' AND E1.D_E_L_E_T_ = '' 
	WHERE 
		XTP.XTP_FILIAL = '0404' AND 
		XTP.XTP_STATUS = '1' AND 
        XTP.XTP_STAPAY = 'paid' AND 
		XTP.XTP_VALOR > 0 AND 
		XTP.D_E_L_E_T_ = ''	
 )ID_PAGAMENTO 
 GROUP BY ID_PAY,DT_EMISS,DT_PGTO,PARCELA,VALOR_TOTAL,VALOR_LIQUIDO,VALOR_TAXA,VALOR_REEMBOLSO,TITULO,PREFIXO,ID_PAY_TITULO,DT_EMISS_TITULO,DT_PGTO_TITULO,PARCELA_TITULO,VALOR_TOTAL_TITULO 
 ORDER BY DT_EMISS, ID_PAY 