SELECT 
	A1_CGC,
	'',
	'',
	'',
	CASE WHEN CharIndex(';', A1_EMAIL) > 0 THEN SUBSTRING(A1_EMAIL,1,CharIndex(';', A1_EMAIL) - 1) ELSE RTRIM(A1_EMAIL) END A1_EMAIL,
	A1_CGC,
	A1_COD,
	A1_LOJA,
	'001',
	A1_CGC,
	A1_NOME,
	CASE WHEN CharIndex(';', A1_EMAIL) > 0 THEN SUBSTRING(A1_EMAIL,1,CharIndex(';', A1_EMAIL) - 1) ELSE RTRIM(A1_EMAIL) END A1_EMAIL,
	A1_DDD,
	REPLACE(REPLACE(REPLACE(A1_TEL,'.', ''),'-', ''),'/', '') A1_TEL,
	A1_TEL2,
	A1_CGC,
	A1_CEP,
	CASE WHEN CharIndex(',', A1_END) > 0 THEN SUBSTRING(A1_END,CharIndex(',', A1_END) + 1, 10) ELSE '' END A1_NUMERO,
	A1_COMPLEM,
	A1_CGC,
	A1_NOME,
	'',
	'',
	A1_DTNASC,
	'',
	'',
	A1_PAIS,
	'',
	A1_CGC,
	A1_CEP,
	CASE WHEN CharIndex(',', A1_END) > 0 THEN SUBSTRING(A1_END,1,CharIndex(',', A1_END) - 1) ELSE A1_END END A1_END,
	CASE WHEN CharIndex(',', A1_END) > 0 THEN SUBSTRING(A1_END,1,CharIndex(',', A1_END) - 1) ELSE A1_END END A1_END,
	CASE WHEN CharIndex(',', A1_END) > 0 THEN SUBSTRING(A1_END,CharIndex(',', A1_END) + 1, 10) ELSE '' END A1_NUMERO,
	A1_COMPLEM,
	A1_BAIRRO,
	A1_BAIRRO,
	A1_EST,
	A1_EST,
	A1_COD_MUN
FROM 
	SA1040 A1 WITH(NOLOCK)
WHERE 
	A1_FILIAL = '' AND 
	A1_PESSOA = 'F' AND 
	A1_MSBLQL <> '1' AND 
	A1.D_E_L_E_T_ = ''