SELECT 
SUM(PESOL) PESOL, 
SUM(PESOB) PESOB, 
ROUND(SUM(CUBAGEM_MASTER + CUBAGEM_UNITARIO),4) CUB_TOTAL 
FROM 
( 
SELECT 
    SUM(SUB.UB_QUANT * SB1.B1_PESO) PESOL, 
    SUM(SUB.UB_QUANT * SB1.B1_PESO) PESOB, 
CASE 
    	WHEN SUB.UB_XCAIXA <> '' AND SUB.UB_QUANT >= SB5.B5_QE2 THEN 
    		SUM( (SB5.B5_ALTURLC * SB5.B5_LARGLC * SB5.B5_COMPRLC) * IIF(SUB.UB_XVOLUME > 1, SUB.UB_XVOLUME - 1, SUB.UB_XVOLUME) )
    	WHEN SUB.UB_XCAIXA = '' AND SUB.UB_QUANT >= SB5.B5_QE2 THEN 
    		SUM( (SB5.B5_ALTURLC * SB5.B5_LARGLC * SB5.B5_COMPRLC) * SUB.UB_XVOLUME )
    	ELSE 
    		0 
    END CUBAGEM_MASTER, 
    CASE 
    	WHEN SUB.UB_XCAIXA <> '' THEN 
			SUM( ROUND( ( SUB.UB_QUANT/SB5.B5_QE2) ) )
			--SUM( ROUND( ( SUB.UB_QUANT/SB5.B5_QE2) - FLOOR(SUB.UB_QUANT/SB5.B5_QE2),4,1) )
			--SUM( XTA.XTA_ALTURA * XTA.XTA_LARG * XTA.XTA_COMPR  * IIF(SUB.UB_XVOLUME > 1, SUB.UB_XVOLUME - 1, SUB.UB_XVOLUME) ) 
    	ELSE 
    		SUM( ROUND( ( SUB.UB_QUANT/SB5.B5_QE2) - FLOOR(SUB.UB_QUANT/SB5.B5_QE2),4,1) * SB5.B5_QE2 * (SB5.B5_ALTURA * SB5.B5_LARG * SB5.B5_COMPR) )   
    END CUBAGEM_UNITARIO 
FROM SUB040 SUB 
    LEFT JOIN SB1040 SB1 ON SB1.B1_FILIAL = '    ' AND SB1.B1_COD = SUB.UB_PRODUTO AND SB1.D_E_L_E_T_ <> '*' 
    LEFT JOIN SB5040 SB5 ON SB5.B5_FILIAL = '    ' AND SB5.B5_COD = SUB.UB_PRODUTO AND SB5.D_E_L_E_T_ <> '*' 
    LEFT JOIN XTA040 XTA ON XTA.XTA_FILIAL= '    ' AND XTA.XTA_CODIGO = SUB.UB_XCAIXA AND XTA.D_E_L_E_T_ <> '*' 
WHERE 
    SUB.UB_FILIAL  = '0404' 
    AND   SUB.UB_NUM     = '175634' 
    AND   SUB.D_E_L_E_T_ = '' 
GROUP BY SUB.UB_XCAIXA,SUB.UB_QUANT,SB5.B5_QE2 
)CUBAGEM_TOTAL 