SELECT 
	CODIGO,
	LOJA,
	RAZAO,
	( VALOR_TOTAL / TOTAL_NOTAS) TICKET
FROM 
(
	SELECT 
		A1.A1_COD CODIGO,
		A1.A1_LOJA LOJA,
		A1.A1_NOME RAZAO,
		SUM(F2.F2_VALBRUT) VALOR_TOTAL,
		COUNT(F2.F2_DOC) TOTAL_NOTAS
		--CONVERT(date,A1.A1_ULTCOM,101) ULTIMA_COMPRA,
		--CONVERT(varchar,DATEADD(MONTH,-6,CONVERT(date,A1.A1_ULTCOM,101)),112) SEIS_MESES
	FROM 
		SA1040 A1 
		INNER JOIN SF2040 F2 ON F2.F2_FILIAL = '0404' AND F2.F2_CLIENTE = A1.A1_COD AND F2.F2_LOJA = A1.A1_LOJA AND F2.F2_TIPO = 'N' AND F2.F2_EMISSAO BETWEEN CONVERT(varchar,DATEADD(MONTH,-6,CONVERT(date,A1.A1_ULTCOM,101)),112) AND A1.A1_ULTCOM AND F2.D_E_L_E_T_ = ''
	WHERE 
		A1.A1_FILIAL = '' AND 
		A1.A1_MSBLQL <> '1' AND 
		A1.A1_ULTCOM <> '' AND 
		A1.D_E_L_E_T_ = ''
	GROUP BY A1.A1_COD,	A1.A1_LOJA,	A1.A1_NOME
) TICKET_MEDIDO
