SELECT 
	ZXJ.ZXJ_ORC,
	COUNT(ZXJ.ZXJ_REVISA) REVISAO,
	CONVERT(date,DT_INI.DT_INI,101) DT_INI,
	DT_INI.HR_INI,
	CONVERT(date,DT_FIM.DT_FIM,101) DT_FIM,
	DT_FIM.HR_FIM
FROM 
	ZXJ040 ZXJ
	CROSS APPLY(
		SELECT 
			MIN(ZXJ_1.ZXJ_DTINI) DT_INI,
			MIN(ZXJ_1.ZXJ_HRINI) HR_INI
		FROM 
			ZXJ040 ZXJ_1
		WHERE 
			ZXJ_1.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
			ZXJ_1.ZXJ_ORC = ZXJ.ZXJ_ORC AND
			ZXJ_1.ZXJ_REVISA = ( 
									SELECT 
										MIN(ZXJ_A.ZXJ_REVISA) 
									FROM 
										ZXJ040 ZXJ_A 
									WHERE 
										ZXJ_A.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
										ZXJ_A.ZXJ_ORC = ZXJ.ZXJ_ORC AND 
										ZXJ_A.D_E_L_E_T_ = '' 
								)  AND 
			ZXJ_1.D_E_L_E_T_ = ''
		--GROUP BY ZXJ_1.ZXJ_ORC
	) DT_INI
	CROSS APPLY( 
		SELECT 
			MIN(ZXJ_2.ZXJ_DTFIM) DT_FIM,
			MIN(ZXJ_2.ZXJ_HRFIM) HR_FIM
		FROM 
			ZXJ040 ZXJ_2
		WHERE 
			ZXJ_2.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
			ZXJ_2.ZXJ_ORC = ZXJ.ZXJ_ORC AND
			ZXJ_2.ZXJ_REVISA = ( 
									SELECT 
										MAX(ZXJ_A.ZXJ_REVISA) 
									FROM 
										ZXJ040 ZXJ_A 
									WHERE 
										ZXJ_A.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
										ZXJ_A.ZXJ_ORC = ZXJ.ZXJ_ORC AND 
										ZXJ_A.D_E_L_E_T_ = '' 
								)  AND 
			ZXJ_2.D_E_L_E_T_ = ''
		--GROUP BY ZXJ_2.ZXJ_ORC
	) DT_FIM
WHERE 
	ZXJ.ZXJ_FILIAL = '0404' AND 
	ZXJ.ZXJ_DTINI BETWEEN '20211101' AND '20220131' AND 
	ZXJ.ZXJ_PEDIDO <> '' AND 
	--ZXJ.ZXJ_ORC = '118057' AND
	ZXJ.D_E_L_E_T_ = ''
GROUP BY ZXJ_ORC,DT_INI.DT_INI,DT_INI.HR_INI,DT_FIM.DT_FIM,DT_FIM.HR_FIM
ORDER BY ZXJ_ORC