SELECT 
	TOTAL_ORCAMENTOS,
	TOTAL_PEDIDOS,
	ROUND( ( CAST(TOTAL_PEDIDOS AS FLOAT) / CAST(TOTAL_ORCAMENTOS AS FLOAT) ) * 100, 2 ) TAXA_CONVERSAO
FROM 
(
	SELECT 
		SUM( ORCAMENTOS ) TOTAL_ORCAMENTOS,
		SUM( PEDIDOS ) TOTAL_PEDIDOS
	FROM 
	(
		SELECT 
			1 ORCAMENTOS,
			0 PEDIDOS
		FROM 
			ZXJ040 ZXJ WITH(NOLOCK)
			CROSS APPLY(
				SELECT 
					ZXJ_1.ZXJ_ORC ORCAMENTO
				FROM 
					ZXJ040 ZXJ_1 WITH(NOLOCK)
				WHERE 
					ZXJ_1.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
					ZXJ_1.ZXJ_ORC = ZXJ.ZXJ_ORC AND
					ZXJ_1.ZXJ_REVISA = ( 
											SELECT 
												MIN(ZXJ_A.ZXJ_REVISA) 
											FROM 
												ZXJ040 ZXJ_A WITH(NOLOCK)
											WHERE 
												ZXJ_A.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
												ZXJ_A.ZXJ_ORC = ZXJ.ZXJ_ORC AND 
												ZXJ_A.D_E_L_E_T_ = '' 
										)  AND 
					ZXJ_1.D_E_L_E_T_ = ''
					GROUP BY ZXJ_1.ZXJ_ORC
			) ORCAMENTOS
		WHERE 
			ZXJ.ZXJ_FILIAL = '0404' AND 
			ZXJ.ZXJ_DTINI BETWEEN '20210101' AND '20211231' AND 
			ZXJ.D_E_L_E_T_ = ''
		GROUP BY ORCAMENTOS.ORCAMENTO
		UNION ALL 
		SELECT 
			0 ORCAMENTOS,
			1 PEDIDOS
		FROM 
			ZXJ040 ZXJ WITH(NOLOCK)
				CROSS APPLY( 
					SELECT 
						ZXJ_2.ZXJ_ORC ORCAMENTO
					FROM 
						ZXJ040 ZXJ_2 WITH(NOLOCK)
					WHERE 
						ZXJ_2.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
						ZXJ_2.ZXJ_ORC = ZXJ.ZXJ_ORC AND
						ZXJ_2.ZXJ_REVISA = ( 
												SELECT 
													MAX(ZXJ_A.ZXJ_REVISA) 
												FROM 
													ZXJ040 ZXJ_A WITH(NOLOCK)
												WHERE 
													ZXJ_A.ZXJ_FILIAL = ZXJ.ZXJ_FILIAL AND 
													ZXJ_A.ZXJ_ORC = ZXJ.ZXJ_ORC AND 
													ZXJ_A.D_E_L_E_T_ = '' 
											)  AND 
						ZXJ_2.ZXJ_PEDIDO <> '' AND
						ZXJ_2.D_E_L_E_T_ = ''
						GROUP BY ZXJ_2.ZXJ_ORC
					) PEDIDOS
				WHERE 
					ZXJ.ZXJ_FILIAL = '0404' AND 
					ZXJ.ZXJ_DTINI BETWEEN '20210101' AND '20211231' AND 
					ZXJ.D_E_L_E_T_ = ''
				GROUP BY PEDIDOS.ORCAMENTO
	) TOTAIS
)  TX_CONVERSAO