SELECT
	AY1_CODIGO,
	AY1_SUBCAT,
	AY0_DESC,
	AY1_CATPAI,
	AY1_CATFIL,
	AY0.R_E_C_N_O_ RECNOAY0 
FROM
AY1010 AY1 
INNER JOIN AY0010 AY0 ON AY0.AY0_FILIAL = '' AND AY0.AY0_CODIGO = AY1.AY1_SUBCAT AND AY0.AY0_MSEXP = '' AND AY0.D_E_L_E_T_ = ' ' 
WHERE 
AY1.AY1_FILIAL = '' 
AND AY1.D_E_L_E_T_ = ' ' 
ORDER BY AY0_TIPO 