SELECT 
CAT1.AY0_CODIGO AS NIV1, 
CAT2.AY0_CODIGO AS NIV2,
CAT3.AY0_CODIGO AS NIV3, 
CAT4.AY0_CODIGO AS NIV4, 
CAT5.AY0_CODIGO AS NIV5,
CAT6.AY0_CODIGO AS NIV6
FROM 
( SELECT 
  AY0_CODIGO, 
  AY1_SUBCAT 
  FROM 
  AY0010 AY0
  INNER JOIN AY1010 AY1 ON AY1_CODIGO = AY0_CODIGO AND AY1.D_E_L_E_T_ = ' '
  WHERE
  AY0.D_E_L_E_T_ = ' '
) AS CAT1
LEFT OUTER JOIN ( SELECT 
					AY0_CODIGO, 
					AY1_SUBCAT,
					AY1_CODIGO 
					FROM 
					AY0010 AY0
					INNER JOIN AY1010 AY1 ON AY1_CODIGO = AY0_CODIGO AND AY1.D_E_L_E_T_ = ' '
					WHERE
					AY0.D_E_L_E_T_ = ' '
				) AS CAT2 ON CAT2.AY0_CODIGO = CAT1.AY1_SUBCAT
LEFT OUTER JOIN ( SELECT 
					AY0_CODIGO, 
					AY1_SUBCAT,
					AY1_CODIGO 
					FROM 
					AY0010 AY0
					INNER JOIN AY1010 AY1 ON AY1_CODIGO = AY0_CODIGO AND AY1.D_E_L_E_T_ = ' '
					WHERE
					AY0.D_E_L_E_T_ = ' ' 
				) AS CAT3 ON CAT3.AY0_CODIGO= CAT2.AY1_SUBCAT
LEFT OUTER JOIN ( SELECT 
					AY0_CODIGO, 
					AY1_SUBCAT,
					AY1_CODIGO 
					FROM 
					AY0010 AY0
					INNER JOIN AY1010 AY1 ON AY1_CODIGO = AY0_CODIGO AND AY1.D_E_L_E_T_ = ' '
					WHERE
					AY0.D_E_L_E_T_ = ' '
				) AS CAT4 ON CAT4.AY0_CODIGO= CAT3.AY1_SUBCAT
LEFT OUTER JOIN ( SELECT 
					AY0_CODIGO, 
					AY1_SUBCAT,
					AY1_CODIGO 
					FROM 
					AY0010 AY0 
					INNER JOIN AY1010 AY1 ON AY1_CODIGO = AY0_CODIGO AND AY1.D_E_L_E_T_ = ' '
					WHERE
					AY0.D_E_L_E_T_ = ' '
				) AS CAT5 ON CAT5.AY0_CODIGO= CAT4.AY1_SUBCAT
LEFT OUTER JOIN( SELECT 
					AY0_CODIGO, 
					AY1_SUBCAT,
					AY1_CODIGO 
					FROM 
					AY0010 AY0
					INNER JOIN AY1010 AY1 ON AY1_CODIGO = AY0_CODIGO AND AY1.D_E_L_E_T_ = ' '
					WHERE
					AY0.D_E_L_E_T_ = ' '
				) AS CAT6 ON CAT6.AY0_CODIGO = CAT5.AY1_SUBCAT

		   