SELECT 
	FILIAL,
	PRODUTO,
	DESCRICAO,
	QTDBASE,
	CUSTO,
	CUSTOMO,
	CUSTOTOTAL,
	MARGEM
FROM (
	SELECT
		FILIAL,
		PRODUTO,
		DESCRICAO,
		QTDBASE,
		SUM(CUSTO_MP) CUSTO,
		SUM(CUSTO_MO) CUSTOMO,
		SUM(CUSTO_MP + CUSTO_MO) CUSTOTOTAL,
		SUM(0) MARGEM
	FROM(
		SELECT 
			G2.G2_FILIAL FILIAL,
			ESTRUTURA_SG2.G2_PRODUTO PRODUTO,
			ESTRUTURA_SG2.B1_DESC DESCRICAO,
			ESTRUTURA_SG2.B1_QBP QTDBASE,
			CUSTO_PRODUTO.CUSTO_MP,
			0 CUSTO_MO
		FROM 
			SG2010 G2 (NOLOCK)
			INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = G2.G2_PRODUTO AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
			CROSS APPLY (
				SELECT
					TOP 1
					G2_1.G2_PRODUTO,
					B1.B1_DESC,
					B1.B1_QBP
				FROM 
					SG2010 G2_1 (NOLOCK)
					INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = G2_1.G2_PRODUTO AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
					INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = ''
				WHERE 
					G2_1.G2_FILIAL = G2.G2_FILIAL AND 
					SUBSTRING(G2_1.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(G2.G2_PRODUTO,1,18) +'%' AND 
					G2_1.G2_RECURSO NOT IN('EMBLIT') AND
					G2_1.D_E_L_E_T_ = ''
				ORDER BY G2_1.G2_FILIAL, G2_1.G2_OPERAC DESC 
			) ESTRUTURA_SG2
			CROSS APPLY (
				SELECT	
					CASE WHEN CUSTO_MP.D1_CUSTO > 0 THEN ROUND(ROUND( CUSTO_MP.D1_CUSTO / CUSTO_MP.D1_QUANT, 4 ) * G1.G1_QUANT,4) ELSE 0 END CUSTO_MP
				FROM 
					SG1010 G1 (NOLOCK)
					CROSS APPLY (
						SELECT 
							TOP 1
							D1.D1_FILIAL,
							D1.D1_COD,
							D1.D1_DOC,
							D1.D1_SERIE,
							D1.D1_DTDIGIT,
							SUM(D1.D1_CUSTO) D1_CUSTO,
							SUM(D1.D1_QUANT) D1_QUANT
						FROM 
							SD1010 D1 (NOLOCK)
							INNER JOIN SB1010 B1 (NOLOCK) ON  B1.B1_FILIAL = '' AND B1.B1_COD  = G1.G1_COMP AND	B1.B1_TIPO <> 'MO' AND	B1.D_E_L_E_T_ = ''
						WHERE 
							D1.D1_FILIAL = G1.G1_FILIAL AND 
							D1.D1_COD = B1.B1_COD AND 
							D1.D1_QUANT > 0 AND
							D1.D1_DTDIGIT <= '20240401' AND 
							D1.D_E_L_E_T_ = ''
						GROUP BY D1.D1_FILIAL,D1.D1_COD,D1.D1_DOC,D1.D1_SERIE,D1.D1_DTDIGIT
						ORDER BY D1.D1_DTDIGIT DESC
					)CUSTO_MP
				WHERE 
					G1.G1_FILIAL = G2.G2_FILIAL AND 
					G1.G1_COD = G2.G2_PRODUTO AND 
					G1.D_E_L_E_T_ = '' 
			) CUSTO_PRODUTO
		WHERE 
			G2.G2_FILIAL BETWEEN '      ' AND 'ZZZZZZ' AND 
			G2.G2_PRODUTO BETWEEN '                              ' AND 'ZZZZZZZZZZZZZZZZZZZZ' AND 
			G2.G2_RECURSO NOT IN('EMBLIT') AND
			G2.D_E_L_E_T_ = ''
		UNION ALL 
		SELECT 
			G2.G2_FILIAL FILIAL,
			ESTRUTURA_SG2.G2_PRODUTO PRODUTO,
			ESTRUTURA_SG2.B1_DESC DESCRICAO,
			ESTRUTURA_SG2.B1_QBP  QTDBASE,
			0 CUSTO_MP,
			SUM(ESTRUTURA_SG2.CUSTO_MO) CUSTO_MO
		FROM
			SG2010 G2 (NOLOCK)
			INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = G2.G2_PRODUTO AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
			CROSS APPLY (
				SELECT
					TOP 1
					G2_1.G2_PRODUTO,
					B1.B1_DESC,
					B1.B1_QBP,
					CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END CUSTO_MO
				FROM 
					SG2010 G2_1 (NOLOCK)
					INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = G2_1.G2_PRODUTO AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
					INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = ''
				WHERE 
					G2_1.G2_FILIAL = G2.G2_FILIAL AND 
					SUBSTRING(G2_1.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(G2.G2_PRODUTO,1,18) +'%' AND 
					G2_1.G2_RECURSO NOT IN('EMBLIT') AND
					G2_1.D_E_L_E_T_ = ''
				ORDER BY G2_1.G2_FILIAL, G2_1.G2_OPERAC DESC 
			) ESTRUTURA_SG2
		WHERE 
			G2.G2_FILIAL BETWEEN '      ' AND 'ZZZZZZ' AND 
			G2.G2_PRODUTO BETWEEN '                              ' AND 'ZZZZZZZZZZZZZZZZZZZZ' AND 
			G2.G2_RECURSO NOT IN('EMBLIT') AND
			G2.D_E_L_E_T_ = ''
		GROUP BY G2.G2_FILIAL, ESTRUTURA_SG2.G2_PRODUTO, ESTRUTURA_SG2.B1_DESC, ESTRUTURA_SG2.B1_QBP
	)CALC_CUSTO
	GROUP BY FILIAL,PRODUTO,DESCRICAO,QTDBASE
)MARGEM
ORDER BY FILIAL, PRODUTO


