-- CONSOLIDADO FILIAL
SELECT 
	FILIAL, 
	NOME_FILIAL,
	QUANTIDADE,
	VALOR_BRUTO,
	IMPOSTOS,
	CPV,
	CUSTOMO,
	ROUND(VALOR_BRUTO - IMPOSTOS - CPV - CUSTOMO,2) VENDA_LIQUIDA,
	ROUND( ( (VALOR_BRUTO - IMPOSTOS - CPV - CUSTOMO) / VALOR_BRUTO) * 100 , 2 ) MARGEM
FROM(
	SELECT 
		F2.F2_FILIAL FILIAL, 
		COMP.M0_FILIAL NOME_FILIAL,
		SUM(QUANTIDADE.D2_QUANT) QUANTIDADE,
		SUM(F2.F2_VALBRUT) VALOR_BRUTO,
		SUM(F2.F2_VALICM + F2.F2_VALIPI + F2.F2_VALIMP5 + F2.F2_VALIMP6 ) IMPOSTOS,
		SUM(QUANTIDADE.D2_CUSTO1) CPV,
		SUM(QUANTIDADE.CUSTO_MO) CUSTOMO
	FROM 
		SF2010 F2 
		INNER JOIN SYS_COMPANY COMP (NOLOCK) ON M0_CODIGO = '01' AND M0_CODFIL = F2.F2_FILIAL AND COMP.D_E_L_E_T_ = ''
		CROSS APPLY(
			SELECT 
				D2.D2_QUANT,
				D2.D2_CUSTO1,
				ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) CUSTO_MO
			FROM 
				SD2010 D2 
				OUTER APPLY(
					SELECT 
						SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO,
						SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO
					FROM 
						SG2010 G2 
						INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
						INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = ''
					WHERE 
						G2.G2_FILIAL = D2.D2_FILIAL AND 
						SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
						G2.G2_RECURSO NOT IN('EMBLIT') AND
						G2.D_E_L_E_T_ = ''
					GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18)
				) ROTEIRO
			WHERE 
				D2.D2_FILIAL = F2.F2_FILIAL AND 
				D2.D2_DOC = F2.F2_DOC AND 
				D2.D2_SERIE = F2.F2_SERIE AND 
				D2.D_E_L_E_T_ = ''
		)QUANTIDADE
	WHERE 
		F2.F2_FILIAL BETWEEN '      ' AND 'ZZZZZZ' AND 
		F2.F2_EMISSAO BETWEEN '20230101' AND '20231231' AND 
		F2.F2_TIPO = 'N' AND 
		F2.D_E_L_E_T_ = ''
	GROUP BY F2.F2_FILIAL, COMP.M0_FILIAL
)CONSOLIDADO_FILIAL
ORDER BY FILIAL

-- CONSOLIDADO CLIENTE
SELECT 
	CLIENTE,
	LOJA,
	RAZAO,
	QUANTIDADE,
	VALOR_BRUTO,
	IMPOSTOS,
	CPV,
	CUSTOMO,
	ROUND(VALOR_BRUTO - IMPOSTOS - CPV - CUSTOMO,2) VENDA_LIQUIDA,
	ROUND( ( (VALOR_BRUTO - IMPOSTOS - CPV - CUSTOMO) / VALOR_BRUTO) * 100 , 2 ) MARGEM
FROM(
	SELECT 
		F2.F2_CLIENTE CLIENTE,
		F2.F2_LOJA LOJA,
		A1.A1_NOME RAZAO,
		SUM(QUANTIDADE.D2_QUANT) QUANTIDADE,
		SUM(F2.F2_VALBRUT) VALOR_BRUTO,
		SUM(F2.F2_VALICM + F2.F2_VALIPI + F2.F2_VALIMP5 + F2.F2_VALIMP6 ) IMPOSTOS,
		SUM(QUANTIDADE.D2_CUSTO1) CPV,
		SUM(QUANTIDADE.CUSTO_MO) CUSTOMO
	FROM 
		SF2010 F2 
		INNER JOIN SA1010 A1 (NOLOCK) ON A1.A1_FILIAL = '01' AND A1.A1_COD = F2.F2_CLIENTE AND A1.A1_LOJA = F2.F2_LOJA AND A1.D_E_L_E_T_ = ''
		CROSS APPLY(
			SELECT 
				D2.D2_COD,
				D2.D2_QUANT D2_QUANT,
				D2.D2_CUSTO1 D2_CUSTO1,
				ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) CUSTO_MO
			FROM 
				SD2010 D2 
				OUTER APPLY(
					SELECT 
						SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO,
						SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO
					FROM 
						SG2010 G2 
						INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
						INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = ''
					WHERE 
						G2.G2_FILIAL = D2.D2_FILIAL AND 
						SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
						G2.G2_RECURSO NOT IN('EMBLIT') AND
						G2.D_E_L_E_T_ = ''
					GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18)
				) ROTEIRO
			WHERE 
				D2.D2_FILIAL = F2.F2_FILIAL AND 
				D2.D2_DOC = F2.F2_DOC AND 
				D2.D2_SERIE = F2.F2_SERIE AND 
				D2.D_E_L_E_T_ = ''
		)QUANTIDADE
	WHERE 
		F2.F2_FILIAL BETWEEN '010101' AND '010101' AND 
		F2.F2_EMISSAO BETWEEN '20230101' AND '20231231' AND 
		F2.F2_TIPO = 'N' AND 
		F2.D_E_L_E_T_ = ''
	GROUP BY F2.F2_CLIENTE, F2.F2_LOJA, A1.A1_NOME
)CONSOLIDADO_CLIENTE
ORDER BY CLIENTE,LOJA

-- SINTETICO POR NOTA
SELECT 
	FILIAL,
	DOCUMENTO, 
	SERIE,
	EMISSAO,
	QUANTIDADE,
	VALOR_BRUTO,
	IMPOSTOS,
	CPV,
	CUSTOMO,
	(VALOR_BRUTO - IMPOSTOS - CPV - CUSTOMO) VENDA_LIQUIDA,
	ROUND( ( (VALOR_BRUTO - IMPOSTOS - CPV - CUSTOMO) / VALOR_BRUTO ) * 100, 2)  MARGEM 
FROM (
	SELECT 
		F2.F2_FILIAL FILIAL,
		F2.F2_DOC DOCUMENTO, 
		F2.F2_SERIE SERIE,
		F2.F2_EMISSAO EMISSAO,
		SUM(QUANTIDADE.D2_QUANT) QUANTIDADE,
		F2.F2_VALBRUT VALOR_BRUTO,
		(F2.F2_VALICM + F2.F2_VALIPI + F2.F2_VALIMP5 + F2.F2_VALIMP6 ) IMPOSTOS,
		SUM(QUANTIDADE.D2_CUSTO1) CPV,
		SUM(QUANTIDADE.CUSTO_MO) CUSTOMO
	FROM 
		SF2010 F2 
		CROSS APPLY(
			SELECT 
				D2.D2_QUANT,
				D2.D2_CUSTO1,
				D2.D2_PEDIDO,
				ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) CUSTO_MO
			FROM 
				SD2010 D2 
				OUTER APPLY(
					SELECT 
						SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO,
						SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO
					FROM 
						SG2010 G2 
						INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = ''
						INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = ''
					WHERE 
						G2.G2_FILIAL = D2.D2_FILIAL AND 
						SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
						G2.G2_RECURSO NOT IN('EMBLIT') AND
						G2.D_E_L_E_T_ = ''
					GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18)
				) ROTEIRO
			WHERE 
				D2.D2_FILIAL = F2.F2_FILIAL AND 
				D2.D2_DOC = F2.F2_DOC AND 
				D2.D2_SERIE = F2.F2_SERIE AND 
				D2.D_E_L_E_T_ = ''
		)QUANTIDADE
	WHERE 
		F2.F2_FILIAL = '010101' AND 
		F2.F2_DOC = '000306097' AND 
		F2.D_E_L_E_T_ = ''
	GROUP BY F2.F2_FILIAL, 	F2.F2_DOC, 	F2.F2_SERIE, F2.F2_EMISSAO, F2.F2_VALBRUT , F2.F2_VALICM , F2.F2_VALIPI, F2.F2_VALIMP5 , F2.F2_VALIMP6
)NOTAS

-- SINTETICO PRODUTO 
 SELECT 
    FILIAL, 
	DOCUMENTO, 
	SERIE, 
	EMISSAO, 
	PRODUTO, 
	COALESCE(CICLO,'') CICLO,
	VALOR_BRUTO, 
	IMPOSTOS, 
	CPV, 
	COALESCE(CUSTO_MO, 0) CUSTO_MO, 
	COALESCE(ROUND((VALOR_BRUTO - IMPOSTOS - CPV - CUSTO_MO),4),0) VENDA_LIQUIDA, 
	COALESCE( ROUND( ( (VALOR_BRUTO - IMPOSTOS - CPV - CUSTO_MO) / VALOR_BRUTO ) * 100, 2),0) MARGEM 
 FROM( 
	SELECT 
        D2.D2_FILIAL FILIAL, 
		D2.D2_DOC DOCUMENTO, 
		D2.D2_SERIE SERIE, 
		D2.D2_EMISSAO EMISSAO, 
		D2.D2_COD PRODUTO, 
		COD_CICLO.DA0_XXCICL CICLO,
		SUM(D2.D2_VALBRUT) VALOR_BRUTO, 
		SUM(D2.D2_VALICM + D2.D2_VALIPI + D2.D2_VALIMP5 + D2.D2_VALIMP6) IMPOSTOS, 
		SUM(D2.D2_CUSTO1) CPV, 
		SUM( ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2)) CUSTO_MO 
	FROM 
		SD2010 D2 
		OUTER APPLY( 
			SELECT 
				SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO, 
				SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO 
			FROM 
				SG2010 G2 
				INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = '' 
				INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = '' 
			WHERE 
				G2.G2_FILIAL = D2.D2_FILIAL AND 
				SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
				G2.G2_RECURSO NOT IN('EMBLIT') AND 
				G2.D_E_L_E_T_ = '' 
			GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18) 
		) ROTEIRO 
		OUTER APPLY (
			SELECT 
				DA0_XXCICL
			FROM 
				SC5010 C5 
				LEFT JOIN DA0010 DA0 (NOLOCK) ON DA0.DA0_FILIAL = C5.C5_FILIAL AND DA0.DA0_CODTAB = C5.C5_TABELA AND DA0.D_E_L_E_T_ = ''
			WHERE 
				C5.C5_FILIAL = D2.D2_FILIAL AND 
				C5.C5_NUM = D2.D2_PEDIDO AND 
				C5.D_E_L_E_T_ = ''
		)COD_CICLO
	WHERE 
		D2.D2_CLIENTE = '000050'  AND 
		D2.D2_LOJA = '01' AND
		D2.D_E_L_E_T_ = '' 
	GROUP BY D2.D2_FILIAL,D2.D2_DOC, D2.D2_SERIE, D2.D2_EMISSAO, D2.D2_COD, COD_CICLO.DA0_XXCICL
 )ITEM_NOTA

 -- ANALITICO GRUPO PRODUTO (RECURSOS)
 SELECT 
    FILIAL, 
	DOCUMENTO, 
	SERIE, 
	EMISSAO, 
	GRPPROD,
	VALOR_BRUTO,
	IMPOSTOS,
	CPV,
	CUSTO_MO,
	VENDA_LIQUIDA, 
	MARGEM 
 FROM( 
	SELECT 
		FILIAL, 
		DOCUMENTO, 
		SERIE, 
		EMISSAO, 
		PRODUTO GRPPROD, 
		SUM(VALOR_CALC) VALOR_BRUTO,
		SUM(IMP_CALC) IMPOSTOS,
		SUM(CPV_CALC) CPV,
		SUM(CUSTO_MO_CALC) CUSTO_MO,
		SUM( ROUND(VALOR_CALC - IMP_CALC - CPV_CALC - CUSTO_MO_CALC,2) ) VENDA_LIQUIDA, 
		SUM(CASE WHEN VALOR_CALC > 0 THEN ROUND( ( (VALOR_CALC - IMP_CALC - CPV_CALC - CUSTO_MO_CALC) / VALOR_CALC ) * 100, 2) ELSE 0 END ) MARGEM
	FROM ( 
		-- ACO
		SELECT 
			D2.D2_FILIAL FILIAL, 
			D2.D2_DOC DOCUMENTO, 
			D2.D2_SERIE SERIE, 
			D2.D2_EMISSAO EMISSAO, 
			'AÇO' PRODUTO,
			SUM(ROUND(D2.D2_VALBRUT * (GRUPO_RECURSOS.DA1_XXPACO /100 ),2)) VALOR_CALC, 
			SUM(ROUND((D2.D2_VALICM + D2.D2_VALIPI + D2.D2_VALIMP5 + D2.D2_VALIMP6) * (GRUPO_RECURSOS.DA1_XXPACO /100 ),2)) IMP_CALC, 
			SUM(ROUND(D2.D2_CUSTO1 * (GRUPO_RECURSOS.DA1_XXPACO /100 ),2)) CPV_CALC, 
			SUM(COALESCE(ROUND(ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) * (GRUPO_RECURSOS.DA1_XXPACO /100 ),2),0)) CUSTO_MO_CALC
		FROM 
			SD2010 D2 
			OUTER APPLY( 
				SELECT 
					SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO, 
					SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO 
				FROM 
					SG2010 G2 
					INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = '' 
					INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = '' 
				WHERE 
					G2.G2_FILIAL = D2.D2_FILIAL AND 
					SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
					G2.G2_RECURSO NOT IN('EMBLIT') AND 
					G2.D_E_L_E_T_ = '' 
				GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18) 
			) ROTEIRO 
			OUTER APPLY (
				SELECT 
					DA1.DA1_XXPACO
				FROM 
					SC5010 C5 
					LEFT JOIN DA1010 DA1 (NOLOCK) ON DA1.DA1_FILIAL = C5.C5_FILIAL AND DA1.DA1_CODTAB = C5.C5_TABELA AND DA1.DA1_CODPRO = D2.D2_COD AND DA1.D_E_L_E_T_ = ''
				WHERE 
					C5.C5_FILIAL = D2.D2_FILIAL AND 
					C5.C5_NUM = D2.D2_PEDIDO AND 
					C5.D_E_L_E_T_ = ''
			)GRUPO_RECURSOS
		WHERE 
			D2.D2_FILIAL + D2.D2_DOC + D2.D2_SERIE = '0101010003074033' AND 
			D2.D_E_L_E_T_ = '' 
		GROUP BY D2.D2_FILIAL,D2.D2_DOC, D2.D2_SERIE, D2.D2_EMISSAO, D2.D2_COD
		UNION ALL 
		-- CORTE
		SELECT 
			D2.D2_FILIAL FILIAL, 
			D2.D2_DOC DOCUMENTO, 
			D2.D2_SERIE SERIE, 
			D2.D2_EMISSAO EMISSAO, 
			'CORTE' PRODUTO,
			SUM(ROUND(D2.D2_VALBRUT * (GRUPO_RECURSOS.DA1_XXPCRT /100 ),2)) VALOR_CALC, 
			SUM(ROUND((D2.D2_VALICM + D2.D2_VALIPI + D2.D2_VALIMP5 + D2.D2_VALIMP6) * (GRUPO_RECURSOS.DA1_XXPCRT /100 ),2)) IMP_CALC, 
			SUM(ROUND(D2.D2_CUSTO1 * (GRUPO_RECURSOS.DA1_XXPCRT /100 ),2)) CPV_CALC, 
			SUM(COALESCE(ROUND(ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) * (GRUPO_RECURSOS.DA1_XXPCRT /100 ),2),0)) CUSTO_MO_CALC
		FROM 
			SD2010 D2 
			OUTER APPLY( 
				SELECT 
					SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO, 
					SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO 
				FROM 
					SG2010 G2 
					INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = '' 
					INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = '' 
				WHERE 
					G2.G2_FILIAL = D2.D2_FILIAL AND 
					SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
					G2.G2_RECURSO NOT IN('EMBLIT') AND 
					G2.D_E_L_E_T_ = '' 
				GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18) 
			) ROTEIRO 
			OUTER APPLY (
				SELECT 
					DA1.DA1_XXPCRT
				FROM 
					SC5010 C5 
					LEFT JOIN DA1010 DA1 (NOLOCK) ON DA1.DA1_FILIAL = C5.C5_FILIAL AND DA1.DA1_CODTAB = C5.C5_TABELA AND DA1.DA1_CODPRO = D2.D2_COD AND DA1.D_E_L_E_T_ = ''
				WHERE 
					C5.C5_FILIAL = D2.D2_FILIAL AND 
					C5.C5_NUM = D2.D2_PEDIDO AND 
					C5.D_E_L_E_T_ = ''
			)GRUPO_RECURSOS
		WHERE 
			D2.D2_FILIAL + D2.D2_DOC + D2.D2_SERIE = '0101010003074033' AND 
			D2.D_E_L_E_T_ = '' 
		GROUP BY D2.D2_FILIAL,D2.D2_DOC, D2.D2_SERIE, D2.D2_EMISSAO, D2.D2_COD
		UNION ALL 
		-- VERNIZ
		SELECT 
			D2.D2_FILIAL FILIAL, 
			D2.D2_DOC DOCUMENTO, 
			D2.D2_SERIE SERIE, 
			D2.D2_EMISSAO EMISSAO, 
			'VERNIZ' PRODUTO,
			SUM( CASE WHEN GRUPO_RECURSOS.DA1_XXPVNZ > 0 THEN ROUND(D2.D2_VALBRUT * (GRUPO_RECURSOS.DA1_XXPVNZ /100 ),2) ELSE 0 END) VALOR_CALC, 
			SUM( CASE WHEN GRUPO_RECURSOS.DA1_XXPVNZ > 0 THEN ROUND((D2.D2_VALICM + D2.D2_VALIPI + D2.D2_VALIMP5 + D2.D2_VALIMP6) * (GRUPO_RECURSOS.DA1_XXPVNZ /100 ),2) ELSE 0 END) IMP_CALC,
			SUM( CASE WHEN GRUPO_RECURSOS.DA1_XXPVNZ > 0 THEN ROUND(D2.D2_CUSTO1 * (GRUPO_RECURSOS.DA1_XXPVNZ /100 ),2) ELSE 0 END) CPV_CALC, 
			SUM( CASE WHEN GRUPO_RECURSOS.DA1_XXPVNZ > 0 THEN ROUND(ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) * (GRUPO_RECURSOS.DA1_XXPVNZ /100 ),2) ELSE 0 END) CUSTO_MO_CALC 
		FROM 
			SD2010 D2 
			OUTER APPLY( 
				SELECT 
					SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO, 
					SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO 
				FROM 
					SG2010 G2 
					INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = '' 
					INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = '' 
				WHERE 
					G2.G2_FILIAL = D2.D2_FILIAL AND 
					SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
					G2.G2_RECURSO NOT IN('EMBLIT') AND 
					G2.D_E_L_E_T_ = '' 
				GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18) 
			) ROTEIRO 
			OUTER APPLY (
				SELECT 
					COALESCE(DA1.DA1_XXPVNZ, 0 ) DA1_XXPVNZ
				FROM 
					SC5010 C5 
					LEFT JOIN DA1010 DA1 (NOLOCK) ON DA1.DA1_FILIAL = C5.C5_FILIAL AND DA1.DA1_CODTAB = C5.C5_TABELA AND DA1.DA1_CODPRO = D2.D2_COD AND DA1.D_E_L_E_T_ = ''
				WHERE 
					C5.C5_FILIAL = D2.D2_FILIAL AND 
					C5.C5_NUM = D2.D2_PEDIDO AND 
					C5.D_E_L_E_T_ = ''
			)GRUPO_RECURSOS
		WHERE 
			D2.D2_FILIAL + D2.D2_DOC + D2.D2_SERIE = '0101010003074033' AND  
			D2.D_E_L_E_T_ = '' 
		GROUP BY D2.D2_FILIAL,D2.D2_DOC, D2.D2_SERIE, D2.D2_EMISSAO, D2.D2_COD
		UNION ALL 
		-- LITOGRAFIA
		SELECT 
			D2.D2_FILIAL FILIAL, 
			D2.D2_DOC DOCUMENTO, 
			D2.D2_SERIE SERIE, 
			D2.D2_EMISSAO EMISSAO, 
			'LITOGRAFIA' PRODUTO,
			SUM(CASE WHEN GRUPO_RECURSOS.DA1_XXPLIT > 0 THEN ROUND(D2.D2_VALBRUT * (GRUPO_RECURSOS.DA1_XXPLIT /100 ),2) ELSE 0 END ) VALOR_CALC, 
			SUM(CASE WHEN GRUPO_RECURSOS.DA1_XXPLIT > 0 THEN ROUND((D2.D2_VALICM + D2.D2_VALIPI + D2.D2_VALIMP5 + D2.D2_VALIMP6) * (GRUPO_RECURSOS.DA1_XXPLIT /100 ),2)ELSE 0 END ) IMP_CALC, 
			SUM(CASE WHEN GRUPO_RECURSOS.DA1_XXPLIT > 0 THEN ROUND(D2.D2_CUSTO1 * (GRUPO_RECURSOS.DA1_XXPLIT /100 ),2) ELSE 0 END )  CPV_CALC, 
			SUM(CASE WHEN GRUPO_RECURSOS.DA1_XXPLIT > 0 THEN COALESCE(ROUND(ROUND(ROTEIRO.CUSTO_MO * D2.D2_QUANT,2) * (GRUPO_RECURSOS.DA1_XXPLIT /100 ),2),0) ELSE 0 END ) CUSTO_MO_CALC
		FROM 
			SD2010 D2 
			OUTER APPLY( 
				SELECT 
					SUBSTRING(G2.G2_PRODUTO,1,18) G2_PRODUTO, 
					SUM(CASE WHEN H1.H1_XCSTUNI > 0 THEN ROUND(H1.H1_XCSTUNI * IIF(B1.B1_QBP > 0, B1.B1_QBP, 1) ,4) ELSE 0 END) CUSTO_MO 
				FROM 
					SG2010 G2 
					INNER JOIN SB1010 B1 (NOLOCK) ON B1.B1_FILIAL = '' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA' AND B1.D_E_L_E_T_ = '' 
					INNER JOIN SH1010 H1 (NOLOCK) ON H1.H1_FILIAL = G2.G2_FILIAL AND H1.H1_CODIGO = G2.G2_RECURSO AND H1.D_E_L_E_T_ = '' 
				WHERE 
					G2.G2_FILIAL = D2.D2_FILIAL AND 
					SUBSTRING(G2.G2_PRODUTO,1,18) LIKE '%'+ SUBSTRING(D2.D2_COD,1,18) +'%' AND 
					G2.G2_RECURSO NOT IN('EMBLIT') AND 
					G2.D_E_L_E_T_ = '' 
				GROUP BY SUBSTRING(G2.G2_PRODUTO,1,18) 
			) ROTEIRO 
			OUTER APPLY (
				SELECT 
					DA1.DA1_XXPLIT
				FROM 
					SC5010 C5 
					LEFT JOIN DA1010 DA1 (NOLOCK) ON DA1.DA1_FILIAL = C5.C5_FILIAL AND DA1.DA1_CODTAB = C5.C5_TABELA AND DA1.DA1_CODPRO = D2.D2_COD AND DA1.D_E_L_E_T_ = ''
				WHERE 
					C5.C5_FILIAL = D2.D2_FILIAL AND 
					C5.C5_NUM = D2.D2_PEDIDO AND 
					C5.D_E_L_E_T_ = ''
			)GRUPO_RECURSOS
		WHERE 
			D2.D2_FILIAL + D2.D2_DOC + D2.D2_SERIE = '0101010003074033' AND 
			D2.D_E_L_E_T_ = '' 
		GROUP BY D2.D2_FILIAL,D2.D2_DOC, D2.D2_SERIE, D2.D2_EMISSAO, D2.D2_COD
	)CALCULOS_GRUPOS
	GROUP BY FILIAL, DOCUMENTO, SERIE, EMISSAO, PRODUTO
 )ITEM_NOTA
 


 --SELECT * FROM SF2010 WHERE F2_FILIAL = '010101' AND F2_DOC = '000307403' AND D_E_L_E_T_ = ''