SELECT 
	A.A1_CGC,
	A.A1_COD,
	A.A1_LOJA,
	A.A1_NOME,
    A.A1_END
FROM 
	SA1030 A
WHERE 
	A.A1_CGC IN (
					SELECT 
						B.A1_CGC 
					FROM 
						SA1030 B 
					WHERE 
						D_E_L_E_T_ = ' ' AND 
						B.A1_CGC <> ' ' 
					GROUP BY B.A1_CGC HAVING COUNT(B.A1_CGC) > 1
				) 
	AND D_E_L_E_T_ = ' '
ORDER BY A.A1_CGC

SELECT 
	A.E1_NUM,
	A.E1_PARCELA,
	A.E1_CLIENTE,
	A.E1_LOJA
FROM 
	SE1030 A
WHERE 
	A.E1_NUM IN (
					SELECT 
						B.E1_NUM 
					FROM 
						SE1030 B 
					WHERE 
						D_E_L_E_T_ = ' ' AND 
						B.E1_NUM <> ' ' 
					GROUP BY B.E1_NUM HAVING COUNT(B.E1_NUM) > 1
				) 
	AND D_E_L_E_T_ = ' '
ORDER BY A.E1_NUM

SELECT 
  COUNT(E1_NUM) TOTAL 
FROM 
  SE1030 
WHERE 
  E1_CLIENTE = '202' AND 
  E1_PREFIXO = 'CAR' AND
  E1_LOJA = '01' AND
  D_E_L_E_T_ = ' '


SELECT 
	WS0_CODINO,
	WS0_DESCRI,
	WS0_STATUS,
	COUNT(WS0_STATUS) STATUS
FROM	
	WS0030
WHERE
	WS0_INTERF = '003' AND
	WS0_DATA BETWEEN '20150728' AND '20150728' AND
	D_E_L_E_T_ = ' '
GROUP BY WS0_CODINO,WS0_DESCRI,WS0_STATUS
ORDER BY WS0_CODINO,WS0_DESCRI,WS0_STATUS

SELECT 
	A.WS0_CODINO,
	A.WS0_DESCRI,
	A.WS0_STATUS,
	COUNT(A.WS0_STATUS) STATUS
FROM 
	WS0030 A
WHERE 
	A.WS0_CODINO IN (
					SELECT 
						B.WS0_CODINO
					FROM 
						WS0030 B 
					WHERE 
						B.WS0_INTERF = '003' AND
						B.WS0_DATA BETWEEN '20150730' AND '20150730' AND
						B.D_E_L_E_T_ = ' ' AND 
						B.WS0_CODINO <> ' ' 
					GROUP BY B.WS0_CODINO HAVING COUNT(B.WS0_CODINO) > 1
				) 
	A.WS0_INTERF = '003' AND
	A.WS0_DATA BETWEEN '20150730' AND '20150730' AND				
	AND A.D_E_L_E_T_ = ' '
GROUP BY A.WS0_CODINO,A.WS0_DESCRI,A.WS0_STATUS
ORDER BY A.WS0_CODINO,A.WS0_DESCRI,A.WS0_STATUS