 SELECT 
	COALESCE(NOTA,'') NOTA,
	COALESCE(SERIE,'') SERIE,
	COALESCE(EMISSAO,'') EMISSAO,
	COALESCE(VENDEDOR,'') CODUSER, 
	SUM(VLR_VENDA) TOTVLIQ 
 FROM ( 
		SELECT 
			NOTA,
			SERIE,
			EMISSAO,
			VENDEDOR, 
			(FATOR * VLR_TOTAL) VLR_VENDA 
		FROM ( 
				SELECT 
					CASE WHEN FT_NATOPER IN ('012') THEN D1.D1_DOC ELSE D2.D2_DOC END NOTA,
					CASE WHEN FT_NATOPER IN ('012') THEN D1.D1_SERIE ELSE D2.D2_SERIE END SERIE,
					CASE WHEN FT_NATOPER IN ('012') THEN D1.D1_DTDIGIT ELSE D2.D2_EMISSAO END EMISSAO,
					A3.A3_COD VENDEDOR, 
					FT_TOTAL VLR_TOTAL, 
					CASE	WHEN FT_NATOPER IN ('008','041','043')      THEN 1 
							WHEN FT_NATOPER IN ('012')		THEN -1 
					END FATOR 
				FROM 
					SFT040 FT WITH(NOLOCK) 
					LEFT JOIN SF2040 F2 WITH(NOLOCK) ON F2.F2_FILIAL = FT.FT_FILIAL AND F2.F2_DOC + F2.F2_SERIE = CASE WHEN FT_NFORI = '' THEN FT.FT_NFISCAL + FT.FT_SERIE ELSE FT.FT_NFORI + FT.FT_SERORI END AND F2.F2_VEND1 IN('000010','000510') AND F2.D_E_L_E_T_ = '' 
					LEFT JOIN SD1040 D1 WITH(NOLOCK) ON D1.D1_FILIAL = FT.FT_FILIAL AND D1.D1_DOC = FT.FT_NFISCAL AND D1.D1_SERIE = FT.FT_SERIE AND D1.D1_ITEM = FT.FT_ITEM AND D1.D1_COD = FT.FT_PRODUTO AND FT_NFORI <> '' AND D1.D_E_L_E_T_ = '' 
					LEFT JOIN SD2040 D2 WITH(NOLOCK) ON D2.D2_FILIAL = FT.FT_FILIAL AND D2.D2_DOC = FT.FT_NFISCAL AND D2.D2_SERIE = FT.FT_SERIE AND D2.D2_ITEM = FT.FT_ITEM AND D2.D2_COD = FT.FT_PRODUTO AND FT.FT_NFORI = '' AND FT.FT_ITEMORI = '' AND D2.D_E_L_E_T_ = '' 
					LEFT JOIN SA3040 A3 WITH(NOLOCK) ON A3.A3_FILIAL = '' AND A3.A3_COD = F2.F2_VEND1 AND A3.A3_COD NOT IN('000033','000333') AND A3.A3_TIPO = 'I' AND A3.A3_MSBLQL <> '1' AND A3.D_E_L_E_T_ = '' 
					LEFT JOIN SA1040 A1 WITH(NOLOCK) ON A1.A1_FILIAL = '' AND A1.A1_COD = F2.F2_CLIENTE AND A1.A1_LOJA  = F2.F2_LOJA AND A1.D_E_L_E_T_ = '' 
				WHERE 
					FT_ENTRADA BETWEEN '20210531' AND '20210629' AND 
					FT.FT_DTCANC = '' AND 
					FT.FT_NATOPER IN ('008','012','041','043')	 AND 
					FT.D_E_L_E_T_ = '' 
		) VENDAS 
 ) COMISSAO 
 WHERE 
	VENDEDOR <> '' 
 GROUP BY NOTA,SERIE,EMISSAO,VENDEDOR 


 --SELECT * FROM SZ4040