SELECT 
	C7.C7_NUM PEDIDO,
	convert(varchar,convert(date,C7.C7_EMISSAO,113),121) DT_EMISSAO,
	COALESCE(convert(varchar,convert(date,D1.D1_DTDIGIT,113),121),'') DT_ENTREGA,
	COALESCE(APROVADORES.APROVADORES,'') APROVADORES ,
	TOTAL_PEDIDO.TOTAL
FROM
	SC7040 C7 (NOLOCK)
	LEFT JOIN SD1040 D1 (NOLOCK) ON D1.D1_FILIAL = C7.C7_FILIAL AND D1.D1_TIPO = 'N' AND D1.D1_PEDIDO = C7.C7_NUM AND D1.D1_COD = C7.C7_PRODUTO AND D1.D1_ITEMPC = C7.C7_ITEM AND D1.D_E_L_E_T_ = '' 
	CROSS APPLY(
		SELECT 
			SUM(SC7.C7_TOTAL + SC7.C7_DESPESA) TOTAL
		FROM 
			SC7040 SC7 (NOLOCK) 
		WHERE 
			SC7.C7_FILIAL = C7.C7_FILIAL AND 
			SC7.C7_NUM = C7.C7_NUM AND 
			SC7.D_E_L_E_T_ = ''
		GROUP BY SC7.C7_NUM 
	)TOTAL_PEDIDO
	OUTER APPLY(
				SELECT 
					COALESCE(
							CONVERT( VARCHAR(1080),
							( SELECT 
								RTRIM(CR.CR_LIBAPRO) + ' - ' + RTRIM(AK.AK_NOME) + ' - ' + convert(varchar,convert(date,CR.CR_DATALIB,113),121) + ' / '  
							FROM 
								SCR040 CR (NOLOCK) 
								LEFT JOIN SAK040 AK (NOLOCK) ON AK.AK_FILIAL = ' ' AND AK.AK_COD = CR.CR_LIBAPRO AND AK.D_E_L_E_T_ = ''
							WHERE 
								CR.CR_FILIAL = C7.C7_FILIAL AND 
								CR.CR_NUM = C7.C7_NUM AND 
								CR.CR_STATUS = '03' AND 
								CR.CR_TIPO = 'PC' AND
								CR.D_E_L_E_T_ = ''
							FOR XML PATH('') )), '') APROVADORES
				FROM 
					SCR040 CR (NOLOCK) 
				WHERE
					CR.CR_FILIAL = C7.C7_FILIAL AND 
					CR.CR_NUM = C7.C7_NUM AND 
					CR.CR_STATUS = '03' AND 
					CR.CR_TIPO = 'PC' AND
					CR.D_E_L_E_T_ = ''
				GROUP BY CR.CR_STATUS
	)APROVADORES
WHERE 
	C7.C7_FILIAL BETWEEN '0404' AND '0404' AND 
	C7.C7_EMISSAO BETWEEN '20210101' AND '20220830' AND 
	C7.C7_PO_EIC <> '' AND
	C7.D_E_L_E_T_ = '' 
GROUP BY C7.C7_NUM ,C7.C7_EMISSAO,COALESCE(convert(varchar,convert(date,D1.D1_DTDIGIT,113),121),''),APROVADORES.APROVADORES,TOTAL_PEDIDO.TOTAL
ORDER BY C7_EMISSAO