SELECT 
 E1.*
FROM 
	SE1040 E1 
WHERE 
	NOT EXISTS(
		SELECT 
			TOP 1
			XTP.*
		FROM 
			XTP040 XTP 
		WHERE
			XTP.XTP_FILIAL = E1.E1_FILIAL AND 
			XTP.XTP_IDPAY = E1.E1_DOCTEF AND 
			ISNULL(NULLIF(XTP.XTP_PARC, ''), '01') = ISNULL(NULLIF(E1.E1_PARCELA, ''), '01') AND
			XTP.D_E_L_E_T_ = ''
	)
	AND E1_TIPO = 'PGM' 
	AND E1_BAIXA = '' 
	AND E1_SALDO > 0 
	AND E1_VENCREA > '20260101' 
	AND E1_VENCREA < '20260509' 
	AND E1.D_E_L_E_T_ = ''
--GROUP BY E1_DOCTEF