USE [GATEWAY]
GO

/****** Object:  View [dbo].[cpq_vendedores]    Script Date: 10/02/2023 15:34:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER view [dbo].[cpq_vendedores] as 

SELECT
	SA3.R_E_C_N_O_ AS vendedorId
	,RTRIM(SA3.A3_FILIAL) AS codigoFilial
	,RTRIM(SA3.A3_COD) AS codigoErp
	,RTRIM(SA3.A3_NOME) AS razaoSocial
	,RTRIM(SA3.A3_NREDUZ) AS nomeFantasia
	,RTRIM(SA3.A3_END) AS endereco
	,RTRIM(SA3.A3_BAIRRO) AS bairro
	,RTRIM(SA3.A3_EST) AS uf
	,RTRIM(SA3.A3_MUN) AS municipio
	,RTRIM(SA3.A3_CEP) AS cep
	,CASE WHEN SA3.A3_TIPO = 'E' THEN 'Externo'	ELSE 'Interno' END AS tipoVendedor
	,CASE WHEN LEN(RTRIM(SA3.A3_CGC)) > 11 THEN RTRIM(SA3.A3_CGC) ELSE '' END AS cnpj 
	,CASE WHEN LEN(RTRIM(SA3.A3_CGC)) < 11 THEN RTRIM(SA3.A3_CGC) ELSE '' END AS cpf 
	,RTRIM(SA3.A3_DDD) AS ddd
	,RTRIM(SA3.A3_TEL) AS telefone
	,RTRIM(SA3.A3_EMAIL) AS email
	,RTRIM(SA3.A3_INSCR) AS inscricaoEstadual
	,RTRIM(SA3.A3_INSCRM) AS inscricaoMunicipal
	,RTRIM(SA3.A3_CODUSR) AS codigoUsr
	,RTRIM(SA3.A3_SUPER) AS supervisor
	,COALESCE(RTRIM(SA3_SUP.A3_NOME),'') AS nomeSupervisor
	,RTRIM(SA3.A3_GEREN) AS gerente
	,COALESCE(RTRIM(SA3_GER.A3_NOME),'') AS nomeGerente
	,RTRIM(SA3.A3_XDIRETO) AS diretor
	,COALESCE(RTRIM(SA3_DIR.A3_NOME),'') AS nomeDiretor
	,CASE WHEN SA3.A3_MSBLQL = '1' THEN 'S' ELSE 'N' END AS bloqueado
FROM 
	[LABOR-1233]..SA3040 SA3 (NOLOCK)
	LEFT JOIN [LABOR-1233]..SA3040 SA3_SUP (NOLOCK)
	ON SA3_SUP.A3_COD = SA3.A3_SUPER 
	AND SA3_SUP.D_E_L_E_T_ = ''
	LEFT JOIN [LABOR-1233]..SA3040 SA3_GER (NOLOCK)
	ON SA3_GER.A3_COD = SA3.A3_GEREN 
	AND SA3_GER.D_E_L_E_T_ = ''
	LEFT JOIN [LABOR-1233]..SA3040 SA3_DIR (NOLOCK)
	ON SA3_DIR.A3_COD = SA3.A3_XDIRETO 
	AND SA3_DIR.D_E_L_E_T_ = ''
WHERE
	SA3.A3_MSEXP = '' AND
	SA3.A3_XLINPRO IN('01','') AND 
	SA3.D_E_L_E_T_ = ' '
GROUP BY SA3.R_E_C_N_O_ 
	,SA3.A3_FILIAL
	,SA3.A3_COD
	,SA3.A3_NOME
	,SA3.A3_NREDUZ
	,SA3.A3_END
	,SA3.A3_BAIRRO
	,SA3.A3_EST
	,SA3.A3_MUN
	,SA3.A3_CEP
	,SA3.A3_TIPO
	,SA3.A3_CGC
	,SA3.A3_DDD
	,SA3.A3_TEL
	,SA3.A3_EMAIL
	,SA3.A3_INSCR
	,SA3.A3_INSCRM
	,SA3.A3_CODUSR
	,SA3.A3_SUPER
	,SA3_SUP.A3_NOME
	,SA3.A3_GEREN
	,SA3_GER.A3_NOME
	,SA3.A3_XDIRETO
	,SA3_DIR.A3_NOME
	,SA3.A3_MSBLQL

GO