USE [GATEWAY]
GO

/****** Object:  View [dbo].[cpq_produtos]    Script Date: 04/04/2023 18:19:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER view [dbo].[cpq_produtos] as 
SELECT
	cast(SB1.R_E_C_N_O_ as int) AS productId
	,RTRIM(SB1.B1_FILIAL) AS codigoFilial
	,RTRIM(SB1.B1_COD) AS codigoErp
	,RTRIM(SB1.B1_DESC) AS descricao
	,COALESCE(dbo.fncRemove_Caracteres_Ocultos(CAST(CAST(CASE WHEN WS5.WS5_DESCRP <> '' THEN RTRIM(WS5.WS5_DESCRP) ELSE RTRIM(SB5.B5_XDESCRI) END AS BINARY(1024)) AS VARCHAR(1024) )),'') AS descricaoLonga
	,COALESCE(dbo.fncRemove_Caracteres_Ocultos(CAST(CAST(CASE WHEN WS5.WS5_CARACT <> '' THEN RTRIM(WS5.WS5_CARACT) ELSE RTRIM(SB5.B5_XCARACT) END AS BINARY(1024)) AS VARCHAR(1024) )),'') AS caracteristica
	,COALESCE(dbo.fncRemove_Caracteres_Ocultos(CAST(CAST(CASE WHEN WS5.WS5_DERESU <> '' THEN RTRIM(WS5.WS5_DERESU) ELSE RTRIM(SB5.B5_XDERESU) END AS BINARY(1024)) AS VARCHAR(1024) )),'') AS descricaoResumida
	,RTRIM(SB1.B1_UM) AS unidadeMedida
	,RTRIM(SB1.B1_TIPO) AS tipo
	,RTRIM(SB1.B1_LOCPAD) AS armazem
	,RTRIM(SB1.B1_GRUPO) AS grupo
	,RTRIM(COALESCE(BM_DESC,'')) AS descricaoGrupo
	,RTRIM(SB1.B1_PESO) AS pesoLiquido
	,RTRIM(SB1.B1_PESBRU) AS pesoBruto
	,RTRIM(SB1.B1_POSIPI) AS ncm
	,SB1.B1_IPI AS aliqIpi
	,CASE WHEN SB1.B1_MSBLQL = '1' THEN 'S' ELSE 'N' END AS bloqueado
	,SB1.B1_XHIBRID hibrido
	,COALESCE(B5_ALTURA,0) AS alturaProd
	,COALESCE(B5_LARG,0) AS larguraProd
	,COALESCE(B5_COMPR,0) AS comprimentoProd
	,COALESCE(B5_ALTURLC,0) AS alturaCaixa
	,COALESCE(B5_LARGLC,0) AS larguraCaixa
	,COALESCE(B5_COMPRLC,0) AS comprimentoCaixa
	,COALESCE(B5_QE2,0) AS qtdCaixa
	,COALESCE(RTRIM(SB1.B1_CATE),'') familia
	,COALESCE(RTRIM(ZN.ZN_NOME),'') descricaoFamilia
	,COALESCE(RTRIM(SB1.B1_XSUBCAT),'') subCategoria
	,COALESCE(RTRIM(SB1.B1_XMARCA),'') marca
	,COALESCE(RTRIM(SB1.B1_XTAM),'') tamanho
	,COALESCE(RTRIM(SB1.B1_XLICA),'') licensaAnvisa
	,convert(varchar,convert(date,SB1.B1_DATAINC,113),121) AS dataCadastro
	,COALESCE(PRODUTO_CASADO.produtoId,'') produtoCasado
	,COALESCE(PRODUTO_CASADO.B1_DESC,'') descricaoProdutoCasado
	,COALESCE(RTRIM(ACU.ACU_DESC),'') linhaProduto 
FROM [LABOR-PROD12]..SB1040 SB1 (NOLOCK)
LEFT JOIN [LABOR-PROD12]..SB5040 SB5 (NOLOCK)
	ON SB5.B5_FILIAL = ' '
	AND SB5.B5_COD = SB1.B1_COD
	AND SB5.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-PROD12]..WS6040 WS6 (NOLOCK)
	ON WS6.WS6_FILIAL = ' ' 
	AND WS6.WS6_CODSKU = SB1.B1_COD 
	AND WS6.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-PROD12]..WS5040 WS5 (NOLOCK)
	ON WS5.WS5_FILIAL = ' ' 
	AND WS5.WS5_CODPRD = WS6.WS6_CODPRD 
	AND WS5.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-PROD12]..SBM040 SBM (NOLOCK)
	ON SBM.BM_FILIAL = ' '
	AND SBM.BM_GRUPO = SB1.B1_GRUPO
	AND SBM.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-PROD12]..SZN040 ZN (NOLOCK)
	ON ZN.ZN_FILIAL = ' ' 
	AND ZN.ZN_COD = SB1.B1_CATE
	AND ZN.D_E_L_E_T_ = ''
LEFT JOIN [LABOR-PROD12]..ACU040 ACU (NOLOCK) 
	ON ACU.ACU_FILIAL = ' '
	AND ACU.ACU_COD = SB1.B1_CATEG 
	AND ACU.D_E_L_E_T_ = ''
OUTER APPLY(
	SELECT
		B1.R_E_C_N_O_ produtoId,
		B1.B1_DESC
	FROM 
		[LABOR-PROD12]..SB1040 B1 (NOLOCK)
	WHERE 
		B1.B1_FILIAL = SB1.B1_FILIAL AND 
		B1.B1_COD = SB1.B1_XCASADO AND 
		B1.D_E_L_E_T_ = ''
)PRODUTO_CASADO
WHERE
	SB1.B1_MSEXP = '' AND
	SB1.B1_TIPO = 'ME' AND
	SB1.B1_GRUPO NOT IN('7000') AND
	SB1.D_E_L_E_T_ = ' '
GO


