SELECT TOP 1000 [IDOrcamentoPrinc]
      ,[Ativo]
      ,[IDStatusWorkflow]
      ,[DtInclusao]
      ,[DtAlteracao]
      ,[IDCliente]
      ,[IDVendedor]
      ,[IDUsuario]
      ,[CodigoPedido]
      ,[DtInicial]
      ,[Tracker]
      ,[OrigemProtheus]
      ,[IDOrcamentoERP]
      ,[LinkPagamento]
      ,[IDOrcamentoNota]
      ,[NumVersao]
      ,[DevolucaoEstoque]
      ,[PedidoCompra]
      ,[Licitacao]
      ,[DataFaturamento]
      ,[IDPlataforma]
      ,[Backorder]
      ,[Eventos]
      ,[FilaIntegracao]
      ,[DtEnvioFilaIntegracao]
  FROM [dbo].[OrcamentoPrinc] where [IDStatusWorkflow] in ('13','14','41') and DtInclusao >= '2023-06-26 00:00:00.000'