USE [GATEWAY]
GO

/****** Object:  View [dbo].[cpq_produtos]    Script Date: 10/02/2023 13:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER view [dbo].[cpq_produtos] as 
SELECT
	SB1.R_E_C_N_O_ AS productId
	,RTRIM(B1_FILIAL) AS codigoFilial
	,RTRIM(B1_COD) AS codigoErp
	,RTRIM(B1_DESC) AS descricao
	,COALESCE(dbo.fncRemove_Caracteres_Ocultos(CAST(CAST(CASE WHEN WS5.WS5_DESCRP <> '' THEN RTRIM(WS5.WS5_DESCRP) ELSE RTRIM(SB5.B5_XDESCRI) END AS BINARY(1024)) AS VARCHAR(1024) )),'') AS descricaoLonga
	,COALESCE(dbo.fncRemove_Caracteres_Ocultos(CAST(CAST(CASE WHEN WS5.WS5_CARACT <> '' THEN RTRIM(WS5.WS5_CARACT) ELSE RTRIM(SB5.B5_XCARACT) END AS BINARY(1024)) AS VARCHAR(1024) )),'') AS caracteristica
	,COALESCE(dbo.fncRemove_Caracteres_Ocultos(CAST(CAST(CASE WHEN WS5.WS5_DERESU <> '' THEN RTRIM(WS5.WS5_DERESU) ELSE RTRIM(SB5.B5_XDERESU) END AS BINARY(1024)) AS VARCHAR(1024) )),'') AS descricaoResumida
	,RTRIM(B1_UM) AS unidadeMedida
	,RTRIM(B1_TIPO) AS tipo
	,RTRIM(B1_LOCPAD) AS armazem
	,RTRIM(B1_GRUPO) AS grupo
	,RTRIM(COALESCE(BM_DESC,'')) AS descricaoGrupo
	,RTRIM(B1_PESO) AS pesoLiquido
	,RTRIM(B1_PESBRU) AS pesoBruto
	,RTRIM(B1_POSIPI) AS ncm
	,B1_IPI AS aliqIpi
	,CASE WHEN B1_MSBLQL = '1' THEN 'S' ELSE 'N' END AS bloqueado
	,B1_XHIBRID hibrido
	,COALESCE(B5_ALTURA,0) AS alturaProd
	,COALESCE(B5_LARG,0) AS larguraProd
	,COALESCE(B5_COMPR,0) AS comprimentoProd
	,COALESCE(B5_ALTURLC,0) AS alturaCaixa
	,COALESCE(B5_LARGLC,0) AS larguraCaixa
	,COALESCE(B5_COMPRLC,0) AS comprimentoCaixa
	,COALESCE(B5_QE2,0) AS qtdCaixa
	,RTRIM(B1_CATE) familia
	,RTRIM(ZN.ZN_NOME) descricaoFamilia
	,RTRIM(B1_XSUBCAT) subCategoria
	,RTRIM(B1_XMARCA) marca
	,RTRIM(B1_XTAM) tamanho
	,convert(varchar,convert(date,B1_DATAINC,113),121) AS dataCadastro
FROM [LABOR-1233]..SB1040 SB1 (NOLOCK)
LEFT JOIN [LABOR-1233]..SB5040 SB5 (NOLOCK)
	ON SB5.B5_FILIAL = ' '
	AND SB5.B5_COD = SB1.B1_COD
	AND SB5.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-1233]..WS6040 WS6 (NOLOCK)
	ON WS6.WS6_FILIAL = ' ' 
	AND WS6.WS6_CODSKU = SB1.B1_COD 
	AND WS6.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-1233]..WS5040 WS5 (NOLOCK)
	ON WS5.WS5_FILIAL = ' ' 
	AND WS5.WS5_CODPRD = WS6.WS6_CODPRD 
	AND WS5.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-1233]..SBM040 SBM (NOLOCK)
	ON SBM.BM_FILIAL = ' '
	AND SBM.BM_GRUPO = SB1.B1_GRUPO
	AND SBM.D_E_L_E_T_ = ' '
LEFT JOIN [LABOR-1233]..SZN040 ZN (NOLOCK)
	ON ZN.ZN_FILIAL = ' ' 
	AND ZN.ZN_COD = SB1.B1_CATE
	AND ZN.D_E_L_E_T_ = ''
WHERE
	SB1.B1_MSEXP = '' AND
	SB1.B1_TIPO = 'ME' AND
	SB1.D_E_L_E_T_ = ' '
GO


