USE [LABOR-BI]
GO

/****** Object:  Table [dbo].[TMS_NOTAS]    Script Date: 16/11/2023 11:10:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMS_NOTAS](
	[recno] [int] IDENTITY(1,1) NOT NULL,
	[identificador] [char](10) NULL,
	[remetente_cnpj_cpf] [char](14) NULL,
	[destinatario_cnpj_cpf] [char](14) NULL,
	[pagador_cnpj_cpf] [char](14) NULL,
	[transportador_cnpj_cpf] [char](14) NULL,
	[redespacho_pornotafiscal] [char](1) NULL,
	[redespacho_cif_fob] [char](1) NULL,
	[redespacho_cnpj_cpf] [char](14) NULL,
	[redespacho_razaosocial] [varchar](100) NULL,
	[redespacho_fantasia] [varchar](100) NULL,
	[redespacho_inscricao_estadual] [char](18) NULL,
	[redespacho_contato] [varchar](60) NULL,
	[redespacho_fone] [char](15) NULL,
	[redespacho_cep] [char](8) NULL,
	[redespacho_endereco] [varchar](100) NULL,
	[redespacho_numero] [varchar](10) NULL,
	[redespacho_complemento] [varchar](100) NULL,
	[redespacho_bairro] [varchar](60) NULL,
	[redespacho_ibge] [char](7) NULL,
	[redespacho_uf] [char](2) NULL,
	[redespacho_cidade] [varchar](60) NULL,
	[redespacho_regiao] [varchar](15) NULL,
	[nota_numero] [char](9) NULL,
	[nota_serie] [char](3) NULL,
	[nota_chave] [char](44) NULL,
	[nota_data_emissao] [date] NULL,
	[nota_peso] [real] NULL,
	[nota_peso_calculado] [real] NULL,
	[nota_m3] [real] NULL,
	[nota_volumes] [int] NULL,
	[nota_km] [int] NULL,
	[nota_valor] [real] NULL,
	[nota_pedido] [char](10) NULL,
	[nota_cfop] [char](4) NULL,
	[nota_cif_fob] [char](1) NULL,
	[nota_calculo] [char](1) NULL,
	[nota_operacao_fiscal] [varchar](50) NULL,
	[nota_centro_custo] [varchar](15) NULL,
	[nota_ocorrencia_quantidade] [int] NULL,
	[trecho_trecho] [varchar](30) NULL,
	[trecho_tabela] [char](1) NULL,
	[trecho_conhecimento] [varchar](30) NULL,
	[trecho_embarque] [date] NULL,
	[trecho_embarque_hora] [char](5) NULL,
	[trecho_previsao] [date] NULL,
	[trecho_previsao_hora] [char](5) NULL,
	[trecho_entrega] [date] NULL,
	[origem_cep] [char](8) NULL,
	[origem_endereco] [varchar](100) NULL,
	[origem_numero] [char](10) NULL,
	[origem_complemento] [varchar](100) NULL,
	[origem_bairro] [varchar](60) NULL,
	[origem_ibge] [char](7) NULL,
	[origem_uf] [char](2) NULL,
	[origem_cidade] [varchar](60) NULL,
	[origem_regiao] [varchar](15) NULL,
	[destino_cep] [char](8) NULL,
	[destino_endereco] [varchar](100) NULL,
	[destino_numero] [char](10) NULL,
	[destino_complemento] [varchar](100) NULL,
	[destino_bairro] [varchar](60) NULL,
	[destino_ibge] [char](7) NULL,
	[destino_uf] [char](2) NULL,
	[destino_cidade] [varchar](60) NULL,
	[destino_regiao] [varchar](15) NULL,
	[romaneio_numero] [char](10) NULL,
	[romaneio_saida_data] [date] NULL,
	[romaneio_saida_hora] [char](5) NULL,
	[romaneio_cancelamento] [char](1) NULL,
	[romaneio_tipo] [char](1) NULL,
	[pre_cte_cfop] [char](4) NULL,
	[pre_cte_valor_prestacao] [real] NULL,
	[pre_cte_total_frete] [real] NULL,
	[pre_cte_conciliacao_valor] [real] NULL,
	[pre_cte_imposto_tipo] [varchar](10) NULL,
	[pre_cte_imposto_base] [real] NULL,
	[pre_cte_imposto_aliquota] [real] NULL,
	[pre_cte_imposto_valor] [real] NULL,
	[pre_cte_imposto_desconto] [real] NULL,
	[cte_cfop] [char](4) NULL,
	[cte_valor_prestacao] [real] NULL,
	[cte_total_frete] [real] NULL,
	[cte_conciliacao_valor] [real] NULL,
	[cte_imposto_tipo] [varchar](10) NULL,
	[cte_imposto_base] [real] NULL,
	[cte_imposto_aliquota] [real] NULL,
	[cte_imposto_valor] [real] NULL,
	[cte_imposto_desconto] [real] NULL
) ON [PRIMARY]
GO


