CREATE TABLE TMS_PRE_CTE
(
	recno INT IDENTITY,
	identificador char(10),
	remetente_cnpj_cpf char(14),
	destinatario_cnpj_cpf char(14),
	pagador_cnpj_cpf char(14),
	transportador_cnpj_cpf char(14),
	romaneio_numero char(10),
	romaneio_tipo char(1),
	romaneio_motorista_nome varchar(100),
	romaneio_motorista_rg_cpf char(14),
	romaneio_motorista_celular char(15),
	romaneio_placa_tracao char(8),
	romaneio_placa_tracao_2 char(8),
	romaneio_placa_carreta char(8),
	romaneio_placa_carreta_2 char(8),
	romaneio_placa_carreta_3 char(8),
	documento_numero char(9),
	documento_tipo varchar(30),
	documento_saida date,
	documento_saida_hora char(5),
	documento_previsao date,
	documento_previsao_hora char(5),
	documento_total_quantidade_nf int,
	documento_total_peso float(12),
	documento_total_peso_calculado float(12),
	documento_total_m3 float(8),
	documento_total_volumes int,
	documento_total_km int,
	documento_total_valor float(14),
	coleta_numero char(10),	
	coleta_pre_coleta char(10),	
	origem_ibge char(7),
	origem_uf char(2),
	origem_cidade varchar(60),
	origem_regiao varchar(15),
	destino_ibge char(7),
	destino_uf char(2),
	destino_cidade varchar(60),
	destino_regiao varchar(15),
	prestacao_cfop char(4),
	prestacao_valor_prestacao float(14),
	prestacao_total_frete float(14),
	prestacao_conciliacao_valor float(14),
	prestacao_imposto_tipo varchar(10),
	prestacao_imposto_base float(14),
	prestacao_imposto_aliquota float(5),
	prestacao_imposto_valor float(14),
	prestacao_imposto_desconto float(14)

)