SELECT 
	PEDIDO, 
	RECNOSC5, 
	TOTAL_ITPED, 
	TOTAL_ITLIB, 
	TOTAL_QTDPED, 
	TOTAL_QTDLIB 
 FROM 
 ( 
	SELECT 
		C5.C5_NUM PEDIDO, 
		C5.R_E_C_N_O_ RECNOSC5, 
		ITENS.ITEM TOTAL_ITPED, 
		ITENS.QTD TOTAL_ITLIB, 
		LIBERADO.ITEM TOTAL_QTDPED, 
		LIBERADO.QTD TOTAL_QTDLIB 
	FROM 
		SC5040 C5 
		CROSS APPLY( 
					SELECT 
						COUNT(C6.C6_ITEM) ITEM, 
						COUNT(C6.C6_QTDVEN) QTD 
					FROM 
						SC6040 C6 
					WHERE 
						C6.C6_FILIAL = C5.C5_FILIAL AND  
						C6.C6_NUM = C5.C5_NUM AND 
						C6.D_E_L_E_T_ = '' 
					GROUP BY C6.C6_FILIAL,C6.C6_NUM 
		)ITENS 
		CROSS APPLY( 
					SELECT 
						COUNT(C9.C9_ITEM) ITEM, 
						COUNT(C9.C9_QTDLIB) QTD 
					FROM  
						SC9040 C9 
					WHERE 
						C9.C9_FILIAL = C5.C5_FILIAL AND  
						C9.C9_PEDIDO = C5.C5_NUM AND 
						C9.C9_BLCRED = '' AND 
						C9.C9_BLEST = '02' AND 
						C9.C9_NFISCAL = '' AND 
						C9.D_E_L_E_T_ = '' 
					GROUP BY C9.C9_FILIAL,C9.C9_PEDIDO 
		)LIBERADO 
	WHERE 
		C5.C5_FILIAL = '0401' AND  
		C5.C5_NUM NOT IN( 
							SELECT  
								SC5.C5_XPVORIG  
							FROM 
								SC5040 SC5 
							WHERE 
								SC5.C5_FILIAL = '0404' AND  
								SC5.D_E_L_E_T_ = ''  
							) AND 
		C5.D_E_L_E_T_ = '' 
 ) PEDIDO_LIBERADO 
 WHERE 
	TOTAL_ITLIB = TOTAL_ITPED AND  
	TOTAL_QTDLIB = TOTAL_QTDPED 
 ORDER BY PEDIDO 