CREATE TABLE [dbo].[PRODUTOS1](
	[FILIAL] [INT] NULL,
	[CODIGO] [VARCHAR] (15) NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
	[MARCA] [varchar](100) NULL,
	[COR] [varchar](100) NOT NULL,
	[UNITARIO][NUMERIC](14,4)NOT NULL
) ON [PRIMARY]

DECLARE @I AS INT
SET @I = 0
WHILE @I < 50 BEGIN
	INSERT INTO PRODUTOS1(FILIAL,CODIGO,DESCRICAO,MARCA,COR,UNITARIO)
	SELECT TOP 1000
		1 + (CASE WHEN @I % 2 = 0 THEN @I ELSE 0 END) AS FILIAL
	,	PRODUTO.B4_COD
	,	PRODUTO.B4_DESC
	,	MARCAS.AY2_DESCR
	,	CORES.BV_DESCRI
	,	PRODUTO.B4_PRV1
	FROM 
	SB4010 PRODUTO
	CROSS JOIN AY2010 MARCAS
	CROSS JOIN SBV010 CORES
	
	SET @I = @I + 1
	
END	

SELECT PROD.CODIGO,PROD.DESCRICAO,AY2.AY2_CODIGO,PROD.MARCA,PROD.UNITARIO 
FROM 
PRODUTOS1 PROD
INNER JOIN AY2010 AY2 ON AY2.AY2_DESCR = PROD.MARCA AND AY2.D_E_L_E_T_ = ''
WHERE
PROD.UNITARIO > 600

	