CREATE CLUSTERED INDEX [CX_PRODUTOS1]
ON PRODUTOS1(CODIGO ASC) ON [PRIMARY]

CREATE NONCLUSTERED INDEX IX_PRODUTOS1 ON PRODUTOS1
(FILIAL ASC,CODIGO ASC, DESCRICAO ASC, UNITARIO ASC)

SET STATISTICS IO ON
SET STATISTICS TIME ON
DBCC SHOW_STATISTICS (PRODUTOS1,IX_PRODUTOS1)
SELECT	
	CODIGO ,
	DESCRICAO ,
	UNITARIO
FROM 
	PRODUTOS1 
WHERE 
	FILIAL = 11
AND MARCA = 'ADVENTEAM'


CREATE TABLE AUDITORIA(BANCO VARCHAR(100),TABELA VARCHAR(100),DATA DATETIME,OPERACAO VARCHAR(100))

CREATE TRIGGER TR_PRODUTOS1 ON PRODUTOS1 FOR INSERT
AS 
BEGIN
	INSERT INTO AUDITORIA(BANCO,TABELA,DATA,OPERACAO)
	SELECT 
		DB_NAME()
	,	'PRODUTO' + I.CODIGO
	,	GETDATE()
	,	'INSERT'
	FROM 
		INSERTED I
END			

INSERT INTO PRODUTOS1(CODIGO,COR,DESCRICAO,FILIAL,MARCA,UNITARIO)
SELECT
	'901415'
,	'BRANCO'
,	'BABY LOOK'
,	1
,	'VIV LEROA'
,	15.99	

SELECT * FROM AUDITORIA
SELECT * FROM PRODUTOS1 WHERE CODIGO = '901415'

CREATE TRIGGER TR_PRODUTOS1_UPD ON PRODUTOS1 FOR UPDATE
AS 
BEGIN
	INSERT INTO AUDITORIA(BANCO,TABELA,DATA,OPERACAO)
	SELECT 
		DB_NAME()
	,	'CODIGO ANTIGO ' + D.CODIGO + ' - CODIGO NOVO ' + I.CODIGO
	,	GETDATE()
	,	'UPDATE'
	FROM 
		INSERTED I,DELETED D
END			

UPDATE 
	PRODUTOS1
SET
	CODIGO = '300'
WHERE
	CODIGO = '901415'

SELECT * FROM AUDITORIA	

UPDATE PRODUTOS1 SET CODIGO = '901415'
WHERE
CODIGO = '300'

ALTER PROCEDURE SP_PRODUTOS1_SEL (
               @FILIAL AS INT = NULL
,              @CODIGO AS VARCHAR(100) = NULL
,              @DESCRICAO AS VARCHAR(100) = NULL
,              @UNITARIO AS NUMERIC(14,4) = NULL
)
AS
BEGIN
                SELECT * FROM PRODUTOS1 P
                WHERE
                    P.FILIAL = @FILIAL
                AND P.CODIGO = @CODIGO
                AND P.DESCRICAO = @DESCRICAO
                AND P.UNITARIO = @UNITARIO
END

SP_PRODUTOS1_SEL  @CODIGO = '300'

SELECT * FROM PRODUTOS1