 SELECT ED_CODIGO, 
 	ED_DESCRIC, 
 	ED_COND, 
 	NFILHOS, 
 	LVL, 
 	[01] AS JANEIRO, 
 	[02] AS FEVEREIRO, 
 	[03] AS MARCO, 
 	[04] AS ABRIL, 
 	[05] AS MAIO, 
 	[06] AS JUNHO, 
 	[07] AS JULHO, 
 	[08] AS AGOSTO, 
 	[09] AS SETEMBRO, 
 	[10] AS OUTUBRO, 
 	[11] AS NOVEMBRO, 
 	[12] AS DEZEMBRO 
 FROM 
 ( 
 		SELECT SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND,SUBSTRING(E5_DATA,5,2) AS MES, (ISNULL(SUM((E5_VALOR+E5_VLMULTA+E5_VLJUROS+E5_VLACRES)-E5_VLDESCO-E5_VLDECRE),0)) VALOR, SED.NFILHOS, SED.LVL 
     	FROM ufn_GETSUBTREE('  ','') SED 
    		LEFT OUTER JOIN SE5010 SE5 
 	   		ON SE5.E5_NATUREZ = SED.ED_CODIGO 
 	   		AND LEFT(SE5.E5_DATA,4) = '2015' 
 			AND SE5.E5_LA <> 'S' 
 	   		AND SE5.D_E_L_E_T_ = '' 
 		GROUP BY SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SED.NFILHOS, SED.LVL, SUBSTRING(E5_DATA,5,2) 

 ) AS T1 
 PIVOT (SUM(VALOR) 
 FOR MES IN ([01],[02],[03],[04],[05],[06],[07],[08],[09],[10],[11],[12])) AS T2 
 ORDER BY ED_CODIGO  