 SELECT ED_CODIGO, 
 	ED_DESCRIC, 
 	ED_COND, 
 	NFILHOS, 
 	LVL, 
 	[01] AS JANEIRO, 
 	[02] AS FEVEREIRO, 
 	[03] AS MARCO, 
 	[04] AS ABRIL, 
 	[05] AS MAIO, 
 	[06] AS JUNHO, 
 	[07] AS JULHO, 
 	[08] AS AGOSTO, 
 	[09] AS SETEMBRO, 
 	[10] AS OUTUBRO, 
 	[11] AS NOVEMBRO, 
 	[12] AS DEZEMBRO 
 FROM 
 ( 
 		SELECT SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND,SUBSTRING(E1_VENCREA,5,2) AS MESP, (ISNULL(SUM((E1_VALOR+E1_MULTA+E1_JUROS+E1_ACRESC+E1_CORREC)-E1_DESCONT-E1_DECRESC-E1_DESCFIN),0)) VALOR, SED.NFILHOS, SED.LVL 
     	FROM ufn_GETSUBTREE('  ','') SED 
    		LEFT OUTER JOIN SE1010 SE1 
 	   		ON SE1.E1_NATUREZ = SED.ED_CODIGO 
 	   		AND LEFT(SE1.E1_VENCREA,4) = '2015' 
 			--AND SE1.E1_FLAGFAT <> 'S' 
 	   		--AND SE1.E1_LA <> 'S' 
 	   		AND SE1.D_E_L_E_T_ = '' 
 		GROUP BY SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SED.NFILHOS, SED.LVL, SUBSTRING(E1_VENCREA,5,2) 
 	UNION ALL 
    		SELECT SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SUBSTRING(E2_VENCREA,5,2) AS MES, (ISNULL(SUM((E2_VALOR+E2_MULTA+E2_JUROS+E2_ACRESC+E2_CORREC)-E2_DESCONT-E2_DECRESC),0)*-1) VALOR, SED.NFILHOS, SED.LVL 
     	FROM ufn_GETSUBTREE('  ','') SED 
    		LEFT OUTER JOIN SE2010 SE2 
 	 		ON SE2.E2_NATUREZ = SED.ED_CODIGO 
 			AND LEFT(SE2.E2_VENCREA,4) = '2015' 
 			--AND SE2.E2_MULTNAT <> '1' 
 			--AND SE2.E2_FLAGFAT <> 'S' 
 			--AND (SE2.E2_DESDOBR <> 'S' OR (SE2.E2_DESDOBR = 'S' AND SE2.E2_PARCELA <> ''))
 			AND SE2.D_E_L_E_T_ = '' 
    		GROUP BY SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SED.NFILHOS, SED.LVL, SUBSTRING(E2_VENCREA,5,2) 
 	UNION ALL 
 		SELECT SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SUBSTRING(E2_VENCREA,5,2) AS MES, (ISNULL(SUM(EV_VALOR),0)*-1) VALOR, SED.NFILHOS, SED.LVL 
 		FROM ufn_GETSUBTREE('  ','') SED 
 		INNER JOIN SEV010 SEV 
   			ON SEV.EV_NATUREZ = SED.ED_CODIGO 
 			AND SEV.EV_RECPAG = 'P' 
 			AND SEV.EV_SITUACA = '' 
    			AND SEV.D_E_L_E_T_ = '' 
 		INNER JOIN SE2010 SE2 
    			ON SE2.E2_NUM = SEV.EV_NUM 
    			AND SE2.E2_FILIAL = SEV.EV_FILIAL 
 			AND SE2.E2_FORNECE = SEV.EV_CLIFOR 
    			AND SE2.E2_LOJA = SEV.EV_LOJA 
 			AND SE2.E2_TIPO = SEV.EV_TIPO 
 			AND LEFT(SE2.E2_VENCREA,4) = '2015' 
 			AND SE2.D_E_L_E_T_ = ''	
    		GROUP BY SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SED.NFILHOS, SED.LVL, SUBSTRING(E2_VENCREA,5,2) 
	UNION ALL 

		SELECT SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND,SUBSTRING(E5_DATA,5,2) AS MES, (ISNULL(SUM((E5_VALOR+E5_VLMULTA+E5_VLJUROS+E5_VLACRES)-E5_VLDESCO-E5_VLDECRE),0)) VALOR, SED.NFILHOS, SED.LVL 
     	FROM ufn_GETSUBTREE('  ','') SED 
    		LEFT OUTER JOIN SE5010 SE5 
 	   		ON SE5.E5_NATUREZ = SED.ED_CODIGO 
 	   		AND LEFT(SE5.E5_DATA,4) = '2015' 
 			AND SE5.E5_LA <> 'S' 
 	   		AND SE5.D_E_L_E_T_ = '' 
 		GROUP BY SED.ED_CODIGO, SED.ED_DESCRIC, SED.ED_COND, SED.NFILHOS, SED.LVL, SUBSTRING(E5_DATA,5,2) 

 ) AS T1 
 PIVOT (SUM(VALOR) 
 FOR MES IN ([01],[02],[03],[04],[05],[06],[07],[08],[09],[10],[11],[12])) AS T2 
 ORDER BY ED_CODIGO 
