WITH SW3 AS (
    SELECT 
        W3_FILIAL, 
        W3_PO_NUM, 
        MAX(W3_DT_EMB) AS W3_DT_EMB, 
        SUM(W3_PRECO * W3_QTDE) AS VALOR  
    FROM SW3010 WITH (NOLOCK)
    WHERE D_E_L_E_T_ = ''
      AND W3_FILIAL = ''
    GROUP BY W3_FILIAL, W3_PO_NUM
),
SWB_SUM AS (
    SELECT 
        WB_FILIAL, 
        WB_HAWB, 
        SUM(CASE WHEN WB_FOBMOE <> 0 THEN WB_FOBMOE ELSE WB_VLIQ END) AS VLRSWB 
    FROM SWB010 WITH (NOLOCK)
    WHERE D_E_L_E_T_ = ''
      AND WB_FILIAL = '0101'
      AND WB_PO_DI = 'D'
      AND WB_CA_DT <> ''
      AND WB_TIPOREG IN ('1','P')
    GROUP BY WB_FILIAL, WB_HAWB
),
TSALD AS (
    SELECT 
        W9_FILIAL, 
        W9_HAWB, 
        W9_INVOICE,
        ISNULL((W9_FOB_TOT + W9_OUTDESP) - SWB.VLRSWB, W9_FOB_TOT + W9_OUTDESP) AS SALDO
    FROM SW9010 WITH (NOLOCK)
    LEFT JOIN SWB_SUM SWB 
        ON SWB.WB_FILIAL = W9_FILIAL 
       AND SWB.WB_HAWB  = W9_HAWB
    WHERE SW9010.D_E_L_E_T_ = ''
),
TVLRNUM AS (
    SELECT WD_FILIAL, WD_HAWB, SUM(WD_VALOR_R) AS WD_VALOR_R
    FROM SWD010 WITH (NOLOCK)
    WHERE D_E_L_E_T_ = ''
      AND WD_FILIAL = '0101'
      AND WD_DESPESA = '901'
    GROUP BY WD_FILIAL, WD_HAWB
),
TVLRIMP AS (
    SELECT WD_FILIAL, WD_HAWB, SUM(WD_VALOR_R) AS WD_VALOR_R
    FROM SWD010 WITH (NOLOCK)
    WHERE D_E_L_E_T_ = ''
      AND WD_FILIAL = '0101'
      AND WD_DESPESA IN ('102','103','201','203')
    GROUP BY WD_FILIAL, WD_HAWB
)
SELECT DISTINCT
    SW2.W2_PO_NUM AS NUMERO_PO,
    ISNULL(SW6.W6_HAWB, '') AS NUM_PROCESSO,
    ISNULL(TSALD.W9_INVOICE, '') AS INVOICE,
    SW2.W2_FORN,
    ISNULL(SW9.W9_FOB_TOT + SW9.W9_OUTDESP, W3.VALOR) AS VALOR_FOB,
    SW2.W2_COND_PA + ' - ' + YP.YP_TEXTO AS CONDPAG,
    ISNULL(TSALD.SALDO, 0) AS SALDO,
    COALESCE(WB.WB_LC_NUM, '') AS LC,
    CASE 
        WHEN SW6.W6_DT_ENCE <> '' THEN '7-FINALIZADO'
        WHEN SW6.W6_DT_ENCE = '' AND SW6.W6_DTREG_D <> '' AND SW6.W6_NF_ENT <> '' AND ISNULL(F1_DOC,'') = '' THEN '5-AGUARDANDO NF COMPL.'
        WHEN SW6.W6_DT_ENCE = '' AND SW6.W6_DTREG_D <> '' AND SW6.W6_NF_ENT <> '' AND ISNULL(F1_DOC,'') <> '' THEN '6-AGUARDANDO ENCERRAMENTO DO PROCESSO'
        WHEN SW6.W6_DT_EMB = '' THEN '2-AGUARDANDO EMBARQUE'
        WHEN SW6.W6_DT_EMB <> '' AND SW6.W6_CHEG = '' THEN '3-EMBARCADO'
        WHEN SW6.W6_DT_EMB <> '' AND SW6.W6_CHEG <> '' AND SW6.W6_DTREG_D <> '' AND SW6.W6_NF_ENT = '' THEN '4-AGUARDANDO DESEMBARAÇO'
        WHEN SW6.W6_DT_EMB <> '' AND SW6.W6_CHEG <> '' AND SW6.W6_DTREG_D = '' AND SW6.W6_NF_ENT = '' THEN '4-AGUARDANDO DESEMBARAÇO'
        ELSE '1-FASE DE NEGOCIAÇÃO'
    END AS STATUS
FROM SW2010 SW2 WITH (NOLOCK)
LEFT JOIN SW6010 SW6 WITH (NOLOCK)
    ON SW2.W2_FILIAL = SW6.W6_FILIAL
   AND SW2.W2_PO_NUM = SW6.W6_PO_NUM
   AND SW6.D_E_L_E_T_ = ''
LEFT JOIN SW3 W3 
    ON W3.W3_FILIAL = SW2.W2_FILIAL 
   AND W3.W3_PO_NUM = SW2.W2_PO_NUM
LEFT JOIN SW9010 SW9 WITH (NOLOCK)
    ON SW6.W6_FILIAL = SW9.W9_FILIAL
   AND SW6.W6_HAWB = SW9.W9_HAWB
   AND SW9.D_E_L_E_T_ = ''
LEFT JOIN SY6010 SY6 WITH (NOLOCK)
    ON Y6_FILIAL = '01'
   AND SW2.W2_COND_PA = Y6_COD
   AND SY6.D_E_L_E_T_ = ''
LEFT JOIN SYP010 YP WITH (NOLOCK)
    ON YP_FILIAL = ''
   AND YP.YP_CHAVE = Y6_DESC_P
   AND YP.D_E_L_E_T_ = ''
LEFT JOIN TSALD 
    ON TSALD.W9_FILIAL = SW6.W6_FILIAL 
   AND TSALD.W9_HAWB = SW6.W6_HAWB
LEFT JOIN SY4010 SY4 WITH (NOLOCK)
    ON Y4_FILIAL = '01'
   AND SW2.W2_AGENTE = Y4_COD
   AND SY4.D_E_L_E_T_ = ''
LEFT JOIN TVLRNUM 
    ON TVLRNUM.WD_FILIAL = SW6.W6_FILIAL 
   AND TVLRNUM.WD_HAWB = SW6.W6_HAWB
LEFT JOIN TVLRIMP 
    ON TVLRIMP.WD_FILIAL = SW6.W6_FILIAL 
   AND TVLRIMP.WD_HAWB = SW6.W6_HAWB
LEFT JOIN SWB010 WB WITH (NOLOCK)
    ON WB.WB_FILIAL = SW6.W6_FILIAL
   AND WB.WB_HAWB = SW6.W6_HAWB
   AND WB.WB_LC_NUM <> ''
   AND WB.D_E_L_E_T_ = ''
LEFT JOIN SF1010 SF1 WITH (NOLOCK)
    ON SW6.W6_FILIAL = SF1.F1_FILIAL
   AND SW6.W6_HAWB = SF1.F1_HAWB
   AND SF1.F1_SERIE = 'C'
   AND SF1.D_E_L_E_T_ = ''
WHERE SW2.D_E_L_E_T_ = ''
  AND SW2.W2_FILIAL = '0101'
  AND SW2.W2_PO_DT BETWEEN '20210101' AND '20251231'
  --AND SW2.W2_PO_NUM = 'PEDASP0004'
ORDER BY STATUS DESC;
