WITH Base AS (
	SELECT
	     SW2.W2_PO_NUM,
	     SW2.W2_FORN,
	     SW2.W2_FORLOJ,
	     SW2.W2_PO_DT,
	     SW3.W3_COD_I,
	     SW3.W3_PART_N,
	     SW3.W3_QTDE,
	     SW3.W3_PRECO,
	     SW6.W6_HAWB,
	     SW6.W6_DT_ENTR,
	     SW6.W6_NF_ENT,
	     SW6.W6_DI_NUM,
	     SW6.W6_DT,
	     SW6.W6_DT_NF,
	     SW6.W6_DT_EMB,
	     SW6.W6_CHEG,
	     SW7.W7_HAWB,
	     SW8.W8_HAWB,
	     SW8.W8_INVOICE,
	     SW8.W8_DT_EMIS,
	     SW8.W8_QTDE AS W8_QTDE,
	     SW9.W9_COND_PA,
	     SW9.W9_DIAS_PA,
	     SW9.W9_INVOICE,
	     SA2.A2_NOME
	 FROM  SW2010  SW2
	 INNER JOIN  SW3010  SW3
	     ON SW3.D_E_L_E_T_ = '' 
	     AND SW3.W3_FILIAL = SW2.W2_FILIAL
	     AND SW3.W3_PO_NUM = SW2.W2_PO_NUM
	 	AND SW3.W3_SEQ <> ''
	 LEFT JOIN  SW6010  SW6
	     ON SW6.D_E_L_E_T_ = '' 
	     AND SW6.W6_FILIAL = SW2.W2_FILIAL
	     AND SW6.W6_PO_NUM = SW2.W2_PO_NUM
	 LEFT JOIN  SW7010  SW7
	     ON SW7.D_E_L_E_T_ = ''
	     AND SW7.W7_FILIAL = SW3.W3_FILIAL
	     AND SW7.W7_PO_NUM = SW3.W3_PO_NUM
	     AND SW7.W7_PGI_NUM = SW3.W3_PGI_NUM
	     AND SW7.W7_POSICAO = SW3.W3_POSICAO
	     AND SW7.W7_COD_I = SW3.W3_COD_I
	 LEFT JOIN  SW8010  SW8
	     ON SW8.D_E_L_E_T_ = ''
	     AND SW8.W8_HAWB = SW7.W7_HAWB
	     AND SW8.W8_PO_NUM = SW7.W7_PO_NUM
	     AND SW8.W8_POSICAO = SW7.W7_POSICAO
	     AND SW8.W8_PGI_NUM = SW7.W7_PGI_NUM
	 LEFT JOIN  SW9010  SW9
	     ON SW9.D_E_L_E_T_ = ''
	     AND SW9.W9_FILIAL = SW8.W8_FILIAL
	     AND SW9.W9_HAWB = SW8.W8_HAWB
	     AND SW9.W9_INVOICE = SW8.W8_INVOICE
	 INNER JOIN  SA2010  SA2
	     ON SA2.D_E_L_E_T_ = ''
	     AND SW3.W3_FORN = SA2.A2_COD
	     AND SW3.W3_FORLOJ = SA2.A2_LOJA
	 WHERE
	     SW2.D_E_L_E_T_ = ''
  AND W2_PO_NUM		BETWEEN ''	AND 'ZZZZZZZZZZ' 
  AND W2_PO_DT		BETWEEN '20250101'		AND '20260228' 
 )
, Saldo AS (
	SELECT
	SW8.W8_PO_NUM,
	SW8.W8_COD_I,
	SUM(SW8.W8_QTDE) AS Total_QTDE
FROM  SW8010  SW8
WHERE SW8.D_E_L_E_T_ = ''
GROUP BY SW8.W8_PO_NUM, SW8.W8_COD_I
)
SELECT
W3_COD_I AS SKU,
W3_PART_N AS COD_FABRICA,
W2_FORN AS COD_FOR,
W2_FORLOJ AS LOJ_FOR,
A2_NOME AS FORNECEDOR,
CASE 
	WHEN W6_DT_ENTR IS NOT NULL OR W6_NF_ENT IS NOT NULL THEN 'ENTREGUE'
	WHEN W8_DT_EMIS IS NOT NULL THEN 'TRANSITO'
	ELSE 'PED COMPRAS'
END AS STATUS,
ISNULL(W6_HAWB,'') AS PROCESSO,
W2_PO_NUM AS PO,
CASE WHEN W2_PO_DT = '' OR W2_PO_DT IS NULL THEN '' ELSE CONVERT(NVARCHAR, CONVERT(DATETIME, W2_PO_DT, 103), 103) END AS DATA_PO,
ISNULL(W6_DI_NUM,'') AS NUM_DI,
CASE WHEN W6_DT IS NULL OR W6_DT = '' THEN '' ELSE CONVERT(NVARCHAR, CONVERT(DATETIME, W6_DT, 103), 103) END AS DATA_DI,
ISNULL(W8_INVOICE,'') AS NUM_INVOICE,
CASE WHEN W8_DT_EMIS IS NULL OR W8_DT_EMIS = '' THEN '' ELSE CONVERT(NVARCHAR, CONVERT(DATETIME, W8_DT_EMIS, 103), 103) END AS DATA_INVOICE,
CASE WHEN W9_COND_PA IS NULL OR W9_COND_PA = '' THEN '' ELSE CONVERT(NVARCHAR, DATEADD(day, W9_DIAS_PA, W8_DT_EMIS), 103) END AS VENC_INVOICE,
ISNULL(W6_NF_ENT,'') AS NF,
CASE WHEN W6_DT_NF IS NULL OR W6_DT_NF = '' THEN '' ELSE CONVERT(NVARCHAR, CONVERT(DATETIME, W6_DT_NF, 103), 103) END AS DATA_NF,
CASE WHEN W6_DT_EMB IS NULL OR W6_DT_EMB = '' THEN '' ELSE CONVERT(NVARCHAR, CONVERT(DATETIME, W6_DT_EMB, 103), 103) END AS DATA_EMBARQUE,
CASE WHEN W6_CHEG IS NULL OR W6_CHEG = '' THEN '' ELSE CONVERT(NVARCHAR, CONVERT(DATETIME, W6_CHEG, 103), 103) END AS DATA_CHEGADA,
W3_QTDE AS QUANT,
W3_PRECO AS PRECO,
W3_QTDE*W3_PRECO AS TOTAL_PURCHASE,
ISNULL(Saldo.Total_QTDE,0) - W3_QTDE AS SALDO_Q
FROM Base
LEFT JOIN Saldo
ON Saldo.W8_PO_NUM = Base.W2_PO_NUM
AND Saldo.W8_COD_I = Base.W3_COD_I