-- 1.0.1.03.01015	OUTROS DIREITOS A RECEBER FORNECEDORES = VLR_ADIANTADO SEM DT_EMBARQUE SEM DI_NUM E SEM NF_ENTRADA - OS HEDGE LIQUIDADOS
-- 1.0.1.04.02001	ADIANTOS A FORNECEDORES IMPORTACAO = VLR_ADIANTADO COM DT_EMBARQUE SEM DI_NUM E SEM NF_ENTRADA - OS HEDGE LIQUIDADOS
-- 2.0.1.01.01002	FORNECEDORES ESTRANGEIROS = SALDO COM DT_EMBARQUE COM DI_NUM E COM NF_ENTRADA
-- 1.0.1.04.02007	PROCESSO ANTECIPADO EMBARCADO (A) = SALDO COM DT_EMBARQUE SEM DI_NUM E SEM NF_ENTRADA * TAXA PTAX DO ULTIMO DIA MES
-- 2.0.1.01.01015	FOR PROCESSO ANTECIPADO EMBARCADO = SALDO COM DT_EMBARQUE SEM DI_NUM E SEM NF_ENTRADA * TAXA PTAX DO ULTIMO DIA MES * -1
-- 1.0.1.04.02011	ESTOQUE IMPORTADO TRANSITO = HEDGE LIQUIDADOS SEM OU COM DT_EMBARQUE SEM DI_NUM E SEM NF_ENTRADA
-- 2.0.1.01.01014	FORNCEDORES HEDGEADO = HEDGE NAO LIQUIDADOS COM DT_EMBARQUE COM DI_NUM E COM NF_ENTRADA

SELECT 
	HAWB,
	DT_EMBARQUE,
	DI_NUM,
	NF_ENTRADA,
	DT_PO,
	TOTAL_PO_USA,
	VLR_ADIANTADO_USA,
	VLR_ADIANTADO_BRA,
	VLR_HEDGE_USA,
	VLR_HEDGE_BRA,
	(TOTAL_PO_USA - VLR_ADIANTADO_USA) SALDO_USA,
	(TOTAL_PO_USA - VLR_ADIANTADO_USA) SALDO_BRA
FROM 
(
	SELECT 
		CASE 
			WHEN W6.W6_HAWB <> '' THEN 
				W6.W6_HAWB 
			ELSE 
				W2.W2_PO_NUM
		END	HAWB,
		COALESCE(W6.W6_DT_EMB,'') DT_EMBARQUE,
		COALESCE(W6.W6_DI_NUM,'') DI_NUM,
		COALESCE(W6.W6_NF_ENT,'') NF_ENTRADA,
		W2.W2_PO_DT DT_PO,
		ROUND(W2.W2_FOB_TOT + W2.W2_INLAND + W2.W2_OUT_DES,2) TOTAL_PO_USA,
		COALESCE(ROUND(SWB_ADI.SALDO_ADIANTADO_USA,2),0) VLR_ADIANTADO_USA,
		COALESCE(ROUND(SWB_ADI.SALDO_ADIANTADO_BRA,2),0) VLR_ADIANTADO_BRA,
		COALESCE(ROUND(ZXD_HEDGE.SALDO_HEDGE_USA,2),0) VLR_HEDGE_USA,
		COALESCE(ROUND(ZXD_HEDGE.SALDO_HEDGE_BRA,2),0) VLR_HEDGE_BRA
	FROM 
		SW2040 W2
		LEFT JOIN SW6040 W6 ON W6.W6_FILIAL = W2.W2_FILIAL AND W6.W6_PO_NUM = W2.W2_PO_NUM AND W6.D_E_L_E_T_ = ''
		OUTER APPLY(
						SELECT 
							SUM(CASE 
								WHEN WB.WB_FOBMOE <> 0 THEN 
									WB.WB_FOBMOE 
								ELSE 
									WB.WB_VLIQ 
								END) SALDO_ADIANTADO_USA,
								SUM(CASE 
									WHEN WB.WB_FOBMOE <> 0 THEN 
										WB.WB_FOBMOE * WB.WB_CA_TX
									ELSE 
										WB.WB_VLIQ * WB.WB_CA_TX
									END) SALDO_ADIANTADO_BRA
						FROM 
							SWA040 WA 
							INNER JOIN SWB040 WB ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND  WB.WB_PO_DI = WA.WA_PO_DI AND WB.WB_TIPOREG = 'P' AND WB.D_E_L_E_T_ = '' 
						WHERE
							WA.WA_FILIAL = CASE WHEN W6.W6_FILIAL <> '' THEN W6.W6_FILIAL ELSE W2.W2_FILIAL END AND 
							WA.WA_HAWB = CASE WHEN W6.W6_HAWB <> '' THEN W6.W6_HAWB ELSE W2.W2_PO_NUM END AND 
							WA.WA_PO_DI = 'A' AND
							WA.D_E_L_E_T_ = '' 
						GROUP BY WA.WA_FILIAL,WA.WA_HAWB 
					) SWB_ADI
			OUTER APPLY(
						SELECT 
							SUM(CASE 
								WHEN WB.WB_FOBMOE <> 0 THEN 
									WB.WB_FOBMOE 
								ELSE 
									WB.WB_VLIQ 
								END) SALDO_HEDGE_USA,
								SUM(CASE 
								WHEN WB.WB_FOBMOE <> 0 THEN 
									WB.WB_FOBMOE * ZXD.ZXD_CA_TX
								ELSE 
									WB.WB_VLIQ * ZXD.ZXD_CA_TX
								END) SALDO_HEDGE_BRA
						FROM 
							SWA040 WA 
							INNER JOIN SWB040 WB ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND  WB.WB_PO_DI = WA.WA_PO_DI AND WB.WB_TIPOREG = 'P' AND WB.D_E_L_E_T_ = '' 
							INNER JOIN ZXD040 ZXD ON ZXD.ZXD_FILIAL = WA.WA_FILIAL AND ZXD.ZXD_HAWB = WA.WA_HAWB AND ZXD.D_E_L_E_T_ = ''
						WHERE
							WA.WA_FILIAL = CASE WHEN W6.W6_FILIAL <> '' THEN W6.W6_FILIAL ELSE W2.W2_FILIAL END AND 
							WA.WA_HAWB = CASE WHEN W6.W6_HAWB <> '' THEN W6.W6_HAWB ELSE W2.W2_PO_NUM END AND 
							WA.WA_PO_DI = 'D' AND
							WA.D_E_L_E_T_ = '' 
						GROUP BY WA.WA_FILIAL,WA.WA_HAWB 
					) ZXD_HEDGE
	WHERE
		W2.W2_FILIAL = '0404' AND
		W2.W2_PO_DT BETWEEN '20200101' AND '20210331' AND 
		W2.W2_PO_NUM = '20.02-SC-TIANDA' AND
		W2.D_E_L_E_T_ = ''
)CONTABIL 
--WHERE 
--	DI_NUM = '' AND 
--	NF_ENTRADA = '' 
ORDER BY HAWB

--SELECT * FROM ZXD040 WHERE D_E_L_E_T_ = ''
--SELECT * FROM SW2040 WHERE W2_PO_NUM = '20.02-SC-KANG    ' AND D_E_L_E_T_ = ''
--SELECT * FROM SW3040 WHERE W3_PO_NUM = '20.06-SC-XI' AND D_E_L_E_T_ = ''
--SELECT * FROM SWA040 WHERE WA_HAWB = '20.02-SC-TIANDA' AND D_E_L_E_T_ = ''
--SELECT * FROM SWB040 WHERE WB_HAWB = '20.02-SC-TIANDA' AND D_E_L_E_T_ = ''
--SELECT * FROM SW6040 WHERE W6_HAWB = '20.05-SC-BIOSER' AND D_E_L_E_T_ = ''
--SELECT * FROM SW9040 WHERE W9_HAWB = '20.01-SC-NOVEL' AND D_E_L_E_T_ = ''
SELECT * FROM ZZ9040 WHERE D_E_L_E_T_ = ''

SELECT 
	E4_CODIGO,
	E4_INFER,
	E4_SUPER
 FROM 
	SE4040 
 WHERE 
	E4_FILIAL = '    ' AND 
	E4_INFER <= 10000  AND
	E4_INFER <> 0 AND 
	E4_XTGV = '1' AND 
	E4_MSBLQL <> '1' AND 
	D_E_L_E_T_ = '' 
 ORDER BY E4_CODIGO 


 SELECT * FROM SA1040 WHERE A1_COND <> '' AND D_E_L_E_T_ = '' 
 SELECT * FROM ZXF040 WHERE D_E_L_E_T_ = ''
 SELECT * FROM ZZ9040 WHERE D_E_L_E_T_ = ''


 UPDATE SE4040 SET E4_XAVAENV = '1' 
 WHERE 
 E4_CODIGO IN('110','111','113','112','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130','131','132','133','134','135','136','137')