SELECT 
	HAWB, 
	DT_EMBARQUE, 
	DI_NUM, 
	NF_ENTRADA, 
	DT_PO, 
	TOTAL_PO_USA, 
	VLR_ADIANTADO_USA, 
	VLR_ADIANTADO_BRA, 
	VLR_HEDGE_USA, 
	VLR_HEDGE_BRA, 
	(TOTAL_PO_USA - VLR_ADIANTADO_USA) SALDO_USA, 
	(TOTAL_PO_USA - VLR_ADIANTADO_USA) SALDO_BRA,
	VALOR_CONTABIL,
	CONTROLE_CAMBIO
 FROM 
 ( 
	SELECT  
		CASE 
			WHEN W6.W6_HAWB <> '' THEN 
				W6.W6_HAWB 
			ELSE 
				W2.W2_PO_NUM 
		END	HAWB, 
		COALESCE(W6.W6_DT_EMB,'') DT_EMBARQUE, 
		COALESCE(W6.W6_DI_NUM,'') DI_NUM, 
		COALESCE(W6.W6_NF_ENT,'') NF_ENTRADA, 
		W2.W2_PO_DT DT_PO, 
		ROUND(W2.W2_FOB_TOT + W2.W2_INLAND + W2.W2_OUT_DES,2) TOTAL_PO_USA, 
		COALESCE(ROUND(SWB_ADI.SALDO_ADIANTADO_USA,2),0) VLR_ADIANTADO_USA, 
		COALESCE(ROUND(SWB_ADI.SALDO_ADIANTADO_BRA,2),0) VLR_ADIANTADO_BRA, 
		COALESCE(ROUND(ZXD_HEDGE.SALDO_HEDGE_USA,2),0) VLR_HEDGE_USA, 
		COALESCE(ROUND(ZXD_HEDGE.SALDO_HEDGE_BRA,2),0) VLR_HEDGE_BRA,
		COALESCE(CT2_EIC.VALOR_CT2,0) VALOR_CONTABIL,
		CAMBIO_ATUAL.CAMBIO CONTROLE_CAMBIO
	FROM 
		SW2040 W2 
		LEFT JOIN SW6040 W6 ON W6.W6_FILIAL = W2.W2_FILIAL AND W6.W6_PO_NUM = W2.W2_PO_NUM AND W6.D_E_L_E_T_ = ''
		CROSS APPLY(
					SELECT  
						CASE 
							WHEN WA.WA_HAWB <> '' THEN
								'CAMBIO'
							ELSE 
								''
						END CAMBIO
					FROM 
						SWA040 WA  
						INNER JOIN SWB040 WB ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND WB.WB_TIPOREG = 'P' AND (WB.WB_CA_DT BETWEEN '20210101' AND '20210331' OR WB.WB_CA_DT = '')  AND WB.D_E_L_E_T_ = ''  
					WHERE 
						WA.WA_FILIAL = CASE WHEN W6.W6_FILIAL <> '' THEN W6.W6_FILIAL ELSE W2.W2_FILIAL END AND 
						WA.WA_HAWB = CASE WHEN W6.W6_HAWB <> '' THEN W6.W6_HAWB ELSE W2.W2_PO_NUM END AND 
						WA.D_E_L_E_T_ = '' 
					GROUP BY WA.WA_FILIAL,WA.WA_HAWB 
		) CAMBIO_ATUAL 
		OUTER APPLY( 
						SELECT  
							SUM(CASE 
								WHEN WB.WB_FOBMOE <> 0 THEN 
									WB.WB_FOBMOE 
								ELSE 
									WB.WB_VLIQ 
								END) SALDO_ADIANTADO_USA, 
                            SUM(CASE 
									WHEN WB.WB_FOBMOE <> 0 THEN 
										WB.WB_FOBMOE * WB.WB_CA_TX 
									ELSE 
										WB.WB_VLIQ * WB.WB_CA_TX 
									END) SALDO_ADIANTADO_BRA 
						FROM 
							SWA040 WA  
							INNER JOIN SWB040 WB ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND  WB.WB_PO_DI = WA.WA_PO_DI AND WB.WB_TIPOREG = 'P' AND WB.D_E_L_E_T_ = ''  
						WHERE 
							WA.WA_FILIAL = CASE WHEN W6.W6_FILIAL <> '' THEN W6.W6_FILIAL ELSE W2.W2_FILIAL END AND 
							WA.WA_HAWB = CASE WHEN W6.W6_HAWB <> '' THEN W6.W6_HAWB ELSE W2.W2_PO_NUM END AND 
							WA.WA_PO_DI = 'A' AND 
							WA.D_E_L_E_T_ = '' 
						GROUP BY WA.WA_FILIAL,WA.WA_HAWB 
					) SWB_ADI 
			OUTER APPLY( 
						SELECT 
							SUM(CASE 
								WHEN WB.WB_FOBMOE <> 0 THEN 
									WB.WB_FOBMOE 
								ELSE 
									WB.WB_VLIQ 
								END) SALDO_HEDGE_USA, 
							SUM(CASE 
								WHEN WB.WB_FOBMOE <> 0 THEN 
									WB.WB_FOBMOE * ZXD.ZXD_CA_TX 
								ELSE 
									WB.WB_VLIQ * ZXD.ZXD_CA_TX 
								END) SALDO_HEDGE_BRA 
						FROM 
							SWA040 WA 
							INNER JOIN SWB040 WB ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND  WB.WB_PO_DI = WA.WA_PO_DI AND WB.WB_TIPOREG = 'P' AND WB.WB_X_HEDGE = '1' AND WB.D_E_L_E_T_ = '' 
							INNER JOIN ZXD040 ZXD ON ZXD.ZXD_FILIAL = WA.WA_FILIAL AND ZXD.ZXD_HAWB = WA.WA_HAWB AND ZXD.D_E_L_E_T_ = '' 
						WHERE 
							WA.WA_FILIAL = CASE WHEN W6.W6_FILIAL <> '' THEN W6.W6_FILIAL ELSE W2.W2_FILIAL END AND 
							WA.WA_HAWB = CASE WHEN W6.W6_HAWB <> '' THEN W6.W6_HAWB ELSE W2.W2_PO_NUM END AND 
							WA.WA_PO_DI = 'D' AND 
							WA.D_E_L_E_T_ = '' 
						GROUP BY WA.WA_FILIAL,WA.WA_HAWB  
					) ZXD_HEDGE 
				OUTER APPLY( 
						SELECT 
							SUM(CT2.CT2_VALOR) VALOR_CT2 
						FROM 
							SWB040 WB WITH (NOLOCK) 
							INNER JOIN CT2040 CT2 WITH (NOLOCK) ON CT2.CT2_FILIAL = '0404' AND CT2_LOTE = '008850' AND CT2_KEY =  WB.WB_FILIAL + WB.WB_PREFIXO + WB.WB_NUMDUP + WB.WB_PARCELA + WB.WB_TIPOTIT + WB.WB_FORN + WB.WB_LOJA AND CT2.D_E_L_E_T_ = ''
						WHERE 
							WB.WB_FILIAL = W6.W6_FILIAL AND
							WB.WB_HAWB = W6.W6_HAWB AND 
							WB.WB_TIPOREG = 'P' AND
							WB.D_E_L_E_T_ = '' 
					) CT2_EIC
	WHERE 
		W2.W2_FILIAL = '0404' AND 
		W2.W2_PO_DT <= '20210331' AND 
		W2.D_E_L_E_T_ = '' 
 ) CONTABIL 
 ORDER BY HAWB

 SELECT WB_FILIAL,WB_PREFIXO,WB_NUMDUP,WB_PARCELA,WB_TIPOTIT,WB_FORN,WB_LOJA,* FROM SWB040 WHERE WB_HAWB = '17.01-SC-RYMCO   ' AND D_E_L_E_T_ = ''
 SELECT * FROM SE2040 WHERE E2_FILIAL = '0401' AND E2_HAWBEIC = '17.01-SC-ELEC' AND D_E_L_E_T_ = ''
/*
SELECT 
	SUM(CASE 
		WHEN WB.WB_FOBMOE <> 0 THEN 
			WB.WB_FOBMOE * WB.WB_CA_TX 
		ELSE 
			WB.WB_VLIQ * WB.WB_CA_TX 
		END) SALDO_ADIANTADO_BRA,
	SUM(CT2.CT2_VALOR) VALOR 
FROM 
	SWB040 WB WITH (NOLOCK) 
	INNER JOIN CT2040 CT2 WITH (NOLOCK) ON CT2.CT2_FILIAL = '0404' AND CT2_KEY =  WB.WB_FILIAL + WB.WB_PREFIXO + WB.WB_NUMDUP + WB.WB_PARCELA + WB.WB_TIPOTIT + WB.WB_FORN + WB.WB_LOJA AND CT2.D_E_L_E_T_ = ''
WHERE 
	WB.WB_FILIAL = '0404' AND
	WB.WB_HAWB = '20.06-SC-BIOCAT-A' AND 
	WB.WB_TIPOREG = '1' AND
	WB.D_E_L_E_T_ = ''
*/

SELECT UA_XBLQ,UA_XBLQMAN,UA_XENVSUP,* FROM SUA040 WHERE UA_NUM = '120435' AND UA_FILIAL = '0404' AND D_E_L_E_T_ = '' 

UPDATE SUA040 SET UA_XBLQMAN = '' 
WHERE UA_NUM = '120435' AND UA_FILIAL = '0404' AND D_E_L_E_T_ = '' 


SELECT A1_GRPTRIB,A1_EST,* FROM SA1040 WHERE A1_COD = '127107' AND A1_LOJA = '0001' AND D_E_L_E_T_ = ''
SELECT B1_GRTRIB,B1_GRPTI,* FROM SB1040 WHERE B1_COD = '4241' AND D_E_L_E_T_ = ''

SELECT * FROM SFM040 WHERE FM_FILIAL = '0404' AND FM_TIPO = '01' AND FM_GRTRIB = 'CRF' AND FM_EST = 'RJ'AND FM_GRPROD = '043' AND D_E_L_E_T_ = ''

SELECT * FROM SFM040 SFM WHERE SFM.FM_FILIAL = '0404'AND SFM.FM_TIPO = '01'AND SFM.D_E_L_E_T_=' ' ORDER BY FM_FILIAL,FM_TIPO,FM_PRODUTO,FM_CLIENTE,FM_LOJACLI,FM_ID




SELECT F4_VLRZERO,* FROM SF4040 WHERE F4_MSBLQL <> '1' AND D_E_L_E_T_ = ''