WITH CATEGORIAS(CODCATEG,DESCRICAO) AS 
( 
    SELECT ACU_COD,ACU_DESC
    FROM 
    ACU010
    WHERE 
    D_E_L_E_T_ = ' '
    UNION ALL 
    SELECT ACU_COD, ACU_DESC
    FROM ACU010 AC
    INNER JOIN CATEGORIAS CAT ON AC.ACU_COD = CAT.CODCATEG
)
SELECT * FROM CATEGORIAS
OPTION(MAXRECURSION 0)
