 WITH BASE AS ( 
    SELECT 
        W2.W2_PO_NUM, 
        W2.W2_FILIAL, 
        W2.W2_PO_DT, 
        ROUND(W2.W2_FOB_TOT + W2.W2_INLAND + W2.W2_OUT_DES, 2) AS TOTAL_PO_USA, 
        ISNULL(W6.W6_HAWB, W2.W2_PO_NUM) AS HAWB, 
        W6.W6_DT_EMB AS DT_EMBARQUE, 
        W6.W6_DI_NUM AS DI_NUM, 
        W6.W6_NF_ENT 
    FROM SW2040 W2 (NOLOCK) 
    INNER JOIN SW6040 W6 (NOLOCK) 
        ON W6.W6_FILIAL = W2.W2_FILIAL AND W6.W6_PO_NUM = W2.W2_PO_NUM AND W6.D_E_L_E_T_ = '' 
    WHERE W2.W2_FILIAL = '0404' AND W2.W2_PO_DT BETWEEN '20240101' AND '20250530' AND W2.D_E_L_E_T_ = '' 
 ), 
 ADTO AS ( 
    SELECT 
        WA.WA_HAWB, 
        WA.WA_FILIAL, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE ELSE WB.WB_VLIQ END) AS SALDO_ADIANTADO_USA, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE * WB.WB_CA_TX ELSE WB.WB_VLIQ * WB.WB_CA_TX END) AS SALDO_ADIANTADO_BRA 
    FROM SWA040 WA (NOLOCK) 
    INNER JOIN SWB040 WB (NOLOCK) 
        ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND WB.WB_PO_DI = WA.WA_PO_DI 
        AND WB.WB_TIPOREG = 'P' AND WB.D_E_L_E_T_ = '' 
    WHERE WA.WA_PO_DI = 'A' AND WA.D_E_L_E_T_ = '' 
    GROUP BY WA.WA_FILIAL, WA.WA_HAWB 
 ), 
 HEDGE AS ( 
    SELECT 
        WA.WA_HAWB, 
        WA.WA_FILIAL, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE ELSE WB.WB_VLIQ END) AS SALDO_HEDGE_USA, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE * ZXD.ZXD_CA_TX ELSE WB.WB_VLIQ * ZXD.ZXD_CA_TX END) AS SALDO_HEDGE_BRA 
    FROM SWA040 WA (NOLOCK) 
    INNER JOIN SWB040 WB (NOLOCK) 
        ON WB.WB_FILIAL = WA.WA_FILIAL AND WB.WB_HAWB = WA.WA_HAWB AND WB.WB_PO_DI = WA.WA_PO_DI 
        AND WB.WB_TIPOREG = 'P' AND WB.WB_X_HEDGE = '1' AND WB.D_E_L_E_T_ = '' 
    INNER JOIN ZXD040 ZXD (NOLOCK) 
        ON ZXD.ZXD_FILIAL = WA.WA_FILIAL AND ZXD.ZXD_HAWB = WA.WA_HAWB AND ZXD.D_E_L_E_T_ = '' 
    WHERE WA.WA_PO_DI = 'D' AND WA.D_E_L_E_T_ = '' 
    GROUP BY WA.WA_FILIAL, WA.WA_HAWB 
 ), 
 VALOR_CT2 AS ( 
    SELECT 
        WB.WB_HAWB, 
        WB.WB_FILIAL, 
        SUM(CT2.CT2_VALOR) AS VALOR_CONTABIL 
    FROM SWB040 WB (NOLOCK) 
    INNER JOIN CT2040 CT2 (NOLOCK) 
        ON CT2.CT2_FILIAL = WB.WB_FILIAL 
        AND CT2.CT2_KEY = WB.WB_FILIAL + WB.WB_PREFIXO + WB.WB_NUMDUP + WB.WB_PARCELA + WB.WB_TIPOTIT + WB.WB_FORN + WB.WB_LOJA 
        AND CT2.CT2_LOTE = '008850' 
        AND CT2.D_E_L_E_T_ = '' 
    WHERE WB.WB_TIPOREG = 'P' AND WB.D_E_L_E_T_ = '' 
    GROUP BY WB.WB_FILIAL, WB.WB_HAWB 
 ) 
 SELECT 
    B.HAWB, 
    B.DT_EMBARQUE, 
    B.DI_NUM, 
    B.W6_NF_ENT AS NF_ENTRADA, 
    B.W2_PO_DT AS DT_PO, 
    B.TOTAL_PO_USA, 
    ISNULL(A.SALDO_ADIANTADO_USA, 0) AS VLR_ADIANTADO_USA, 
    ISNULL(A.SALDO_ADIANTADO_BRA, 0) AS VLR_ADIANTADO_BRA, 
    ISNULL(H.SALDO_HEDGE_USA, 0) AS VLR_HEDGE_USA, 
    ISNULL(H.SALDO_HEDGE_BRA, 0) AS VLR_HEDGE_BRA, 
    B.TOTAL_PO_USA - ISNULL(A.SALDO_ADIANTADO_USA, 0) AS SALDO_USA, 
    B.TOTAL_PO_USA - ISNULL(A.SALDO_ADIANTADO_USA, 0) AS SALDO_BRA, 
    ISNULL(C.VALOR_CONTABIL, 0) AS VALOR_CONTABIL 
 FROM BASE B 
	 LEFT JOIN ADTO A ON A.WA_HAWB = B.HAWB AND A.WA_FILIAL = B.W2_FILIAL 
	 LEFT JOIN HEDGE H ON H.WA_HAWB = B.HAWB AND H.WA_FILIAL = B.W2_FILIAL 
	 LEFT JOIN VALOR_CT2 C ON C.WB_HAWB = B.HAWB AND C.WB_FILIAL = B.W2_FILIAL 
where 
	A.SALDO_ADIANTADO_USA > 0 AND 
	B.DT_EMBARQUE <> '' AND  
	B.DI_NUM = '' AND 
	B.W6_NF_ENT = ''
 ORDER BY B.HAWB 