WITH BASE AS ( 
    SELECT 
        W2.W2_PO_NUM, 
        W2.W2_FILIAL, 
        W2.W2_PO_DT, 
        ROUND(W2.W2_FOB_TOT + W2.W2_INLAND + W2.W2_OUT_DES, 2) AS TOTAL_PO_USA, 
        W2.W2_PO_NUM AS PONUM, 
        ISNULL(W6.W6_HAWB, W2.W2_PO_NUM) AS HAWB, 
        ISNULL(W6.W6_DT_EMB,'') AS DT_EMBARQUE, 
        ISNULL(W6.W6_DI_NUM,'') AS DI_NUM, 
        ISNULL(W6.W6_NF_ENT,'') AS W6_NF_ENT 
    FROM SW2040 W2 WITH(NOLOCK) 
    LEFT JOIN SW6040 W6 WITH(NOLOCK) 
        ON W6.W6_FILIAL = W2.W2_FILIAL 
        AND W6.W6_PO_NUM = W2.W2_PO_NUM 
        AND W6.D_E_L_E_T_ = '' 
    WHERE W2.W2_FILIAL = '0404' 
        AND W2.W2_PO_DT BETWEEN '20250101' AND '20260210' 
        AND W2.D_E_L_E_T_ = '' 
 ), 
 ADTO AS ( 
    SELECT 
        WA.WA_HAWB, 
        WA.WA_FILIAL, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE ELSE WB.WB_VLIQ END) AS SALDO_ADIANTADO_USA, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE * WB.WB_CA_TX ELSE WB.WB_VLIQ * WB.WB_CA_TX END) AS SALDO_ADIANTADO_BRA 
    FROM SWA040 WA WITH(NOLOCK) 
    INNER JOIN SWB040 WB WITH(NOLOCK) 
        ON WB.WB_FILIAL = WA.WA_FILIAL 
        AND WB.WB_HAWB = WA.WA_HAWB 
        AND WB.WB_PO_DI = WA.WA_PO_DI 
        AND WB.WB_TIPOREG = 'P' 
        AND WB.D_E_L_E_T_ = '' 
    WHERE WA.WA_PO_DI = 'A' 
        AND WA.D_E_L_E_T_ = '' 
    GROUP BY WA.WA_FILIAL, WA.WA_HAWB 
 ), 
 HEDGE AS ( 
    SELECT 
        WA.WA_HAWB, 
        WA.WA_FILIAL, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE ELSE WB.WB_VLIQ END) AS SALDO_HEDGE_USA, 
        SUM(CASE WHEN WB.WB_FOBMOE <> 0 THEN WB.WB_FOBMOE * ZXD.ZXD_CA_TX ELSE WB.WB_VLIQ * ZXD.ZXD_CA_TX END) AS SALDO_HEDGE_BRA 
    FROM SWA040 WA WITH(NOLOCK) 
    INNER JOIN SWB040 WB WITH(NOLOCK) 
        ON WB.WB_FILIAL = WA.WA_FILIAL 
        AND WB.WB_HAWB = WA.WA_HAWB 
        AND WB.WB_PO_DI = WA.WA_PO_DI 
        AND WB.WB_TIPOREG = 'P' 
        AND WB.WB_X_HEDGE = '1' 
        AND WB.D_E_L_E_T_ = '' 
    INNER JOIN ZXD040 ZXD WITH(NOLOCK) 
        ON ZXD.ZXD_FILIAL = WA.WA_FILIAL 
        AND ZXD.ZXD_HAWB = WA.WA_HAWB 
        AND ZXD.D_E_L_E_T_ = '' 
    WHERE WA.WA_PO_DI = 'D' 
        AND WA.D_E_L_E_T_ = '' 
    GROUP BY WA.WA_FILIAL, WA.WA_HAWB 
 ), 
 VALOR_CT2 AS ( 
    SELECT 
        WB.WB_HAWB, 
        WB.WB_FILIAL, 
        SUM(CT2.CT2_VALOR) AS VALOR_CONTABIL 
    FROM SWB040 WB WITH(NOLOCK) 
    INNER JOIN CT2040 CT2 WITH(NOLOCK) 
        ON CT2.CT2_FILIAL = WB.WB_FILIAL 
        AND CT2.CT2_KEY = WB.WB_FILIAL + WB.WB_PREFIXO + WB.WB_NUMDUP + WB.WB_PARCELA + WB.WB_TIPOTIT + WB.WB_FORN + WB.WB_LOJA 
        AND CT2.CT2_LOTE = '008850' 
        AND CT2.D_E_L_E_T_ = '' 
    WHERE WB.WB_TIPOREG = 'P' 
        AND WB.D_E_L_E_T_ = '' 
    GROUP BY WB.WB_FILIAL, WB.WB_HAWB 
 ), 
 FORMULAS AS ( 
    SELECT 
        ZF_CONTAD, 
        ZF_DESCTD, 
        ZF_CONTAC, 
        ZF_DESCTC, 
        ZF_FORMUL, 
        ZF_VLR01, 
        ZF_PTAX, 
        ROW_NUMBER() OVER (ORDER BY ZF_CONTAD, ZF_CONTAC) AS FORMULA_ID 
    FROM SZF040 WITH(NOLOCK) 
    WHERE ZF_ATIVO = 'T' 
        AND ZF_FORMUL <> '' 
        AND D_E_L_E_T_ = '' 
 ), 
 DADOS_COMPLETOS AS ( 
    SELECT 
        B.PONUM, 
        B.HAWB, 
        B.DT_EMBARQUE, 
        B.DI_NUM, 
        B.W6_NF_ENT AS NF_ENTRADA, 
        B.W2_PO_DT AS DT_PO, 
        B.TOTAL_PO_USA, 
        ISNULL(A.SALDO_ADIANTADO_USA, 0) AS VLR_ADTDO_USA, 
        ISNULL(A.SALDO_ADIANTADO_BRA, 0) AS VLR_ADTDO_BRA, 
        ISNULL(H.SALDO_HEDGE_USA, 0) AS VLR_HEDGE_USA, 
        ISNULL(H.SALDO_HEDGE_BRA, 0) AS VLR_HEDGE_BRA, 
        B.TOTAL_PO_USA - ISNULL(A.SALDO_ADIANTADO_USA, 0) AS SALDO_USA, 
        B.TOTAL_PO_USA - ISNULL(A.SALDO_ADIANTADO_USA, 0) AS SALDO_BRA, 
        ISNULL(C.VALOR_CONTABIL, 0) AS VALOR_CONTABIL, 
        CASE WHEN A.SALDO_ADIANTADO_USA > 0 THEN 1 ELSE 0 END AS TEM_ADTO_USA, 
        CASE WHEN A.SALDO_ADIANTADO_BRA > 0 THEN 1 ELSE 0 END AS TEM_ADTO_BRA, 
        CASE WHEN H.SALDO_HEDGE_BRA > 0 THEN 1 ELSE 0 END AS TEM_HEDGE_BRA, 
        CASE WHEN B.DT_EMBARQUE <> '' THEN 1 ELSE 0 END AS TEM_EMBARQUE, 
        CASE WHEN B.DI_NUM <> '' THEN 1 ELSE 0 END AS TEM_DI, 
        CASE WHEN B.W6_NF_ENT <> '' THEN 1 ELSE 0 END AS TEM_NF 
    FROM BASE B 
        LEFT JOIN ADTO A ON A.WA_HAWB = B.HAWB AND A.WA_FILIAL = B.W2_FILIAL 
        LEFT JOIN HEDGE H ON H.WA_HAWB = B.HAWB AND H.WA_FILIAL = B.W2_FILIAL 
        LEFT JOIN VALOR_CT2 C ON C.WB_HAWB = B.HAWB AND C.WB_FILIAL = B.W2_FILIAL 
 ) 
 SELECT 
    F.FORMULA_ID, 
    F.ZF_CONTAD AS CONTA_DEBITO, 
    F.ZF_DESCTD AS DESC_DEBITO, 
    F.ZF_CONTAC AS CONTA_CREDITO, 
    F.ZF_DESCTC AS DESC_CREDITO, 
    F.ZF_VLR01 AS FORMULA_VALOR, 
    F.ZF_PTAX AS USA_PTAX, 
    D.PONUM, 
    D.HAWB, 
    D.DT_EMBARQUE, 
    D.DI_NUM, 
    D.NF_ENTRADA, 
    D.DT_PO, 
    D.TOTAL_PO_USA, 
    D.VLR_ADTDO_USA, 
    D.VLR_ADTDO_BRA, 
    D.VLR_HEDGE_USA, 
    D.VLR_HEDGE_BRA, 
    D.SALDO_USA, 
    D.SALDO_BRA, 
    D.VALOR_CONTABIL 
 FROM FORMULAS F 
 CROSS APPLY ( 
    SELECT * 
    FROM DADOS_COMPLETOS D 
    WHERE 
        (F.ZF_FORMUL LIKE '%SALDO_ADIANTADO_BRA%' AND F.ZF_FORMUL LIKE '%DT_EMBARQUE <> ''''%' AND F.ZF_FORMUL LIKE '%DI_NUM = ''''%' AND F.ZF_FORMUL LIKE '%W6_NF_ENT = ''''%' AND D.TEM_ADTO_BRA = 1 AND D.TEM_EMBARQUE = 1 AND D.TEM_DI = 0 AND D.TEM_NF = 0) 
        OR (F.ZF_FORMUL LIKE '%SALDO_ADIANTADO_BRA%' AND F.ZF_FORMUL LIKE '%DT_EMBARQUE = ''''%' AND F.ZF_FORMUL LIKE '%DI_NUM = ''''%' AND F.ZF_FORMUL LIKE '%W6_NF_ENT = ''''%' AND D.TEM_ADTO_BRA = 1 AND D.TEM_EMBARQUE = 0 AND D.TEM_DI = 0 AND D.TEM_NF = 0) 
        OR (F.ZF_FORMUL LIKE '%SALDO_ADIANTADO_USA%' AND F.ZF_FORMUL LIKE '%DT_EMBARQUE <> ''''%' AND F.ZF_FORMUL LIKE '%DI_NUM <> ''''%' AND F.ZF_FORMUL LIKE '%W6_NF_ENT <> ''''%' AND D.TEM_ADTO_USA = 1 AND D.TEM_EMBARQUE = 1 AND D.TEM_DI = 1 AND D.TEM_NF = 1) 
        OR (F.ZF_FORMUL LIKE '%SALDO_HEDGE_BRA%' AND F.ZF_FORMUL LIKE '%DT_EMBARQUE <> ''''%' AND F.ZF_FORMUL LIKE '%DI_NUM <> ''''%' AND F.ZF_FORMUL LIKE '%W6_NF_ENT <> ''''%' AND D.TEM_HEDGE_BRA = 1 AND D.TEM_EMBARQUE = 1 AND D.TEM_DI = 1 AND D.TEM_NF = 1) 
        OR (F.ZF_FORMUL LIKE '%SALDO_HEDGE_BRA%' AND F.ZF_FORMUL LIKE '%DT_EMBARQUE <> ''''%' AND F.ZF_FORMUL LIKE '%DI_NUM = ''''%' AND F.ZF_FORMUL LIKE '%W6_NF_ENT = ''''%' AND D.TEM_HEDGE_BRA = 1 AND D.TEM_EMBARQUE = 1 AND D.TEM_DI = 0 AND D.TEM_NF = 0) 
 ) D 
 ORDER BY F.FORMULA_ID, D.HAWB 