SELECT DISTINCT(AY3.AY3_CODIGO), 
CAST(CAST(AY3.AY3_DESCEC AS BINARY) AS VARCHAR) CARDESC, 
AY3.AY3_STATUS,AY3.R_E_C_N_O_ RECNOAY3, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_SUBCAT = AYV.AYV_CAT1 AND AY1.D_E_L_E_T_ = '' ) CATNV1, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT1 AND AY1.AY1_SUBCAT = AYV.AYV_CAT2 AND AY1.D_E_L_E_T_ = '' ) CATNV2, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT2 AND AY1.AY1_SUBCAT = AYV.AYV_CAT3 AND AY1.D_E_L_E_T_ = '' ) CATNV3, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT3 AND AY1.AY1_SUBCAT = AYV.AYV_CAT4 AND AY1.D_E_L_E_T_ = '' ) CATNV4, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT4 AND AY1.AY1_SUBCAT = AYV.AYV_CAT5 AND AY1.D_E_L_E_T_ = '' ) CATNV5, 
AYV.AYV_COD 
FROM 
AY3010 AY3 
INNER JOIN AY5010 AY5 ON AY5.AY5_FILIAL = '' AND AY5_CODIGO = AY3.AY3_CODIGO AND AY5.D_E_L_E_T_ = '' 
INNER JOIN AYV010 AYV ON AYV.AYV_FILIAL = '' AND AYV.AYV_COD = AY5.AY5_CODPRO AND AYV.AYV_USAECO = '1' AND AYV.AYV_ENVECO = '2' AND AYV.AYV_STATEC = '1' AND AYV.D_E_L_E_T_ = '' 
WHERE 
AY3.AY3_STATEC IN('0','2') AND 
AY3.AY3_ENVECO = '1' AND 
AY3.D_E_L_E_T_ = '' 
ORDER BY AY3.AY3_CODIGO 