SELECT 
	RTRIM(B2.B2_FILIAL) codigoFilial,
	RTRIM(B2.B2_COD) codigoErp,
	RTRIM(B2.B2_LOCAL) armazem,
	CASE 
		WHEN B2.B2_QATU - B2.B2_QPEDVEN - B2.B2_RESERVA < 0 THEN 0
		ELSE 
			ROUND(B2.B2_QATU - B2.B2_QPEDVEN - B2.B2_RESERVA,2)
	END saldoAtual
FROM 
	SB2050 B2 
	INNER JOIN SB1050 B1 ON B1.B1_FILIAL = '' AND B1.B1_COD = B2.B2_COD AND B1.B1_MSBLQL <> '1' AND B1.D_E_L_E_T_ = ''
WHERE 
	B2.B2_FILIAL <> '' AND
	B2.B2_LOCAL = '01' AND 
	B2.B2_COD <> '' AND 
	B2.B2_QATU - B2.B2_QPEDVEN - B2.B2_RESERVA > 0 AND
	B2.D_E_L_E_T_ = ''
ORDER BY B2_FILIAL,B2_COD 
FOR XML PATH('produto'), ROOT('produtos')


