SELECT 
	PRODUTO,
	DOCUMENTO,
	SERIE,
	LOTENOTA,
	LOTEETQ
FROM
(
	SELECT 
		D2.D2_COD PRODUTO,
		D2.D2_DOC DOCUMENTO,
		D2.D2_SERIE SERIE,
		D2.D2_LOTECTL LOTENOTA,
		ISNULL(ZZA.ZZA_NUMLOT,'') LOTEETQ
	FROM 
		SD2030 D2 
		LEFT OUTER JOIN ZZA030 ZZA ON ZZA.ZZA_NUMLOT = D2.D2_LOTECTL AND ZZA.D_E_L_E_T_ = '' 
	WHERE 
		D2.D2_LOTECTL <> '' AND
		D2.D_E_L_E_T_ = ''
) LOTES
WHERE 
LOTEETQ = ''
GROUP BY PRODUTO,DOCUMENTO,SERIE,LOTENOTA,LOTEETQ