SELECT 
	FT.FT_FILIAL, 
	FT.FT_NFISCAL,
	FT.FT_SERIE,
	CASE
		WHEN FT.FT_TIPOMOV = 'S' THEN 
			'SAIDA'
		ELSE
			'ENTRADA' 
	END TIPO_MOV,
	FT.FT_PRODUTO, 
	B1.B1_DESC, 
	FT.FT_QUANT,
	FT.FT_CLASFIS,
	B1.B1_POSIPI,
	FT.FT_CFOP,
	FT.FT_VALCONT,
	FT.FT_BASEICM,
	FT.FT_VALICM,
	FT.FT_VALIPI,
	D2.D2_LOTECTL,  
	D2.D2_DTVALID, 
	B8.B8_DATA, 
	CASE 
		WHEN B1.B1_ORIGEM = '0' THEN 
			'    ' 
		WHEN B8.B8_DATA <= '20191130' THEN 
			'POLO' 
		WHEN B8.B8_DATA >= '20191201' THEN  
			'TTD' 
	END STATUS_LOTE, 
	COALESCE(W6.W6_DI_NUM,'') W6_DI_NUM,
	COALESCE(W6.W6_NF_ENT,'') W6_NF_ENT,
	COALESCE(W6.W6_SE_NF,'') W6_SE_NF
 FROM 
	SFT040 FT WITH(NOLOCK)
	INNER JOIN SB1040 B1 WITH(NOLOCK) ON  
		B1.B1_FILIAL = '' AND 
		B1.B1_COD = FT.FT_PRODUTO AND 
		B1.D_E_L_E_T_ = '' 
	INNER JOIN SD2040 D2 WITH(NOLOCK) ON  
		D2.D2_FILIAL = FT.FT_FILIAL AND  
		D2.D2_DOC = FT.FT_NFISCAL AND 
		D2.D2_SERIE = FT.FT_SERIE AND 
		D2.D2_CLIENTE = FT.FT_CLIEFOR AND 
		D2.D2_LOJA = FT.FT_LOJA AND 
		D2.D2_COD = FT.FT_PRODUTO AND 
		D2.D2_ITEM = FT.FT_ITEM AND 
		D2.D2_LOTECTL <> '' AND  
		D2.D_E_L_E_T_ = '' 
	OUTER APPLY( 
				SELECT 
					TOP 1 
					COALESCE(D1.D1_CONHEC,'') D1_CONHEC 
				FROM 
					SD5040 D5 WITH(NOLOCK)
					LEFT JOIN SD5040 D5A WITH(NOLOCK) ON 
						D5A.D5_FILIAL = D5.D5_FILIAL AND 
						D5A.D5_NUMSEQ = D5.D5_NUMSEQ AND 
						D5A.D5_PRODUTO = D5.D5_PRODUTO AND 
						D5A.D5_ORIGLAN = '999' AND 
						D5A.D_E_L_E_T_ = ''
					LEFT JOIN SD1040 D1 WITH(NOLOCK) ON 
						D1.D1_FILIAL = D5A.D5_FILIAL AND 
						D1.D1_COD = D5A.D5_PRODUTO AND 
						D1.D1_LOTECTL = D5A.D5_LOTECTL AND 
						D1.D_E_L_E_T_ = '' 
				WHERE 
					D5.D5_FILIAL = D2.D2_FILIAL AND 
					D5.D5_PRODUTO = D2.D2_COD AND 
					D5.D5_LOTECTL = D2.D2_LOTECTL AND
					D5.D5_ORIGLAN = '499' AND 
					D5.D5_SERIE = '' AND 
					D5.D_E_L_E_T_ = '' 
				ORDER BY D5.D5_DATA ASC 
			) LOTEDI 
	LEFT JOIN SW6040 W6 WITH(NOLOCK) ON  
		W6.W6_FILIAL = FT.FT_FILIAL AND 
		W6.W6_HAWB = LOTEDI.D1_CONHEC AND 
		W6.D_E_L_E_T_ = '' 
	INNER JOIN SB8040 B8 WITH(NOLOCK) ON 
		B8.B8_FILIAL = D2.D2_FILIAL AND 
		B8.B8_PRODUTO = D2.D2_COD AND 
		B8.B8_LOTECTL = D2.D2_LOTECTL AND 
		B8.B8_LOCAL = D2.D2_LOCAL AND 
		B8.D_E_L_E_T_ = '' 
 WHERE 
	FT.FT_FILIAL BETWEEN '0404' AND '0404' AND  
	FT.FT_NFISCAL BETWEEN '' AND 'ZZZZZZZZZ' AND 
	FT.FT_SERIE BETWEEN '   ' AND 'ZZZ' AND 
	FT.FT_EMISSAO BETWEEN '20200201' AND '20200228' AND  
	FT.FT_PRODUTO BETWEEN '' AND 'ZZZZZZZZZZZZZZ' AND 
	FT.FT_DTCANC = '' AND 
	FT.FT_TIPOMOV = 'S' AND 
	FT.D_E_L_E_T_ = '' 
 GROUP BY FT.FT_FILIAL, FT.FT_NFISCAL, FT.FT_SERIE, FT.FT_TIPOMOV, FT.FT_PRODUTO, B1.B1_DESC, FT.FT_QUANT, FT.FT_CLASFIS,	B1.B1_POSIPI, FT.FT_CFOP, FT.FT_VALCONT, FT.FT_BASEICM, FT.FT_VALICM, FT.FT_VALIPI, D2.D2_LOTECTL, D2.D2_DTVALID, B8.B8_DATA, B1.B1_ORIGEM, FT.FT_VALCONT, FT.FT_BASEICM, FT.FT_VALICM, W6.W6_DI_NUM , W6.W6_NF_ENT, W6.W6_SE_NF
 ORDER BY FT.FT_FILIAL, FT.FT_PRODUTO


/*
SELECT 
	D5.D5_NUMSEQ,
	D5A.*,
	COALESCE(D1.D1_CONHEC,'') D1_CONHEC 
FROM 
	SD5040 D5 WITH(NOLOCK)
	LEFT JOIN SD5040 D5A WITH(NOLOCK) ON 
	D5A.D5_FILIAL = D5.D5_FILIAL AND 
	D5A.D5_NUMSEQ = D5.D5_NUMSEQ AND 
	D5A.D5_PRODUTO = D5.D5_PRODUTO AND 
	D5A.D5_ORIGLAN = '999' AND 
	D5A.D_E_L_E_T_ = ''
	LEFT JOIN SD1040 D1 WITH(NOLOCK) ON 
	D1.D1_FILIAL = D5A.D5_FILIAL AND 
	D1.D1_COD = D5A.D5_PRODUTO AND 
	D1.D1_LOTECTL = D5A.D5_LOTECTL AND 
	D1.D_E_L_E_T_ = '' 
WHERE 
	D5.D5_FILIAL = '0404' AND 
	D5.D5_PRODUTO = '58' AND 
	D5.D5_LOTECTL = '01119121' AND
	D5.D5_ORIGLAN = '499' AND 
	D5.D5_SERIE = '' AND 
	D5.D_E_L_E_T_ = '' 
ORDER BY D5.D5_DATA ASC 
*/




