SELECT  
 	PRODUTO,   
 	GRUPO,  
     TABELA,  
	    CUSTUMER_GRUPO,  
 	PRECO  
 FROM  
 (  
 	SELECT  
 		PRODUTO,  
     		COALESCE([000],0) AS VISITANTES,  
     		COALESCE([001],0) AS COMUM,  
     		COALESCE([002],0) AS REVENDA_SP,  
     		COALESCE([003],0) AS FINAL_PJ,  
     		COALESCE([004],0) AS REV_N_NO,  
     		COALESCE([005],0) AS REV_S_SE,  
     		COALESCE([006],0) AS REV_VET_SP,  
     		COALESCE([007],0) AS FINAL_VET,  
     		COALESCE([008],0) AS REV_VET_N_NE_CO,  
     		COALESCE([009],0) AS REV_VET_S_SE,  
     		COALESCE([010],0) AS REV_VET_RJ,  
     		COALESCE([012],0) AS FINAL_PF,  
     		COALESCE([013],0) AS FINAL_PS,  
     		COALESCE([014],0) AS FUNCIONARIOS,  
             CODTABELA TABELA,  
     		DESC_GRUPO CUSTUMER_GRUPO  
     FROM  
 	(  
 		SELECT  
 			DA1.DA1_CODPRO PRODUTO,  
 			GRUPO.value GRUPO,  
             DA0.DA0_CODTAB CODTABELA,  
 			CAST(CAST( ZZ6.ZZ6_DESCEC AS BINARY) AS VARCHAR(1028)) DESC_GRUPO,  
 			MAX(DA1.DA1_PRCVEN) QUANTIDADE  
 		FROM  
	    		DA0040 DA0   
	    		INNER JOIN DA1040 DA1 ON DA1.DA1_FILIAL = DA0.DA0_FILIAL AND DA1.DA1_CODTAB = DA0.DA0_CODTAB AND DA1.DA1_PRCVEN > 0 AND DA1.D_E_L_E_T_ = ''  
	    		CROSS APPLY STRING_SPLIT(DA0.DA0_XGRPPR,',') GRUPO  
             INNER JOIN ZZ6040 ZZ6 ON ZZ6.ZZ6_FILIAL = '    ' AND ZZ6.ZZ6_CODIGO = GRUPO.value AND ZZ6.D_E_L_E_T_ = '' 
 		WHERE  
             DA0.DA0_FILIAL = '0404' AND 
 			DA0.DA0_XGRPPR <> '' AND 
 			DA0.DA0_ENVECO = '1' AND 
 			DA0.D_E_L_E_T_ = '' 
	    	GROUP BY DA0.DA0_XGRPPR,DA1.DA1_CODPRO,DA1.DA1_PRCVEN,GRUPO.value,DA0.DA0_CODTAB,ZZ6.ZZ6_DESCEC  
 	) GRUPO_CLIENTES  
	PIVOT ( MAX(QUANTIDADE)  
	FOR GRUPO IN([000],[001],[002],[003],[004],[005],[006],[007],[008],[009],[010],[012],[013],[014]) ) PIVOTTABLE  
 ) GRUPO_CLIENTES_LINHA  
 UNPIVOT (PRECO FOR GRUPO IN(VISITANTES,COMUM,REVENDA_SP,FINAL_PJ,REV_N_NO,REV_S_SE,REV_VET_SP,FINAL_VET,REV_VET_N_NE_CO,REV_VET_S_SE,REV_VET_RJ,FINAL_PF,FINAL_PS,FUNCIONARIOS)) UNPIVOTTABLE  
 WHERE PRECO > 0  
 ORDER BY PRODUTO
 
 /*

 UPDATE DA0040 SET DA0_ENVECO = '1' 
 WHERE 
 DA0_FILIAL = '0404' AND 
 DA0_XGRPPR <> '' AND 
 D_E_L_E_T_ = ''
 
 */