SELECT 
	CODIGO_SKU, 
	DESC_SKU, 
	ID_SKU, 
	PER_IPI, 
	PRECO_DE, 
	CODIGO_TABELA, 
	ITEM_TABELA, 
	RECNODA1 
FROM 
( 
	SELECT 
		B5.B5_COD CODIGO_SKU, 
		B1.B1_DESC DESC_SKU, 
		B5.B5_XIDSKU ID_SKU, 
		B1.B1_IPI PER_IPI, 
		DA1.DA1_PRCVEN PRECO_DE, 
		DA1.DA1_CODTAB CODIGO_TABELA, 
		DA1.DA1_ITEM ITEM_TABELA, 
		DA1.R_E_C_N_O_ RECNODA1 
	FROM 
		DA1040 DA1 
		INNER JOIN SB1040 B1 ON B1.B1_FILIAL = '    ' AND B1.B1_COD = DA1.DA1_CODPRO AND B1.B1_MSBLQL <> '1' AND B1.D_E_L_E_T_ = '' 
		INNER JOIN SB5040 B5 ON B5.B5_FILIAL = '    ' AND B5.B5_COD = DA1.DA1_CODPRO AND B5.B5_XIDSKU > 0 AND B5.D_E_L_E_T_ = ''     
WHERE 
		DA1.DA1_FILIAL = '0404' AND  
		DA1.DA1_CODTAB = '002' AND 
		DA1.DA1_PRCVEN > 0 AND 
		DA1.DA1_ENVECO = '1'  AND 
	  	DA1.D_E_L_E_T_ = '' 
	UNION ALL 
	SELECT 
		WS6.WS6_CODSKU CODIGO_SKU, 
		B1.B1_DESC DESC_SKU, 
		B1.B1_XIDSKU ID_SKU, 
		B1.B1_IPI PER_IPI, 
		DA1.DA1_PRCVEN PRECO_DE, 
		DA1.DA1_CODTAB CODIGO_TABELA, 
		DA1.DA1_ITEM ITEM_TABELA, 
		DA1.R_E_C_N_O_ RECNODA1 
	FROM 
		DA1040 DA1 
		INNER JOIN WS6040 WS6 ON WS6.WS6_FILIAL = '    ' AND WS6.WS6_CODSKU = DA1.DA1_CODPRO AND WS6.D_E_L_E_T_ = '' 
		INNER JOIN WS5040 WS5 ON WS5.WS5_FILIAL = '    ' AND WS5.WS5_CODPRD = WS6.WS6_CODPRD AND WS5.WS5_USAECO = 'S' AND WS5.D_E_L_E_T_ = ''  
		INNER JOIN SB1040 B1 ON B1.B1_FILIAL = '    ' AND B1.B1_COD = WS6.WS6_CODSKU AND B1.B1_XIDSKU > 0 AND B1.B1_MSBLQL <> '1' AND B1.D_E_L_E_T_ = '' 
	WHERE 
		DA1.DA1_FILIAL = '0404' AND  
		DA1.DA1_CODTAB = '002' AND 
		DA1.DA1_PRCVEN > 0 AND 
		DA1.DA1_ENVECO = '1' AND  
		DA1.D_E_L_E_T_ = '' 
)PRECOS_SKU 
ORDER BY CODIGO_SKU 