-- INFORMACOES REPRESENTANTES
SELECT 
	TOP(10) RNUM,
	ITEM_ID,
	NAME,
	EMAIL,
	DDD,
	TELEPHONE,
	CELLPHONE,
	PHOTO_LINK 
FROM 
(
	SELECT 
		ROW_NUMBER() OVER(ORDER BY A3.A3_COD) RNUM,
		A3.A3_COD ITEM_ID,
		A3.A3_NOME NAME,
		A3.A3_EMAIL EMAIL,
		A3.A3_DDDTEL DDD,
		A3.A3_TEL TELEPHONE,
		A3.A3_CEL CELLPHONE,
		'' PHOTO_LINK 
	FROM 
		SA3040 A3 WITH(NOLOCK)
	WHERE 
		A3.A3_CGC <> '' AND 
		A3.A3_MSBLQL <> '1' AND 
		A3.D_E_L_E_T_ = ''
)REPRESENTANTES
WHERE 
	RNUM > 10 * (10 - 1)