-- AREA DO CLIENTE - PEDIDOS 
-- TOTAL DE REGISTROS 
/*
SELECT
	COUNT(C5_NUM) TOTAL
FROM 
	SC5040 C5 WITH(NOLOCK)
	INNER JOIN SA1040 A1 WITH(NOLOCK) ON A1.A1_FILIAL = '' AND A1.A1_CGC = '54705371000106' AND A1.D_E_L_E_T_ = ''
WHERE 
	C5.C5_CLIENTE = A1.A1_COD AND 
	C5.C5_LOJACLI = A1.A1_LOJA AND 
	C5.C5_TIPO = 'N' AND 
	C5.D_E_L_E_T_ = ''
*/
-- DADOS PEDIDO CABEÇALHO 
SELECT
	TOP(10) RNUM, 
	INTERNAL_ID,
	SITE_ID,
	CREATED_AT,
	TOTAL_AMOUNT,
	SHIPPING_AMOUNT,
	DISCOUNT_AMOUNT,
	CHAVE_NFE,
	STATUS_PEDIDO,
	PREFIXO,
	DOC
FROM 
(
	SELECT
		ROW_NUMBER() OVER(ORDER BY C5_EMISSAO DESC) RNUM,
		C5.C5_NUM INTERNAL_ID,
		C5.C5_XNUMECL SITE_ID,
		C5.C5_EMISSAO CREATED_AT,
		CASE WHEN F2.F2_VALBRUT <> '' THEN F2.F2_VALBRUT ELSE C5.C5_XVALOR END TOTAL_AMOUNT,
		CASE WHEN F2.F2_FRETE <> '' THEN F2.F2_FRETE ELSE C5.C5_FRETE END SHIPPING_AMOUNT,
		CASE WHEN DESCONTO_NOTA.D2_DESC <> '' THEN DESCONTO_NOTA.D2_DESC ELSE DESCONTO_PEDIDO.C6_VALDESC END DISCOUNT_AMOUNT,
		COALESCE(F2.F2_CHVNFE,'') CHAVE_NFE,
		COALESCE(STATUS_PEDIDO.Z04_DESC,'') STATUS_PEDIDO,
		COALESCE(F2.F2_SERIE,'') PREFIXO,
		COALESCE(F2.F2_DOC,'') DOC
	FROM 
		SC5040 C5 WITH(NOLOCK)
		INNER JOIN SA1040 A1 WITH(NOLOCK) ON A1.A1_FILIAL = '' AND A1.A1_CGC = '54705371000106' AND A1.D_E_L_E_T_ = ''
		LEFT JOIN SF2040 F2 WITH(NOLOCK) ON F2.F2_FILIAL = C5.C5_FILIAL AND F2.F2_DOC = C5.C5_NOTA AND F2.F2_SERIE = C5.C5_SERIE AND F2.D_E_L_E_T_ = ''
		OUTER APPLY(
					SELECT 
						TOP 1
						Z04.Z04_DESC
					FROM 
						Z05040 Z05 
						INNER JOIN Z04040 Z04 ON Z04.Z04_FILIAL = '' AND Z04.Z04_COD = Z05.Z05_STATUS AND Z04.D_E_L_E_T_ = ''
					WHERE 
						Z05.Z05_FILIAL = '0404' AND 
						Z05.Z05_PEDIDO = C5.C5_NUM AND 
						Z05.D_E_L_E_T_ = ''
					--GROUP BY Z05.Z05_PEDIDO,Z04.Z04_DESC
					ORDER BY Z05.Z05_DATA DESC
		)STATUS_PEDIDO
		OUTER APPLY(
					SELECT
						SUM(D2.D2_DESC) D2_DESC 
					FROM 
						SD2040 D2 WITH(NOLOCK)
					WHERE 
						D2.D2_FILIAL = F2.F2_FILIAL AND 
						D2.D2_DOC = F2.F2_DOC AND 
						D2.D2_SERIE = F2.F2_SERIE AND 
						D2.D_E_L_E_T_ = ''
		)DESCONTO_NOTA 
		OUTER APPLY(
					SELECT
						SUM(C6.C6_VALDESC) C6_VALDESC 
					FROM 
						SC6040 C6 WITH(NOLOCK)
					WHERE 
						C6.C6_FILIAL = C5.C5_FILIAL AND 
						C6.C6_NUM = C5.C5_NUM AND 
						C6.D_E_L_E_T_ = ''
		)DESCONTO_PEDIDO
	WHERE 
		C5.C5_CLIENTE = A1.A1_COD AND 
		C5.C5_LOJACLI = A1.A1_LOJA AND
		C5.C5_TIPO = 'N' AND 
		C5.D_E_L_E_T_ = ''
)PEDIDOS
WHERE RNUM > 10 * ( 1 - 1 ) 

--SELECT * FROM Z05040 WHERE Z05_PEDIDO = '284174' AND D_E_L_E_T_ = '' ORDER BY Z05_DATA,Z05_HORA




--SELECT * FROM Z04040 WHERE D_E_L_E_T_ = ''
