SELECT
	C5.C5_FILIAL FILIAL,
	C5.C5_NUM INTERNAL_ID,
	C5.C5_XNUMECO SITE_ID,
	C5.C5_EMISSAO CREATE_DATA,
	CASE 
		WHEN COALESCE(F2.F2_VALBRUT,0) > 0 THEN 
			F2.F2_VALBRUT
		ELSE 
			C5.C5_XVALOR
	END AMOUNT,
	C5.C5_FECENT DELIVERY_TIME,
	STATUS_PEDIDO.Z04_DESC STATUS,
	COALESCE(F2.F2_CHVNFE,'') NFE_LINK,
	F2.F2_DOC DOC,
	F2.F2_SERIE PREFIXO,
	E4.E4_FORMA METHOD_PAY,
	E4.E4_CODIGO + ' - ' + E4.E4_DESCRI ADDITIONAL_INFO,
	A1.A1_NOME NAME,
	A1.A1_CGC DOCUMENT,
	A1.A1_EMLCONT EMAIL_CONTATO,
	A1.A1_EMAIL EMAIL,
	A1.A1_ECOMPRA EMAIL_COMPRA,
	A1.A1_EMLINFO EMAIL_INFO,
	A1.A1_EMLVEND EMAIL_VEND,
	A1.A1_DDD DDD,
	A1.A1_TEL TEL,
	A1.A1_TEL2 TEL_2,
	A1.A1_END ENDERECO,
	A1.A1_BAIRRO BAIRRO,
	A1.A1_MUN MUNICIPIO,
	A1.A1_EST ESTADO,
	A1.A1_CEP CEP,
	CASE WHEN END_ENTREGA.WSC_ENDENT <> '' THEN END_ENTREGA.WSC_ENDENT ELSE SUBSTRING(A1.A1_ENDENT,1,CHARINDEX(',',A1.A1_ENDENT)-1) END END_ENTREGA,
	CASE WHEN END_ENTREGA.WSC_ENDNUM <> '' THEN END_ENTREGA.WSC_ENDNUM ELSE SUBSTRING(A1.A1_ENDENT,CHARINDEX(',',A1.A1_ENDENT)+1,6) END NUMEND_ENTREGA,
	CASE WHEN END_ENTREGA.WSC_BAIRRE <> '' THEN END_ENTREGA.WSC_BAIRRE ELSE A1.A1_BAIRROE END BAI_ENTREGA,
	CASE WHEN END_ENTREGA.WSC_MUNE <> '' THEN END_ENTREGA.WSC_MUNE ELSE A1.A1_MUNE END MUN_ENTREGA,
	CASE WHEN END_ENTREGA.WSC_CEPE <> '' THEN END_ENTREGA.WSC_CEPE ELSE A1.A1_CEPE END CEP_ENTREGA,
	CASE WHEN END_ENTREGA.WSC_ESTE <> '' THEN END_ENTREGA.WSC_ESTE ELSE A1.A1_ESTE END EST_ENTREGA,
	CASE WHEN END_ENTREGA.WSC_COMPLE <> '' THEN END_ENTREGA.WSC_COMPLE ELSE '' END COMP_ENTREGA,
	A1.A1_ENDCOB END_COBRANCA,
	A1.A1_BAIRROC BAI_COBRANCA,
	A1.A1_MUNC MUN_COBRANCA,
	A1.A1_CEPC CEP_COBRANCA,
	A1.A1_ESTC EST_COBRANCA
FROM 
	SC5040 C5 WITH(NOLOCK)
	INNER JOIN SA1040 A1 WITH(NOLOCK) ON A1.A1_FILIAL = '' AND A1.A1_COD = C5.C5_CLIENTE AND A1.A1_LOJA = C5.C5_LOJACLI AND A1.D_E_L_E_T_ = ''
	INNER JOIN SA4040 A4 WITH(NOLOCK) ON A4.A4_FILIAL = '' AND A4.A4_COD = C5.C5_TRANSP AND A4.D_E_L_E_T_ = ''
	LEFT JOIN SF2040 F2 WITH(NOLOCK) ON F2.F2_FILIAL = C5.C5_FILIAL AND F2.F2_DOC = C5.C5_NOTA AND F2.F2_SERIE = C5.C5_SERIE AND F2.D_E_L_E_T_ = ''
	INNER JOIN SE4040 E4 WITH(NOLOCK) ON E4.E4_FILIAL = '' AND E4.E4_CODIGO = C5.C5_CONDPAG AND E4.D_E_L_E_T_ = ''
	OUTER APPLY(
				SELECT 
					TOP 1
					Z04.Z04_DESC
				FROM 
					Z05040 Z05 
					INNER JOIN Z04040 Z04 ON Z04.Z04_FILIAL = '' AND Z04.Z04_COD = Z05.Z05_STATUS AND Z04.D_E_L_E_T_ = ''
				WHERE 
					Z05.Z05_FILIAL = '0404' AND 
					Z05.Z05_PEDIDO = C5.C5_NUM AND 
					Z05.D_E_L_E_T_ = ''
				ORDER BY Z05.Z05_DATA DESC
	)STATUS_PEDIDO
	OUTER APPLY(
				SELECT 
					WSC.WSC_NOMDES,
					WSC.WSC_ENDENT,
					WSC.WSC_ENDNUM,
					WSC.WSC_COMPLE,
					WSC.WSC_MUNE,
					WSC.WSC_BAIRRE,
					WSC.WSC_ESTE,
					WSC.WSC_CEPE
				FROM 
					WSC040 WSC 
				WHERE 
					WSC.WSC_FILIAL = '0404' AND 
					WSC.WSC_NUMSC5 = C5.C5_NUM AND 
					WSC.D_E_L_E_T_ = ''
	)END_ENTREGA
WHERE 
	C5.C5_NUM = '266834' AND 
	C5.C5_CLIENTE = '130593' AND 
	C5.C5_LOJACLI = '0001' AND 
	C5.D_E_L_E_T_ = ''


	--SELECT * FROM WSC040 WHERE D_E_L_E_T_ = ''