UPDATE 
	SB4010 
SET 
	B4_XTITULO = B4_XECTITU,
	B4_XSUBTIT = B4_XECSUBT,
	B4_XDESCRI = B4_XECDESC,
	B4_XCARACT = B4_XECCARA,
	B4_XALTEMB = B4_XECALTE,
	B4_XLAREMB = B4_XECLARG,
	B4_XPROEMB = B4_XECPRO2,
	B4_XPRZADI = B4_XECENTR,
	B4_XQTDMAX = B4_XECQTMA,
	B4_XTPPROD = B4_XECTIPO,
	B4_XPRESEN = IIF(B4_XECPRES = '1','S','N'),
	B4_XPERSON = 'N',
	B4_XISBN = B4_XECISBN,
	B4_XEAN13 = B4_XECEAN1,
	B4_XYOUTUB = B4_XECYOUT,
	B4_XESTMIN = B4_XECEMIN
	B4_XENVECO = '1',
	B4_STATUS = 'A' 
WHERE
	D_E_L_E_T_ = ''