-- Cria tabela temporária com os cálculos em USD
SELECT
    PRODUTO,
    SUM(VALOR_TOT_DI) AS TOTAL_USD,
    SUM(VAL_TOT)      AS TOTAL_BRL,
    SUM(VAL_TOT) / NULLIF(SUM(VALOR_TOT_DI), 0) AS TAXA_MEDIA
INTO #TMP_DOLARIZA_ESTOQUE
FROM (
    SELECT
        BJ.BJ_COD AS PRODUTO,
        (W7.W7_PRECO * BJ.BJ_QINI)                 AS VALOR_TOT_DI,
        (W7.W7_PRECO * BJ.BJ_QINI * W6.W6_TX_US_D) AS VAL_TOT
    FROM SBJ010 BJ
    INNER JOIN SB8010 B8
        ON B8.B8_LOTECTL = BJ.BJ_LOTECTL
       AND B8.B8_FILIAL  = BJ.BJ_FILIAL
       AND BJ.BJ_LOCAL   = B8.B8_LOCAL
       AND B8.D_E_L_E_T_ = ''
    LEFT JOIN P90010 P9
        ON P9.P90_LOTE   = B8.B8_LOTECTL
       AND P9.P90_PRODUT = B8.B8_PRODUTO
       AND P9.D_E_L_E_T_ = ''
    LEFT JOIN SD1010 D1
        ON D1.D1_DOC     = P9.P90_DOC
       AND D1.D1_COD     = P9.P90_PRODUT
       AND D1.D1_SERIE   = P9.P90_SERIE
       AND D1.D1_FORNECE = P9.P90_FORNEC
       AND D1.D1_LOJA    = P9.P90_LOJA
       AND D1.D_E_L_E_T_ = ''
    LEFT JOIN SW6010 W6
        ON W6.W6_HAWB    = D1.D1_CONHEC
       AND W6.D_E_L_E_T_ = ''
    LEFT JOIN SW7010 W7
        ON W7.W7_HAWB    = D1.D1_CONHEC
       AND W7.W7_COD_I   = P9.P90_PRODUT
       AND W7.D_E_L_E_T_ = ''
    WHERE
        BJ.BJ_QINI > 0
        AND BJ.BJ_DATA = '20250831'
        AND BJ.D_E_L_E_T_ = ''
) A
WHERE A.VALOR_TOT_DI <> 0
GROUP BY A.PRODUTO;


SELECT * FROM #TMP_DOLARIZA_ESTOQUE