-- ORÇAMENTOS COM PEDIDOS ANALITICO
SELECT 
	PRODUTO,
	SUM(VALOR) VALOR
FROM (
	SELECT 
		FILIAL,
		PRODUTO PRODUTO,
		SUM(VALOR) VALOR
	FROM (
		SELECT
			UB.UB_FILIAL FILIAL,
			UB.UB_PRODUTO PRODUTO,
			UB.UB_VLRITEM VALOR
		FROM 
			SUB040 UB WITH (NOLOCK)
			INNER JOIN SUA040 UA WITH (NOLOCK) ON UA.UA_FILIAL = UB.UB_FILIAL AND UA.UA_NUM = UB.UB_NUM AND UA.UA_NUMSC5 <> '' AND UA.UA_EMISSAO BETWEEN '20190601' AND '20191231' AND UA.D_E_L_E_T_ = ''
			INNER JOIN SA1040 A1 WITH (NOLOCK) ON A1.A1_COD = UA.UA_CLIENTE AND A1.A1_LOJA = UA.UA_LOJA AND A1.D_E_L_E_T_ = ''
		WHERE
			UB.UB_FILIAL IN('0401','0404') AND
			UB.UB_EMISSAO BETWEEN '20190601' AND '20191231' AND 
			UB.D_E_L_E_T_ = ''
	) ANALI_SEMPV
	GROUP BY FILIAL,PRODUTO
) TOTAL_ANALI_SEMPV
GROUP BY PRODUTO

-- ORÇAMENTOS SEM PEDIDOS ANALITICO
SELECT 
	PRODUTO,
	SUM(VALOR) VALOR
FROM (
	SELECT 
		FILIAL,
		PRODUTO PRODUTO,
		SUM(VALOR) VALOR
	FROM (
		SELECT
			UB.UB_FILIAL FILIAL,
			UB.UB_PRODUTO PRODUTO,
			UB.UB_VLRITEM VALOR
		FROM 
			SUB040 UB WITH (NOLOCK)
			INNER JOIN SUA040 UA WITH (NOLOCK) ON UA.UA_FILIAL = UB.UB_FILIAL AND UA.UA_NUM = UB.UB_NUM AND UA.UA_NUMSC5 = '' AND UA.UA_EMISSAO BETWEEN '20190601' AND '20191231' AND UA.D_E_L_E_T_ = ''
			INNER JOIN SA1040 A1 WITH (NOLOCK) ON A1.A1_COD = UA.UA_CLIENTE AND A1.A1_LOJA = UA.UA_LOJA AND A1.D_E_L_E_T_ = ''
		WHERE
			UB.UB_FILIAL IN('0401','0404') AND
			UB.UB_EMISSAO BETWEEN '20190601' AND '20191231' AND 
			UB.D_E_L_E_T_ = ''
	) ANALI_SEMPV
	GROUP BY FILIAL,PRODUTO
) TOTAL_ANALI_SEMPV
GROUP BY PRODUTO

-- ORÇAMENTOS COM PEDIDOS SINTETICO 
SELECT 
	TIPOCLI,
	SUM(VALOR) VALOR
FROM (
	SELECT 
		FILIAL,
		NUM,
		TIPOCLI TIPOCLI,
		SUM(VALOR) VALOR
	FROM (
		SELECT
			UA.UA_FILIAL FILIAL,
			UA.UA_NUM NUM,
			A1.A1_TIPO TIPOCLI,
			UB.UB_VLRITEM VALOR
		FROM 
			SUB040 UB WITH (NOLOCK)
			INNER JOIN SUA040 UA WITH (NOLOCK) ON UA.UA_FILIAL = UB.UB_FILIAL AND UA.UA_NUM = UB.UB_NUM AND UA.UA_NUMSC5 <> '' AND UA.UA_EMISSAO BETWEEN '20190601' AND '20191231' AND UA.D_E_L_E_T_ = ''
			INNER JOIN SA1040 A1 WITH (NOLOCK) ON A1.A1_COD = UA.UA_CLIENTE AND A1.A1_LOJA = UA.UA_LOJA AND A1.D_E_L_E_T_ = ''
		WHERE
			UB.UB_FILIAL IN('0401','0404') AND
			UB.UB_EMISSAO BETWEEN '20190601' AND '20191231' AND 
			UB.D_E_L_E_T_ = ''
	) SINT_SEMPV
	GROUP BY FILIAL,NUM,TIPOCLI
) TOTAL_SINT_SEMPV
GROUP BY TIPOCLI

-- ORÇAMENTOS SEM PEDIDOS SINTETICO 
SELECT 
	TIPOCLI,
	SUM(VALOR) VALOR
FROM (
	SELECT 
		FILIAL,
		NUM,
		TIPOCLI TIPOCLI,
		SUM(VALOR) VALOR
	FROM (
		SELECT
			UA.UA_FILIAL FILIAL,
			UA.UA_NUM NUM,
			A1.A1_TIPO TIPOCLI,
			UB.UB_VLRITEM VALOR
		FROM 
			SUB040 UB WITH (NOLOCK)
			INNER JOIN SUA040 UA WITH (NOLOCK) ON UA.UA_FILIAL = UB.UB_FILIAL AND UA.UA_NUM = UB.UB_NUM AND UA.UA_NUMSC5 = '' AND UA.UA_EMISSAO BETWEEN '20190601' AND '20191231' AND UA.D_E_L_E_T_ = ''
			INNER JOIN SA1040 A1 WITH (NOLOCK) ON A1.A1_COD = UA.UA_CLIENTE AND A1.A1_LOJA = UA.UA_LOJA AND A1.D_E_L_E_T_ = ''
		WHERE
			UB.UB_FILIAL IN('0401','0404') AND
			UB.UB_EMISSAO BETWEEN '20190601' AND '20191231' AND 
			UB.D_E_L_E_T_ = ''
	) SINT_SEMPV
	GROUP BY FILIAL,NUM,TIPOCLI
) TOTAL_SINT_SEMPV
GROUP BY TIPOCLI

