WITH META_MENSAL_ANUAL AS (
	SELECT 
		CT.CT_VEND,
		SUM(CT.CT_VALOR) AS TOTAL_META
	FROM 
		SCT040 CT WITH(NOLOCK)
	WHERE 
		CT.CT_FILIAL = '' 
		AND CT.CT_DATA BETWEEN '20240101' AND '20241231'
		AND CT.D_E_L_E_T_ = ''
	GROUP BY 
		CT.CT_VEND
)
SELECT 
	A3.A3_COD AS VENDEDOR,
	A3.A3_NOME AS NOME,
	ISNULL(MM.TOTAL_META, 0) AS TOTAL_META,
	SUM(
		CASE	
			WHEN FT.FT_NATOPER IN ('008','041','043') THEN FT.FT_TOTAL
			WHEN FT.FT_NATOPER = '012' THEN -1 * FT.FT_TOTAL
			ELSE 0
		END
	) AS TOTAL_FATURADO,
	ROUND(
		CASE 
			WHEN ISNULL(MM.TOTAL_META, 0) = 0 THEN 0
			ELSE (SUM(
				CASE 
					WHEN FT.FT_NATOPER IN ('008','041','043') THEN FT.FT_TOTAL
					WHEN FT.FT_NATOPER = '012' THEN -1 * FT.FT_TOTAL
					ELSE 0
				END
			) / MM.TOTAL_META) * 100
		END, 2
	) AS PERCENTUAL_ATINGIDO
FROM 
	SFT040 FT WITH (NOLOCK)
	LEFT JOIN SF2040 F2 WITH(NOLOCK)
		ON F2.F2_FILIAL = FT.FT_FILIAL 
		AND F2.F2_DOC + F2.F2_SERIE = 
			CASE 
				WHEN FT.FT_NFORI = '' THEN FT.FT_NFISCAL + FT.FT_SERIE 
				ELSE FT.FT_NFORI + FT.FT_SERORI 
			END 
		AND F2.D_E_L_E_T_ = ''
	LEFT JOIN SA3040 A3 WITH(NOLOCK)
		ON A3.A3_FILIAL = '' 
		AND A3.A3_COD = F2.F2_VEND1 
		AND A3.A3_COD NOT IN ('000033','000333') 
		AND A3.A3_TIPO = 'I' 
		AND A3.A3_MSBLQL <> '1' 
		AND A3.D_E_L_E_T_ = ''
	LEFT JOIN META_MENSAL_ANUAL MM ON MM.CT_VEND = A3.A3_COD
WHERE 
	FT.FT_ENTRADA BETWEEN '20240101' AND '20241231'
	AND FT.FT_DTCANC = ''
	AND FT.FT_NATOPER IN ('008','012','041','043')
	AND FT.D_E_L_E_T_ = ''
	AND A3.A3_COD IS NOT NULL
GROUP BY 
	A3.A3_COD, A3.A3_NOME, MM.TOTAL_META
ORDER BY 
	TOTAL_FATURADO DESC;


--SELECT * FROM SCT040 WHERE CT_FILIAL = '' AND CT_VEND = '000015' AND CT_DATA BETWEEN '20250101' AND '20250731' AND D_E_L_E_T_ = ''