WITH META_MENSAL AS (
	SELECT 
		CT.CT_VEND,
		SUM(CT.CT_VALOR) AS TOTAL_META
	FROM SCT040 CT WITH(NOLOCK)
	WHERE 
		CT.CT_FILIAL = '' 
		AND CT.CT_DATA BETWEEN '20250101' AND '20251231'
		AND CT.D_E_L_E_T_ = ''
	GROUP BY 
		CT.CT_VEND
),
FATURAMENTO AS (
	SELECT 
		F2.F2_VEND1 AS VENDEDOR,
		SUM(
			CASE	
				WHEN FT.FT_NATOPER IN ('008','041','043') THEN FT.FT_TOTAL
				WHEN FT.FT_NATOPER = '012' THEN -1 * FT.FT_TOTAL
				ELSE 0
			END
		) AS TOTAL_FATURADO
	FROM SFT040 FT WITH(NOLOCK)
	INNER JOIN SF2040 F2 WITH(NOLOCK)
		ON F2.F2_FILIAL = FT.FT_FILIAL 
		AND F2.F2_DOC + F2.F2_SERIE = 
			CASE 
				WHEN FT.FT_NFORI = '' THEN FT.FT_NFISCAL + FT.FT_SERIE 
				ELSE FT.FT_NFORI + FT.FT_SERORI 
			END 
		AND F2.D_E_L_E_T_ = ''
	INNER JOIN SA3040 A3 WITH(NOLOCK)
		ON A3.A3_FILIAL = '' 
		AND A3.A3_COD = F2.F2_VEND1 
		AND A3.A3_COD NOT IN ('000033','000333') 
		AND A3.A3_TIPO = 'I' 
		AND A3.A3_MSBLQL <> '1' 
		AND A3.D_E_L_E_T_ = ''
	WHERE 
		FT.FT_ENTRADA BETWEEN '20250101' AND '20251231'
		AND FT.FT_DTCANC = ''
		AND FT.FT_NATOPER IN ('008','012','041','043')
		AND FT.D_E_L_E_T_ = ''
	GROUP BY 
		F2.F2_VEND1
)
SELECT 
	SUM(ISNULL(MM.TOTAL_META, 0)) AS TOTAL_META_GERAL,
	SUM(ISNULL(F.TOTAL_FATURADO, 0)) AS TOTAL_FATURADO_GERAL,
	ROUND(
		CASE 
			WHEN SUM(ISNULL(MM.TOTAL_META, 0)) = 0 THEN 0
			ELSE (SUM(ISNULL(F.TOTAL_FATURADO, 0)) / SUM(ISNULL(MM.TOTAL_META, 0))) * 100
		END, 2
	) AS PERCENTUAL_ATINGIDO_GERAL
FROM 
	FATURAMENTO F
LEFT JOIN META_MENSAL MM ON MM.CT_VEND = F.VENDEDOR;
