	SELECT 
		FILIAL, 
		SUM(COALESCE([01_QTD],0)) JANEIRO_QTD,
		SUM(COALESCE([01_VLR],0)) JANEIRO_VALOR,
		SUM(COALESCE([02_QTD],0)) FEVEREIRO_QTD,
		SUM(COALESCE([02_VLR],0)) FEVEREIRO_VALOR,
		SUM(COALESCE([03_QTD],0)) MARÇO_QTD,
		SUM(COALESCE([03_VLR],0)) MARÇO_VALOR,
		SUM(COALESCE([04_QTD],0)) ABRIL_QTD,
		SUM(COALESCE([04_VLR],0)) ABRIL_VALOR,
		SUM(COALESCE([05_QTD],0)) MAIO_QTD,
		SUM(COALESCE([05_VLR],0)) MAIO_VALOR,
		SUM(COALESCE([06_QTD],0)) JUNHO_QTD,
		SUM(COALESCE([06_VLR],0)) JUNHO_VALOR,
		SUM(COALESCE([07_QTD],0)) JULHO_QTD,
		SUM(COALESCE([07_VLR],0)) JULHO_VALOR,
		SUM(COALESCE([08_QTD],0)) AGOSTO_QTD,
		SUM(COALESCE([08_VLR],0)) AGOSTO_VALOR,
		SUM(COALESCE([09_QTD],0)) SETEMBRO_QTD,
		SUM(COALESCE([09_VLR],0)) SETEMBRO_VALOR,
		SUM(COALESCE([10_QTD],0)) OUTUBRO_QTD,
		SUM(COALESCE([10_VLR],0)) OUTUBRO_VALOR,
		SUM(COALESCE([11_QTD],0)) NOVEMBRO_QTD,
		SUM(COALESCE([11_VLR],0)) NOVEMBRO_VALOR,
		SUM(COALESCE([12_QTD],0)) DEZEMBRO_QTD,
		SUM(COALESCE([12_VLR],0)) DEZEMBRO_VALOR
	FROM 
	(
		SELECT 
			D3_FILIAL FILIAL, 
			SUBSTRING(D3_EMISSAO,5,2) + '_QTD' MESQTD, 
			SUBSTRING(D3_EMISSAO,5,2) + '_VLR' MESVLR, 
			SUM(D3_QUANT) QUANTIDADE, 
			SUM(D3_CUSTO1) CUSTO
		FROM 
			SD3040 D3  with (noLock) 
			INNER JOIN SB1040 B1 ON (B1.D_E_L_E_T_ = '' AND B1_FILIAL = '    ' AND D3_COD = B1_COD) 
			LEFT JOIN DHI040 DHI ON (DHI.D_E_L_E_T_ = '' AND  D3_XMOTIVO = DHI_CODIGO) 
		WHERE 
			D3_FILIAL = '0404' AND
			D3_CF IN ('RE0','DE0','DE6','RE6') AND 
			D3_DOC <> 'INVENT' AND 
			D3_USUARIO <> 'Administrador' AND 
			D3_EMISSAO BETWEEN '20210101' AND '20220801' AND
			D3.D_E_L_E_T_ = ''
		GROUP BY D3_FILIAL,SUBSTRING(D3_EMISSAO,5,2)
	)MOV_INTERNA
	PIVOT ( SUM( QUANTIDADE) FOR MESQTD IN([01_QTD],[02_QTD],[03_QTD],[04_QTD],[05_QTD],[06_QTD],[07_QTD],[08_QTD],[09_QTD],[10_QTD],[11_QTD],[12_QTD]) )  EM_QUANTIDADE
	PIVOT ( SUM( CUSTO) FOR MESVLR IN([01_VLR],[02_VLR],[03_VLR],[04_VLR],[05_VLR],[06_VLR],[07_VLR],[08_VLR],[09_VLR],[10_VLR],[11_VLR],[12_VLR]) )  EM_CUSTO
	GROUP BY FILIAL 
