SELECT
	W2.W2_PO_NUM NUM_PO,
	W2.W2_FORN FORNECEDOR,
	W2.W2_FORLOJ LOJA,
	AIA.AIA_CODTAB TABELA,
	AIA.AIA_DESCRI DESC_TABELA,
	W3.W3_COD_I PRODUTO,
	W3.W3_QTDE QUANTIDADE,
	W3.W3_PRECO PRECO_PO,
	AIB.AIB_PRCCOM PRECO_TABELA
FROM 
	SW2040 W2 (NOLOCK)
	LEFT JOIN AIA040 AIA (NOLOCK) ON AIA.AIA_FILIAL = W2.W2_FILIAL AND AIA_CODFOR = W2.W2_FORN AND AIA.AIA_LOJFOR = W2.W2_FORLOJ AND AIA.AIA_CODTAB = '001' AND AIA.D_E_L_E_T_ = ''
	INNER JOIN SW3040 W3 (NOLOCK) ON W3.W3_FILIAL = W2.W2_FILIAL AND W3.W3_PO_NUM = W2.W2_PO_NUM AND W3.D_E_L_E_T_ = ''
	INNER JOIN AIB040 AIB (NOLOCK) ON AIB.AIB_FILIAL = AIA.AIA_FILIAL AND AIB.AIB_CODTAB = AIA.AIA_CODTAB AND AIB.AIB_CODFOR = AIA.AIA_CODFOR AND AIB.AIB_LOJFOR = AIA.AIA_LOJFOR AND AIB.AIB_CODPRO = W3.W3_COD_I AND AIB.D_E_L_E_T_ = '' 
WHERE 
	W2.W2_FILIAL = '0404' AND 
	W2.W2_PO_DT BETWEEN '20220101' AND '20220621' AND
	W2.D_E_L_E_T_ = ''
ORDER BY W2_PO_DT