-- Categorias x caracteristicas
SELECT ZA2.ZA2_CODCAT,ZA2.ZA2_CODCAR, ZA2.ZA2_OBRIGA, ZA2.ZA2_STATUS,ZA2.ZA2_OPER, ZA2.ZA2_STATEC,
ZA2.R_E_C_N_O_ AS RECNOZA2, SZE.R_E_C_N_O_ AS RECNOSZE
FROM ZA2030 ZA2
INNER JOIN SZE030 SZE ON SZE.ZE_FILIAL = ZA2.ZA2_FILIAL AND SZE.ZE_CODIGO = ZA2.ZA2_CODCAR AND SZE.D_E_L_E_T_ = ' '
WHERE
ZA2.ZA2_FILIAL = '  ' AND ZA2.ZA2_ENVECO = '1' AND ZA2.D_E_L_E_T_ = ' '
ORDER BY ZA2_CODCAR, ZA2_CODCAT

-- Fabricantes
SELECT T7_FABRICA,T7_STATUS,
T7_OPER,R_E_C_N_O_ RECNOREG 
FROM
ST7030
WHERE
T7_FILIAL = ' ' AND 
T7_ENVECOM = '1' AND
D_E_L_E_T_ = ' '
ORDER BY T7_FABRICA

-- Produto x Categoria
SELECT ACV.ACV_REFGRD,ACV.ACV_CATEGO,
ACV.ACV_STATUS,ACV.ACV_OPER,ACV.ACV_STATEC,
ACV.R_E_C_N_O_ RECNOACV,SB1.B1_STATEC
FROM
ACV030 ACV
INNER JOIN SB1030 SB1 ON SB1.B1_FILIAL = ' ' AND SB1.B1_COD = ACV.ACV_REFGRD AND SB1.D_E_L_E_T_ = ' ' AND SB1.B1_STATEC = '1' 
WHERE
ACV.ACV_FILIAL = ' ' AND
ACV.ACV_ENVECO = '1' AND
ACV.D_E_L_E_T_ = ' '
ORDER BY ACV_CATEGO

-- Produto Pai
SELECT SB1.B1_COD,R_E_C_N_O_ RECNOSB1
FROM SB1030 SB1
WHERE
SB1.B1_USAECO = '1' AND
SB1.B1_STATPRO= '1' AND
SB1.B1_ENVECO = '1' AND
SB1.B1_STATEC IN(' ','2','0') AND
SB1.D_E_L_E_T_ = ' '

-- Produto Filho
SELECT SB1.B1_COD,ZA5.ZA5_CODCOR,
Cast(Cast(ZA5.ZA5_DESECO as Binary(1024)) as varchar(1024)) CORECO,
SB1.R_E_C_N_O_ RECNOSB1
FROM SB1030 SB1
LEFT OUTER JOIN ZA5030 ZA5 ON ZA5.ZA5_CODCOR = SB1.B1_CORECO AND ZA5.D_E_L_E_T_ = ' '
WHERE
SB1.B1_USAECO  = '1' AND
SB1.B1_STATPRO = '1' AND
SB1.B1_ENVECO  = '2' AND
SB1.B1_STATFIL = '1' AND
SB1.B1_STATEC  = '1' AND
SB1.D_E_L_E_T_ = ' '

-- Estoque
SELECT SB2.B2_COD,
(SB2.B2_QATU - SB2.B2_QEMP - SB2.B2_RESERVA) AS ESTOQUE, SB2.R_E_C_N_O_ AS RECSB2, SB1.B1_EMIN, SB1.R_E_C_N_O_ AS RECSB1
FROM
SB2030 SB2
INNER JOIN SB1030 SB1 ON SB1.B1_COD = SB2.B2_COD AND SB1.B1_USAECO = '1' AND SB1.B1_STATPRO = '1' AND SB1.D_E_L_E_T_ = ' '
WHERE
SB2.B2_FILIAL = '03' AND SB2.B2_LOCAL = '01' AND SB2.B2_ENVECO = '1' AND
SB2.D_E_L_E_T_ = ' '
ORDER BY B2_COD

-- Produto x Categoria x caracteristica
SELECT DISTINCT ZA3.ZA3_PRODUT,ZA3.ZA3_CODCAR,ZA3.ZA3_VALOR,ZA3.ZA3_STATUS,ZA3.ZA3_OPER,ZA3.ZA3_STATEC,SB1.B1_STATEC
FROM ZA3030 ZA3
INNER JOIN SB1030 SB1
ON SB1.B1_FILIAL = ' ' AND SB1.B1_COD = ZA3.ZA3_PRODUT AND SB1.D_E_L_E_T_ = ' '
AND SB1.B1_STATEC = '1' AND SB1.B1_USAECO = '1'
WHERE
ZA3.ZA3_ENVECO = '1' AND ( ZA3.ZA3_SEQVAL <> ' ' OR ( ZA3.ZA3_SEQVAL = ' ' )  ) AND 
ZA3.D_E_L_E_T_ = ' '
ORDER BY ZA3_PRODUT,ZA3_CODCAR
