-- Produtos - pedidos de compra
SELECT 
	TIPO,PRODUTO, PEDIDO,PACK, DESCRICAO, 
	SUM(QTDPACK) QTDPACK, SUM(QTDPARES) QTDPARES, 
	SEMANA,DTENTREGA
FROM
	(
			SELECT 
				'PC' TIPO, SC7.C7_NUM PEDIDO, LEFT(SC7.C7_PRODUTO,23) PRODUTO, 
				'' PACK , SC7.C7_DESCRI DESCRICAO, 0 QTDPACK, 
				( SC7.C7_QUANT - SC7.C7_QUJE ) QTDPARES,
				SC7.C7_01SEMAN SEMANA, SC7.C7_DATPRF DTENTREGA
			FROM
				SC7010 SC7
				INNER JOIN SB4010 SB4 ON SB4.B4_GRUPO = '100' AND SB4.D_E_L_E_T_ = ''
			WHERE
				SC7.C7_FILIAL = '05' AND 
				SC7.C7_01SEMAN BETWEEN '' AND 'ZZ' AND 
				Left(SC7.C7_PRODUTO,23) = SB4.B4_COD AND 
				SC7.C7_XCOLECA = 'F13' AND 
				SC7.C7_01PACKS = '' AND 
				SC7.D_E_L_E_T_ = ''
					
		UNION ALL
		
			SELECT 
				'PC' TIPO, SC7.C7_NUM PEDIDO , LEFT(SC7.C7_PRODUTO,23) PRODUTO, 
				SC7.C7_01PACKS PACK , SC7.C7_DESCRI DESCRICAO, 
				( SC7.C7_QUANT - SC7.C7_QUJE ) QTDPACK,0 QTDPARES,
				SC7.C7_01SEMAN SEMANA, SC7.C7_DATPRF DTENTREGA
			FROM
				SC7010 SC7
				INNER JOIN SB4010 SB4 ON SB4.B4_GRUPO = '100' AND SB4.D_E_L_E_T_ = ''
			WHERE
				SC7.C7_FILIAL = '05' AND 
				SC7.C7_01SEMAN BETWEEN '' AND 'ZZ' AND 
				Left(SC7.C7_PRODUTO,23) = SB4.B4_COD AND 
				SC7.C7_XCOLECA = 'F13' AND 
				SC7.C7_01PACKS <> '' AND 
				SC7.D_E_L_E_T_ = ''
		
						
	) COTAPROD	
	GROUP BY TIPO,PRODUTO,PEDIDO,
			PACK,DESCRICAO,SEMANA,
			DTENTREGA

