WITH CATEGORIA(CODIGO,DESCRI,NIVEL)

AS
(
	-- Ancora
    SELECT 
		ACU_COD,
		ACU_DESC,
		1 AS 'NIVEL'
    FROM 
		ACU010 
	WHERE 
		ACU_CODPAI = '' 
    
    UNION ALL
    
    -- Parte RECURSIVA
    SELECT 
        M.ACU_COD,
		M.ACU_DESC,
		C.NIVEL + 1 AS 'NIVEL' 
    FROM 
		ACU010 M 
		INNER JOIN CATEGORIA C ON M.ACU_CODPAI = C.CODIGO		
)
SELECT CODIGO,DESCRI,NIVEL FROM CATEGORIA