-- CATEGORIAS
SELECT 
AY1_CODIGO,AY1_SUBCAT,AY0_DESC,
AY0_STATUS,AY1_CATPAI,AY1_CATFIL,
SYP.YP_TEXTO,AY0.AY0_CODDES,
AY0.R_E_C_N_O_ RECNOAY0 
FROM AY1010 AY1 
INNER JOIN AY0010 AY0 ON AY0.AY0_CODIGO = AY1.AY1_SUBCAT AND 
AY0.AY0_ENVECO = '1' AND AY0.AY0_STATEC = '2' AND AY0.D_E_L_E_T_ = ' ' 
INNER JOIN SYP010 SYP ON SYP.YP_CHAVE = AY0.AY0_CODDES AND SYP.D_E_L_E_T_ = '' 
WHERE 
AY1.D_E_L_E_T_ = '' 
ORDER BY AY0_TIPO 

-- FABRICANTES / MARCAS
SELECT AY2_CODIGO,AY2_STATUS, 
CAST(CAST(AY2_DESECO AS BINARY(1024)) AS VARCHAR(1024)) DESCECO, 
R_E_C_N_O_ RECNOAY2 
FROM 
AY2010
WHERE 
AY2_FILIAL = '' AND 
AY2_ENVECO = '1' AND 
AY2_STATEC = '2' AND 
D_E_L_E_T_ = ' ' 
ORDER BY AY2_CODIGO 

-- ENQUDRAMENTO GARANTIA
SELECT ZZ0.ZZ0_CODIGO,ZZ0.ZZ0_DESC, 
ZZ0.ZZ0_STATUS, ZZ0.R_E_C_N_O_ RECNOZZ0 
FROM 
ZZ0010 ZZ0
WHERE 
ZZ0.ZZ0_FILIAL = '' AND 
ZZ0.ZZ0_ENVECO = '1' AND 
ZZ0.ZZ0_STATEC = '2' AND 
ZZ0.D_E_L_E_T_ = '' 
ORDER BY ZZ0.ZZ0_CODIGO 

-- GARANTIA ESTENDIDA
SELECT ZZ1.ZZ1_CODENQ,ZZ1.ZZ1_ITEM,ZZ1.ZZ1_CODGAR,
ZZ1.ZZ1_ANOS,ZZ1.ZZ1_VALOR,ZZ1.R_E_C_N_O_ RECNOZZ1 
FROM 
ZZ1010 ZZ1
INNER JOIN ZZ0010 ZZ0 ON ZZ1.ZZ1_FILIAL = '' AND ZZ0.ZZ0_CODIGO = ZZ1.ZZ1_CODENQ AND ZZ0.ZZ0_ENVECO = '2' AND ZZ0.ZZ0_STATEC = '1' AND ZZ0.D_E_L_E_T_ = '' 
WHERE 
ZZ1.ZZ1_FILIAL = '' AND 
ZZ1.ZZ1_ENVECO = '1' AND 
ZZ1.ZZ1_STATEC = '2' AND 
ZZ1.D_E_L_E_T_ = '' 
ORDER BY ZZ1.ZZ1_CODENQ 

-- PRODUTOS
SELECT SB1.B1_COD,AYV_CODMA,AYV.AYV_PESO,AYV.AYV_PESOEM,AYV.AYV_ALTPRO,AYV.AYV_ALTEMB,AYV.AYV_LARGPR,AYV.AYV_LARGEM,AYV.AYV_PROFPR,AYV.AYV_PROFEM,
AYV.AYV_ENTREG,AYV.AYV_QTDMAX,AYV.AYV_STATUS,AYV.AYV_TIPOPR,AYV.AYV_PRESEN,AYV.AYV_PERSON,AYV.AYV_TITPER,AYV.AYV_YOUTUB,SB1.B1_PRV1,DA1.DA1_PRCVEN, 
AYV.AYV_CODENQ,AYV.R_E_C_N_O_ RECNOAYV 
FROM 
AYV010 AYV 
INNER JOIN SB1010 SB1 ON SB1.B1_FILIAL = '' AND SB1.B1_COD = AYV.AYV_COD AND SB1.D_E_L_E_T_ = '' 
LEFT JOIN DA1010 DA1 ON DA1.DA1_FILIAL = '' AND DA1.DA1_CODTAB = '001' AND DA1.DA1_CODPRO = AYV.AYV_COD AND DA1.D_E_L_E_T_ = '' 
WHERE 
AYV.AYV_FILIAL = '' AND 
AYV.AYV_USAECO = '1' AND 
AYV.AYV_STATEC IN('0','2') AND 
AYV.D_E_L_E_T_ = '' 
ORDER BY SB1.B1_COD 

-- PRODUTO CATEGORIA
SELECT DISTINCT(AYV.AYV_COD),AYV.AYV_DESC,AYV.AYV_CAT1,AYV.AYV_CAT2,AYV.AYV_CAT3,AYV.AYV_CAT4,AYV.AYV_CAT4,AYV.AYV_CAT5,AYV.R_E_C_N_O_ RECNOAYV, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_SUBCAT = AYV.AYV_CAT1 AND AY1.D_E_L_E_T_ = '' ) CATNV1, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT1 AND AY1.AY1_SUBCAT = AYV.AYV_CAT2 AND AY1.D_E_L_E_T_ = '' ) CATNV2, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT2 AND AY1.AY1_SUBCAT = AYV.AYV_CAT3 AND AY1.D_E_L_E_T_ = '' ) CATNV3, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT3 AND AY1.AY1_SUBCAT = AYV.AYV_CAT4 AND AY1.D_E_L_E_T_ = '' ) CATNV4, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT4 AND AY1.AY1_SUBCAT = AYV.AYV_CAT5 AND AY1.D_E_L_E_T_ = '' ) CATNV5  
FROM 
AYV010 AYV 
WHERE 
AYV.AYV_FILIAL = '' AND 
AYV.AYV_USAECO = '1' AND 
AYV.AYV_ENVECO = '2' AND 
AYV.AYV_STATEC = '1' AND 
AYV.AYV_CATECO = '1' AND 
AYV.D_E_L_E_T_ = '' 
ORDER BY AYV_COD 

-- FILTROS
SELECT DISTINCT(AY3.AY3_CODIGO), 
CAST(CAST(AY3.AY3_DESCEC AS BINARY) AS VARCHAR) CARDESC, 
AY3.AY3_STATUS,AY3.R_E_C_N_O_ RECNOAY3, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_SUBCAT = AYV.AYV_CAT1 AND AY1.D_E_L_E_T_ = '' ) CATNV1, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT1 AND AY1.AY1_SUBCAT = AYV.AYV_CAT2 AND AY1.D_E_L_E_T_ = '' ) CATNV2,
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT2 AND AY1.AY1_SUBCAT = AYV.AYV_CAT3 AND AY1.D_E_L_E_T_ = '' ) CATNV3, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT3 AND AY1.AY1_SUBCAT = AYV.AYV_CAT4 AND AY1.D_E_L_E_T_ = '' ) CATNV4, 
(SELECT AY1.AY1_CATFIL FROM AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT4 AND AY1.AY1_SUBCAT = AYV.AYV_CAT5 AND AY1.D_E_L_E_T_ = '' ) CATNV5, 
AYV.AYV_COD 
FROM 
AY3010 AY3 
INNER JOIN AY5010 AY5 ON AY5.AY5_FILIAL = '' AND AY5_CODIGO = AY3.AY3_CODIGO AND AY5.D_E_L_E_T_ = '' 
INNER JOIN AYV010 AYV ON AYV.AYV_FILIAL = '' AND AYV.AYV_COD = AY5.AY5_CODPRO AND AYV.AYV_USAECO = '1' AND AYV.AYV_ENVECO = '2' AND AYV.AYV_STATEC = '1' AND AYV.D_E_L_E_T_ = '' 
WHERE 
AY3.AY3_STATEC IN('0','2') AND 
AY3.AY3_ENVECO = '1' AND 
AY3.D_E_L_E_T_ = '' 
ORDER BY AYV.AYV_COD

-- FILTRO X PRODUTOS
SELECT AY5.AY5_CODIGO,AY5.AY5_SEQ, 
CAST(CAST(AY4.AY4_VLRECO AS BINARY) AS VARCHAR) VLRECO, 
AY5.AY5_CODPRO,AY5.AY5_STATUS,AY5.R_E_C_N_O_ RECNOAY5, 
AY4.R_E_C_N_O_ RECNOAY4 
FROM 
AY5010 AY5 
INNER JOIN AY4010 AY4 ON AY4.AY4_FILIAL = '' AND AY4.AY4_CODCAR = AY5.AY5_CODIGO AND AY4.AY4_SEQ = AY5.AY5_SEQ AND AY4.AY4_STATEC = '2' AND AY4.AY4_ENVECO = '1' AND AY4.D_E_L_E_T_ = '' 
INNER JOIN AYV010 AYV ON AYV.AYV_FILIAL = '' AND AYV.AYV_COD = AY5.AY5_CODPRO AND AYV.AYV_ENVECO = '2' AND AYV.AYV_STATEC = '1' AND AYV.AYV_USAECO = '1' AND AYV.D_E_L_E_T_ = '' 
WHERE 
AY5.AY5_FILIAL = '' AND 
AY5.AY5_ENVECO = '1' AND 
AY5.AY5_STATEC = '2' AND 
AY5.D_E_L_E_T_ = ' ' 
ORDER BY AY5_CODPRO 

-- ESTOQUE
SELECT AYV.AYV_COD,AYV.AYV_DESC,SB2.B2_LOCAL, 
(SB2.B2_QATU - SB2.B2_QEMP - SB2.B2_RESERVA - SB2.B2_QPEDVEN) AS ESTOQUE, 
AYV.AYV_ESTMIN,SB2.R_E_C_N_O_ RECNOSB2 
FROM 
SB2010 SB2 
INNER JOIN AYV010 AYV ON AYV.AYV_FILIAL = '' AND AYV.AYV_COD = SB2.B2_COD AND AYV.AYV_STATEC = '1' AND AYV.AYV_ENVECO = '2' AND AYV.AYV_USAECO = '1' AND AYV.D_E_L_E_T_ = ''
WHERE 
SB2.B2_FILIAL = '02' AND 
SB2.B2_LOCAL = 'VE' AND 
SB2.B2_MSEXP = '' AND 
SB2.D_E_L_E_T_ = '' 
ORDER BY B2_COD 

-- ALTERACAO DE PRECO
SELECT DA1.DA1_REFGRD,DA1.DA1_CODPRO,DA1.DA1_PRCVEN,SB1.B1_PRV1,DA1.R_E_C_N_O_ RECNODA1 
FROM 
DA1010 DA1 
INNER JOIN SB1010 SB1 ON SB1.B1_FILIAL = '' AND SB1.B1_COD = DA1.DA1_CODPRO AND SB1.D_E_L_E_T_ = '' 
INNER JOIN AYV010 AYV ON AYV.AYV_FILIAL = '' AND AYV.AYV_COD = DA1.DA1_CODPRO AND AYV.AYV_ENVECO = '2' AND AYV.AYV_STATEC = '1' AND AYV.AYV_USAECO = '1' AND AYV.D_E_L_E_T_ = '' 
WHERE 
DA1.DA1_FILIAL = '' AND 
DA1.DA1_ENVECO = '2' AND 
DA1.DA1_CODTAB = '001' AND 
DA1.D_E_L_E_T_ = '' 