SELECT 
	AY1_SUBCAT CATNV1
,	AY0_DESC DESCNV1
,	'' CATNV2
,	'' DESCNV2 
,	'' CATNV3
,	'' DESCNV3
,	'' CATNV4
,	'' DESCNV4 
,	'' CATNV5
,	'' DESCNV5  
,	AY0_STATUS
,	AY1_CATPAI
,	AY1_CATFIL
,	SYP.YP_TEXTO
,	AY0.R_E_C_N_O_ RECNOAY0 
FROM 
	AY1010 AY1
	INNER JOIN AY0010 AY0 ON AY0.AY0_CODIGO = AY1.AY1_SUBCAT AND AY0.AY0_ENVECO IN('1'/*,'2'*/) AND AY0.AY0_STATEC IN(/*'1',*/'2') AND AY0.AY0_TIPO = '1' AND AY0.D_E_L_E_T_ = ''
	INNER JOIN SYP010 SYP ON SYP.YP_CHAVE = AY0.AY0_CODDES AND SYP.D_E_L_E_T_ = '' 
WHERE 
	AY1.D_E_L_E_T_ = ' '

UNION ALL

SELECT 
	'' CATNV1
,	'' DESCNV1
,	AY1.AY1_SUBCAT	CATNV2
,	AY0.AY0_DESC	DESCNV2 
,	'' CATNV3
,	'' DESCNV3
,	'' CATNV4
,	'' DESCNV4 
,	'' CATNV5
,	'' DESCNV5  
,	AY0_STATUS
,	AY1_CATPAI
,	AY1_CATFIL
,	SYP.YP_TEXTO
,	AY0.R_E_C_N_O_ RECNOAY0 
FROM 
	AY1010 AY1
	INNER JOIN AY0010 AY0 ON AY0.AY0_CODIGO = AY1.AY1_SUBCAT AND AY0.AY0_ENVECO IN('1'/*,'2'*/) AND AY0.AY0_STATEC IN(/*'1',*/'2') AND AY0.AY0_TIPO = '2' AND AY0.D_E_L_E_T_ = ''
	INNER JOIN SYP010 SYP ON SYP.YP_CHAVE = AY0.AY0_CODDES AND SYP.D_E_L_E_T_ = '' 
WHERE 
	AY1.D_E_L_E_T_ = ' ' 

UNION ALL

SELECT 
	''	CATNV1
,	''	DESCNV1
,	''	CATNV2
,	''	DESCNV2 
,	AY1.AY1_SUBCAT	CATNV3
,	AY0.AY0_DESC	DESCNV3
,	''	CATNV4
,	''	DESCNV4 
,	''	CATNV5
,	''	DESCNV5  
,	AY0_STATUS
,	AY1_CATPAI
,	AY1_CATFIL
,	SYP.YP_TEXTO
,	AY0.R_E_C_N_O_ RECNOAY0 
FROM 
	AY1010 AY1
	INNER JOIN AY0010 AY0 ON AY0.AY0_CODIGO = AY1.AY1_SUBCAT AND AY0.AY0_ENVECO IN('1'/*,'2'*/) AND AY0.AY0_STATEC IN(/*'1',*/'2') AND AY0.AY0_TIPO = '3' AND AY0.D_E_L_E_T_ = ''
	INNER JOIN SYP010 SYP ON SYP.YP_CHAVE = AY0.AY0_CODDES AND SYP.D_E_L_E_T_ = '' 
WHERE 
	AY1.D_E_L_E_T_ = ' ' 
UNION ALL

SELECT 
	''	CATNV1
,	''	DESCNV1
,	''	CATNV2
,	''	DESCNV2 
,	''	CATNV3
,	''	DESCNV3
,	AY1.AY1_SUBCAT	CATNV4
,	AY0.AY0_DESC	DESCNV4 
,	''	CATNV5
,	''	DESCNV5  
,	AY0_STATUS
,	AY1_CATPAI
,	AY1_CATFIL
,	SYP.YP_TEXTO
,	AY0.R_E_C_N_O_ RECNOAY0 
FROM 
	AY1010 AY1
	INNER JOIN AY0010 AY0 ON AY0.AY0_CODIGO = AY1.AY1_SUBCAT AND AY0.AY0_ENVECO IN('1'/*,'2'*/) AND AY0.AY0_STATEC IN(/*'1',*/'2') AND AY0.AY0_TIPO = '4' AND AY0.D_E_L_E_T_ = ''
	INNER JOIN SYP010 SYP ON SYP.YP_CHAVE = AY0.AY0_CODDES AND SYP.D_E_L_E_T_ = '' 
WHERE 
	AY1.D_E_L_E_T_ = ' ' 
