-- Produto
SELECT SB1.B1_COD,AYV_CODMA,AYV.AYV_PESO,AYV.AYV_PESOEM,AYV.AYV_ALTPRO,AYV.AYV_ALTEMB,AYV.AYV_LARGPR,AYV.AYV_LARGEM,AYV.AYV_PROFPR,AYV.AYV_PROFEM, 
AYV.AYV_ENTREG,AYV.AYV_QTDMAX,AYV.AYV_STATUS,AYV.AYV_TIPOPR,AYV.AYV_PRESEN,AYV.AYV_PERSON,AYV.AYV_TITPER,AYV.AYV_YOUTUB,SB1.B1_PRV1,DA1.DA1_PRCVEN,
AYV.AYV_OPER,AYV.AYV_CODENQ,AYV.R_E_C_N_O_ RECNOAYV
FROM 
AYV010 AYV 
INNER JOIN SB1010 SB1 ON SB1.B1_FILIAL = '03' AND SB1.B1_COD = AYV.AYV_COD AND SB1.D_E_L_E_T_ = '' 
LEFT JOIN DA1010 DA1 ON DA1.DA1_FILIAL = '03' AND DA1.DA1_CODTAB = '001' AND DA1.DA1_CODPRO = AYV.AYV_COD AND DA1.D_E_L_E_T_ = '' 
WHERE 
AYV.AYV_FILIAL = '03' AND 
AYV.AYV_USAECO = '1' AND 
AYV.AYV_STATEC IN('0','2') AND 
AYV.D_E_L_E_T_ = '' 
ORDER BY SB1.B1_COD 

-- Produto x Categoria
SELECT DISTINCT(AYV.AYV_COD),AYV.AYV_DESC,AYV.AYV_CAT1,AYV.AYV_CAT2,AYV.AYV_CAT3,AYV.AYV_CAT4,AYV.AYV_CAT4,AYV.AYV_CAT5,AYV.AYV_OPER,AYV.R_E_C_N_O_ RECNOAYV, 
(SELECT AY1.AY1_CATFIL FROM   AY1010 AY1 WHERE AY1.AY1_SUBCAT = AYV.AYV_CAT1 AND AY1.D_E_L_E_T_ = '')  CATNV1, 
(SELECT AY1.AY1_CATFIL FROM   AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT1 AND AY1.AY1_SUBCAT = AYV.AYV_CAT2 AND AY1.D_E_L_E_T_ = '')  CATNV2, 
(SELECT AY1.AY1_CATFIL FROM   AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT2 AND AY1.AY1_SUBCAT = AYV.AYV_CAT3 AND AY1.D_E_L_E_T_ = '')  CATNV3, 
(SELECT AY1.AY1_CATFIL FROM   AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT3 AND AY1.AY1_SUBCAT = AYV.AYV_CAT4 AND AY1.D_E_L_E_T_ = '')  CATNV4, 
(SELECT AY1.AY1_CATFIL FROM   AY1010 AY1 WHERE AY1.AY1_CODIGO = AYV.AYV_CAT4 AND AY1.AY1_SUBCAT = AYV.AYV_CAT5 AND AY1.D_E_L_E_T_ = '')  CATNV5  
FROM 
AYV010  AYV 
WHERE 
AYV.AYV_FILIAL = '03' AND 
AYV.AYV_USAECO = '1'  AND 
AYV.AYV_ENVECO = '2'  AND 
AYV.AYV_STATEC = '1'  AND 
AYV.AYV_CATECO = '1'  AND 
AYV.D_E_L_E_T_ = '' 
ORDER BY AYV_COD 