SELECT PEDIDO,PRODUTO,ITEM,SUM(VENDAS) VENDAS,SUM(ENTREGUE) ENTREGUE,SUM(FATURADO) FATURADO,SUM(LIBERADO) LIBERADO
FROM (

SELECT C6_NUM PEDIDO,C6_PRODUTO PRODUTO,C6_ITEM ITEM ,C6_QTDVEN VENDAS,C6_QTDENT ENTREGUE,0 FATURADO,0 LIBERADO
FROM SC6010 SC6 
WHERE SC6.D_E_L_E_T_ = ''
AND SC6.C6_NUM = '132363'
AND SC6.C6_FILIAL = '05'
GROUP BY C6_NUM,C6_PRODUTO,C6_ITEM,C6_QTDVEN,C6_QTDENT

UNION

SELECT D2_PEDIDO PEDIDO,D2_COD PRODUTO,D2_ITEMPV ITEM ,0 VENDAS,0 ENTREGUE,SUM(D2_QUANT) FATURADO,0 LIBERADO
FROM SD2010 SD2 
WHERE SD2.D_E_L_E_T_ = ''
AND SD2.D2_PEDIDO = '132363'
AND SD2.D2_FILIAL = '05'
GROUP BY D2_PEDIDO,D2_COD,D2_ITEMPV

UNION

SELECT C9_PEDIDO PEDIDO,C9_PRODUTO PRODUTO,C9_ITEM ITEM ,0 VENDAS,0 ENTREGUE,0 FATURADO,SUM(C9_QTDLIB) LIBERADO
FROM SC9010 SC9 
WHERE SC9.D_E_L_E_T_ = ''
AND SC9.C9_PEDIDO = '132363'
AND SC9.C9_FILIAL = '05'
AND SC9.C9_NFISCAL = '' 
GROUP BY C9_PEDIDO,C9_PRODUTO,C9_ITEM

) XXX
GROUP BY PEDIDO,PRODUTO,ITEM
--HAVING SUM(LIBERADO) > SUM(VENDAS)
ORDER BY PEDIDO,PRODUTO,ITEM
