-- Representantes
SELECT 
	VENDEDOR, NREDUZ, SUM(QTDVEND) QTDVEND
FROM
	(
		SELECT 
			SA3.A3_COD VENDEDOR , SA3.A3_NREDUZ NREDUZ ,SC6.C6_QTDVEN QTDVEND
		FROM 
			SA3010 SA3
		LEFT OUTER JOIN SC5010 SC5 ON SC5.C5_FILIAL = '05' AND SC5.C5_VEND1 = SA3.A3_COD AND SC5.C5_XCOLECA = 'S13' AND SC5.D_E_L_E_T_ = ''
		LEFT OUTER JOIN SC6010 SC6 ON SC6.C6_FILIAL = '05' AND SC6.C6_NUM = SC5.C5_NUM AND LEFT(SC6.C6_PRODUTO,23) = 'D110N.1123             ' AND SC6.D_E_L_E_T_ = ''
		WHERE
			SA3.A3_FILIAL = '05' AND 
			SA3.A3_COD BETWEEN '' AND 'ZZZZZZ' AND 
			SA3.D_E_L_E_T_ = ''
		
		UNION ALL
		
		SELECT 
			SA3.A3_COD VENDEDOR , SA3.A3_NREDUZ NREDUZ ,SCK.CK_QTDVEN QTDVEND
		FROM 
			SA3010 SA3
		LEFT OUTER JOIN SCJ010 SCJ ON SCJ.CJ_FILIAL = '05' AND SCJ.CJ_VEND1 = SA3.A3_COD AND SCJ.CJ_XCOLECA = 'S13' AND SCJ.D_E_L_E_T_ = ''
		LEFT OUTER JOIN SCK010 SCK ON SCK.CK_FILIAL = '05' AND SCK.CK_NUM = SCK.CK_NUM AND LEFT(SCK.CK_PRODUTO,23) = 'D110N.1123             ' AND SCK.CK_NUMPV = ''  AND SCK.D_E_L_E_T_ = ''
		WHERE
			SA3.A3_FILIAL = '05' AND 
			SA3.A3_COD BETWEEN '' AND 'ZZZZZZ' AND 
			SA3.D_E_L_E_T_ = ''
		
	)REPRE
	GROUP BY VENDEDOR, NREDUZ
	ORDER BY VENDEDOR
