SELECT  
		C9_FILIAL,   
		C9_PEDIDO,  
		C9_01DTFAT, 
		C5_CLIENTE, 
		C5_LOJACLI, 
		A1_NREDUZ,  
		C6_QTDVEN,  
		C6_TOTAL    
	FROM (  
			SELECT  
				C9_FILIAL,  
				C9_PEDIDO,  
				C9_01DTFAT, 
				C5_CLIENTE, 
				C5_LOJACLI, 
				A1_NREDUZ,  
				SUM(C9_QTDLIB) AS C6_QTDVEN, 
				SUM(C9_PRCVEN*C9_QTDLIB) AS C6_TOTAL 
			FROM   SC9010 SC9  
			INNER JOIN   SC6010   SC6 ON  
				C6_FILIAL = C9_FILIAL  
				AND C6_NUM = C9_PEDIDO  
				AND C6_ITEM = C9_ITEM  
				AND C6_PRODUTO = C9_PRODUTO  
				AND SC6.D_E_L_E_T_ = ''  
			INNER JOIN   SC5010   SC5 ON  
				C5_FILIAL = C9_FILIAL  
				AND C5_NUM = C9_PEDIDO  
				AND C5_VEND1 BETWEEN ' ' AND 'ZZZZZZ' 
				AND C5_CLIENTE BETWEEN '' AND 'ZZZZZZ' 
				AND C5_XCOLECA BETWEEN 'F13' AND 'F14' 
				AND SC5.D_E_L_E_T_ = ''  
			INNER JOIN   SA1010   SA1 ON  
				A1_FILIAL = ''  
				AND A1_COD = C5_CLIENTE  
				AND A1_LOJA = C5_LOJACLI  
				AND SA1.D_E_L_E_T_ = ''  
			WHERE  
				C9_FILIAL = '05'  
				AND C9_01PEDOP	= ''  
				AND C9_NFISCAL 	= ''  
				AND C9_BLEST 	= ''  
				AND SC9.D_E_L_E_T_ = ' '  
			GROUP BY C9_FILIAL,C9_PEDIDO,C9_01DTFAT,C5_CLIENTE,C5_LOJACLI,A1_NREDUZ  
		) AS TRB  
		WHERE  
			TRB.C6_QTDVEN > 0  
			AND TRB.C6_TOTAL <   750
	ORDER BY C9_FILIAL,C9_PEDIDO,C9_01DTFAT,C5_CLIENTE,C5_LOJACLI,A1_NREDUZ 