SELECT T7_FABRICA,T7_STATUS,
T7_OPER,R_E_C_N_O_ RECNOREG 
FROM 
ST7010
WHERE 
T7_FILIAL = '  ' AND 
T7_ENVECOM = '1' AND 
D_E_L_E_T_ = ' '
ORDER BY T7_FABRICA 

SELECT * FROM ST7010

SELECT ZA2.ZA2_CODCAT,ZA2.ZA2_CODCAR,
ZA2.ZA2_OBRIGA,ZA2.ZA2_STATUS,ZA2.ZA2_OPER, ZA2.ZA2_STATEC, 
ZA2.R_E_C_N_O_ AS RECNOZA2, ZA1.R_E_C_N_O_ AS RECNOZA1
FROM 
ZA2010 ZA2 
INNER JOIN ZA1010 ZA1 ON ZA1.ZA1_FILIAL = ZA2.ZA2_FILIAL AND ZA1.ZA1_CODCAR = ZA2.ZA2_CODCAR AND ZA1.D_E_L_E_T_ = ' ' 
WHERE 
ZA2_FILIAL = ' ' AND 
ZA2_ENVECO = '1' AND 
ZA2.D_E_L_E_T_ = ' ' 
ORDER BY ZA2_CODCAR 

SELECT ACU_COD,ACU_STATUS,ACU_CODPAI,ACU_ENVECO,ACU_STATEC,ACU_OPER,ACU.R_E_C_N_O_ AS ACU_RECNO
FROM ACU010 ACU
WHERE ACU_FILIAL = ' ' AND ACU_ENVECO = '1' AND ACU_OPER = '1' OR ACU_OPER = '2' AND ACU.D_E_L_E_T_ = ' '
ORDER BY ACU_CODPAI

SELECT B1_COD,B1_CODFAB,B1_VPESOEC,B1_STATPRO,B1_TIPOECO,B1_PRESENT,B1_PERSONA,B1_YOUTUBE,B1_PRV1,SB1.R_E_C_N_O_ AS B4_RECNO
FROM 
SB1010 SB1 
WHERE 
B1_FILIAL = ' ' AND 
B1_ENVECO = '1' AND 
B1_USAECO = '1' AND 
B1_OPER IN ('1','2','3') AND 
B1_VPESOEC > 0 AND 
SB1.D_E_L_E_T_ = ' ' 