WITH 
CATEGORIA(CATEGORIA) AS 
( 
   SELECT ACV.ACV_CATEGO
   FROM
   SB4010 SB4 
   INNER JOIN ACV060 ACV ON ACV.ACV_FILIAL = ' ' AND ACV.ACV_REFGRD = SB4.B4_COD AND ACV.D_E_L_E_T_ = ' ' AND ACV.ACV_ENVECO = '2' 
   WHERE
   SB4.B4_STATEC = '1' AND 
   SB4.D_E_L_E_T_ = ' '
        
),
PRODXCATEG(GRADE,CODCATEG,STATUS,OPER,STATUSEC,RECNOACV,STATUSGRADE,CODPAI) AS
(
   SELECT DISTINCT(ACV.ACV_REFGRD),ACV.ACV_CATEGO,
   ACV.ACV_STATUS,ACV.ACV_OPER,ACV.ACV_STATEC,
   ACV.R_E_C_N_O_ RECNOACV,SB4.B4_STATEC,ACU.ACU_COD
   FROM
   CATEGORIA
   INNER JOIN SB4010 SB4 ON SB4.B4_FILIAL = ' ' AND SB4.B4_STATEC = '1' AND SB4.D_E_L_E_T_ = ' '
   INNER JOIN ACV060 ACV ON ACV.ACV_FILIAL = ' ' AND ACV.ACV_REFGRD = SB4.B4_COD AND ACV.D_E_L_E_T_ = ' ' AND ACV.ACV_ENVECO = '2' 
   INNER JOIN ACU060 ACU ON ACU.ACU_FILIAL = ' ' AND ACU.ACU_COD = CATEGORIA AND  ACU.D_E_L_E_T_ = ' '
)
SELECT * FROM PRODXCATEG
ORDER BY GRADE


