-- Estoque Produto
SELECT SB2.B2_COD,SB2.B2_ENVECO, 
(SB2.B2_QATU - SB2.B2_RESERVA - SB2.B2_QPEDVEN) AS ESTOQUE,
SB2.R_E_C_N_O_ AS RECSB2, 
SB1.B1_EMIN, 
SB1.R_E_C_N_O_ AS RECSB1 
FROM
SB2060 SB2
INNER JOIN SB1010 SB1 ON SB1.B1_COD = SB2.B2_COD AND SB1.B1_USAECO = '1' AND SB1.D_E_L_E_T_ <> '*' 
WHERE
SB2.B2_FILIAL = '75' AND
SB2.B2_LOCAL = '01' AND 
SB2.B2_ENVECO = '1' AND
SB2.D_E_L_E_T_ <> '*' 
ORDER BY B2_COD 

-- Produto Filho Alteração
SELECT B0_COD,B0_PRV1,SB0.R_E_C_N_O_ AS B0_RECNO
FROM SB0010 SB0
INNER JOIN SB1010 SB1 ON  B1_COD = B0_COD AND SB1.D_E_L_E_T_ = ' '
WHERE 
SB0.B0_OPER = '1' OR SB0.B0_OPER = '2' AND 
SB0.B0_ENVECO = '1' AND 
SB1.B1_USAECO = '1' AND 
SB0.D_E_L_E_T_ = ' '
ORDER BY B0_COD

-- Produto Pai
SELECT DISTINCT B4_COD,B4_CODFAB,B4_PESO,B4_STATPRO,B4_TIPOECO,B4_PRESENT,B4_PERSONA,B4_YOUTUBE,B0_PRV1,B0_PRV2,SB4.R_E_C_N_O_ AS B4_RECNO
FROM SB4010 SB4
INNER JOIN SB0010 SB0
ON B0_FILIAL = '75' AND SUBSTR(B0_COD,1,9) = B4_COD AND SB0.D_E_L_E_T_ = ' '
WHERE B4_FILIAL = '  ' AND 
B4_ENVECO = '1' AND 
B4_USAECO = '1' AND 
B4_OPER = '1' OR B4_OPER = '2' AND 
SB4.D_E_L_E_T_ = ' '

-- Caracteristicas
SELECT ZA3_PRODUT,ZA3_CODCAR,
ZA3_VALOR,ZA3_STATUS,ZA3_OPER, 
R_E_C_N_O_ AS RECNOZA3
FROM 
ZA3060
WHERE
ZA3_ENVECO = '1' AND
D_E_L_E_T_ = ' ' 
ORDER BY ZA3_CODCAR 

-- Categorias
SELECT ACU_COD,ACU_STATUS,ACU_CODPAI,ACU_ENVECO,ACU_STATEC,ACU_OPER,ACU.R_E_C_N_O_ AS ACU_RECNO
FROM ACU060 ACU
WHERE ACU_FILIAL = '  ' AND 
ACU_ENVECO = '1' AND 
ACU_OPER = '1' OR ACU_OPER = '2' AND 
ACU.D_E_L_E_T_ = ' '
ORDER BY ACU_CODPAI

-- Categorias X Produtos
SELECT ACV_REFGRD,ACV_CATEGO, 
ACV_STATUS,ACV_OPER 
FROM 
ACV060
WHERE
ACV_FILIAL = '  ' AND 
ACV_ENVECO = '1' AND 
D_E_L_E_T_ = ' ' 
ORDER BY ACV_CATEGO 

-- Salvar caracteristicas
SELECT DISTINCT SUBSTR(B1_COD,1,9) AS B1_CODPRO,B1_COD,B1_CORECO,B1_STATPRO,SUBSTR(B1_COD,12,2) AS B1_TAMANHO,SB1.R_E_C_N_O_ AS B1_RECNO
,BV_DESCRI,B0_PRV1,ZA5_DESCCO
FROM SB1010 SB1
INNER JOIN SB0010 SB0 ON B0_FILIAL = '75' AND B0_COD = B1_COD AND SB0.D_E_L_E_T_ = ' '
INNER JOIN SB4010 SB4
ON B4_FILIAL = '  ' AND SUBSTR(B4_COD,1,9) = SUBSTR(B1_COD,1,9) AND SB4.D_E_L_E_T_ = ' '
INNER JOIN SBV010 SBV ON BV_FILIAL = '  ' AND BV_TABELA = B4_COLUNA AND BV_CHAVE = SUBSTR(B1_COD,12,2) AND SBV.D_E_L_E_T_ = ' '
INNER JOIN ZA5060 ZA5 ON ZA5_FILIAL = '  ' AND ZA5_CODCOR = B1_CORECO AND ZA5.D_E_L_E_T_ = ' '
WHERE B1_FILIAL = '  ' AND B1_OPER = '1' OR B1_OPER = '2' AND B1_ENVECO = '1' AND B1_USAECO = '1' AND SB1.D_E_L_E_T_ = ' '

--- Altera Status Pedido
SELECT SC5.C5_NUMECO,SC5.C5_NUM, 
SC5.C5_STATECO,SC5.C5_STATUS, 
SC5.C5_SEDEX,SC5.C5_NOTA, 
SC5.C5_SERIE, SC5.R_E_C_N_O_ RECNOSC5, 
ZA8.ZA8_SEDEX 
FROM 
SC5060 SC5 
LEFT OUTER JOIN ZA8060 ZA8 ON ZA8.ZA8_PEDIDO = SC5.C5_NUM AND ZA8.D_E_L_E_T_ <> '*' 
WHERE 
SC5.C5_FILIAL = '75' AND 
SC5.C5_OPER IN('7','8','9') AND 
SC5.C5_NUMECO <> ' ' AND 
--SC5.C5_ENVECO = '1' AND 
SC5.D_E_L_E_T_ <> '*'
ORDER BY SC5.C5_NUM 
