SELECT 
	PEDIDO,CLIENTE,LOJACLI,TIPO,TRANSP,DTAEMISSAO,TIPOCLI,CONDPAG,
	VENDEDOR,ITEM,PRODUTO,DESCPROD,SUM(QTDCANC) QTDCANC,
	SUM(QTDVEN) QTDVEN,SUM(QTDEMP) QTDEMP,SUM(QTDENT) QTDENT,
	SUM(QTDLIB) QTDLIB, DTAENTR,ARMAZEM,VALOR,VALDESC,PRCVEN,TES
FROM
	(	SELECT
			SC5.C5_NUM PEDIDO ,SC5.C5_CLIENTE CLIENTE,SC5.C5_LOJACLI LOJACLI, 
			SC5.C5_TIPO TIPO ,SC5.C5_TRANSP TRANSP ,SC5.C5_EMISSAO DTAEMISSAO,
			SC5.C5_TIPOCLI TIPOCLI,SC5.C5_CONDPAG CONDPAG,SC5.C5_VEND1 VENDEDOR, 
			SC6.C6_ITEM ITEM,SC6.C6_PRODUTO PRODUTO,SC6.C6_DESCRI DESCPROD, 
			0 QTDCANC,SC6.C6_QTDVEN QTDVEN,SC6.C6_QTDEMP QTDEMP, 
			SC6.C6_QTDENT QTDENT,0 QTDLIB,SC6.C6_ENTREG DTAENTR,SC6.C6_LOCAL ARMAZEM, 
			SC6.C6_VALOR VALOR,SC6.C6_VALDESC VALDESC,SC6.C6_PRCVEN PRCVEN, 
			SC6.C6_TES TES
		FROM 
			SC5010 SC5 

			INNER JOIN SC6010 SC6 ON SC6.C6_FILIAL = SC5.C5_FILIAL AND SC6.C6_NUM = SC5.C5_NUM AND 
			SC6.C6_BLQ <> 'R' AND SC6.C6_ENTREG BETWEEN '20130101' AND '20130313' AND 
			SC6.C6_PRODUTO BETWEEN '' AND 'ZZZZZZZZZZZZZZZZZZZZZZZ' AND SC6.D_E_L_E_T_ = '' 

		WHERE
		SC5.C5_FILIAL = '05' AND 
		SC5.C5_NUM BETWEEN '' AND 'ZZZZZZ' AND  
		SC5.C5_CLIENTE BETWEEN '' AND 'ZZZZZZZZ' AND 
		SC5.C5_LOJACLI BETWEEN '' AND 'ZZ' AND 
		SC5.C5_VEND1 BETWEEN ''  AND 'ZZZZZZ' AND 
		SC5.D_E_L_E_T_ = '' 
		GROUP BY 
		SC5.C5_NUM,SC5.C5_CLIENTE,SC5.C5_LOJACLI, 
		SC5.C5_TIPO,SC5.C5_TRANSP,SC5.C5_EMISSAO,
		SC5.C5_TIPOCLI,SC5.C5_CONDPAG,SC5.C5_VEND1, 
		SC6.C6_ITEM,SC6.C6_PRODUTO,SC6.C6_DESCRI, 
		SC6.C6_XCANC,SC6.C6_QTDVEN,SC6.C6_QTDEMP, 
		SC6.C6_QTDENT,SC6.C6_ENTREG,SC6.C6_LOCAL, 
		SC6.C6_VALOR,SC6.C6_VALDESC,SC6.C6_PRCVEN, 
		SC6.C6_TES
		
		UNION
		
		SELECT
			SC5.C5_NUM PEDIDO ,SC5.C5_CLIENTE CLIENTE,SC5.C5_LOJACLI LOJACLI, 
			SC5.C5_TIPO TIPO ,SC5.C5_TRANSP TRANSP ,SC5.C5_EMISSAO DTAEMISSAO,
			SC5.C5_TIPOCLI TIPOCLI,SC5.C5_CONDPAG CONDPAG,SC5.C5_VEND1 VENDEDOR, 
			SC6.C6_ITEM ITEM,SC6.C6_PRODUTO PRODUTO,SC6.C6_DESCRI DESCPROD, 
			SC6.C6_QTDVEN QTDCANC,0 QTDVEN,0 QTDEMP, 
			0 QTDENT,0 QTDLIB,SC6.C6_ENTREG DTAENTR,SC6.C6_LOCAL ARMAZEM, 
			SC6.C6_VALOR VALOR,SC6.C6_VALDESC VALDESC,SC6.C6_PRCVEN PRCVEN, 
			SC6.C6_TES TES
		FROM 
			SC5010 SC5 

			INNER JOIN SC6010 SC6 ON SC6.C6_FILIAL = SC5.C5_FILIAL AND SC6.C6_NUM = SC5.C5_NUM AND 
			SC6.C6_BLQ = 'R' AND SC6.C6_XCANC = 'S' AND SC6.C6_ENTREG BETWEEN '20130101' AND '20130313' AND 
			SC6.C6_PRODUTO BETWEEN '' AND 'ZZZZZZZZZZZZZZZZZZZZZZZ' AND SC6.D_E_L_E_T_ = '' 

		WHERE
		SC5.C5_FILIAL = '05' AND 
		SC5.C5_NUM BETWEEN '' AND 'ZZZZZZ' AND  
		SC5.C5_CLIENTE BETWEEN '' AND 'ZZZZZZZZ' AND 
		SC5.C5_LOJACLI BETWEEN '' AND 'ZZ' AND 
		SC5.C5_VEND1 BETWEEN ''  AND 'ZZZZZZ' AND 
		SC5.D_E_L_E_T_ = '' 
		GROUP BY 
		SC5.C5_NUM,SC5.C5_CLIENTE,SC5.C5_LOJACLI, 
		SC5.C5_TIPO,SC5.C5_TRANSP,SC5.C5_EMISSAO,
		SC5.C5_TIPOCLI,SC5.C5_CONDPAG,SC5.C5_VEND1, 
		SC6.C6_ITEM,SC6.C6_PRODUTO,SC6.C6_DESCRI, 
		SC6.C6_XCANC,SC6.C6_QTDVEN,SC6.C6_QTDEMP, 
		SC6.C6_QTDENT,SC6.C6_ENTREG,SC6.C6_LOCAL, 
		SC6.C6_VALOR,SC6.C6_VALDESC,SC6.C6_PRCVEN, 
		SC6.C6_TES
		
		UNION
		
		SELECT
			SC5.C5_NUM PEDIDO ,SC5.C5_CLIENTE CLIENTE,SC5.C5_LOJACLI LOJACLI, 
			SC5.C5_TIPO TIPO ,SC5.C5_TRANSP TRANSP ,SC5.C5_EMISSAO DTAEMISSAO,
			SC5.C5_TIPOCLI TIPOCLI,SC5.C5_CONDPAG CONDPAG,SC5.C5_VEND1 VENDEDOR, 
			SC6.C6_ITEM ITEM,SC6.C6_PRODUTO PRODUTO,SC6.C6_DESCRI DESCPROD, 
			0 QTDCANC,0 QTDVEN,0 QTDEMP, 
			0 QTDENT,SC9.C9_QTDLIB QTDLIB,SC6.C6_ENTREG DTAENTR,SC6.C6_LOCAL ARMAZEM, 
			SC6.C6_VALOR VALOR,SC6.C6_VALDESC VALDESC,SC6.C6_PRCVEN PRCVEN, 
			SC6.C6_TES TES
		FROM 
			SC5010 SC5 

			INNER JOIN SC6010 SC6 ON SC6.C6_FILIAL = SC5.C5_FILIAL AND SC6.C6_NUM = SC5.C5_NUM AND 
			SC6.C6_BLQ <> 'R' AND  SC6.C6_ENTREG BETWEEN '20130101' AND '20130313' AND 
			SC6.C6_PRODUTO BETWEEN '' AND 'ZZZZZZZZZZZZZZZZZZZZZZZ' AND SC6.D_E_L_E_T_ = '' 

			INNER JOIN SC9010 SC9 ON SC9.C9_FILIAL = SC5.C5_FILIAL AND SC9.C9_PEDIDO = SC5.C5_NUM AND 
			SC9.C9_PRODUTO BETWEEN '' AND 'ZZZZZZZZZZZZZZZZZZZZZZZ' AND SC9.D_E_L_E_T_ = '' 
		WHERE
		SC5.C5_FILIAL = '05' AND 
		SC5.C5_NUM BETWEEN '' AND 'ZZZZZZ' AND  
		SC5.C5_CLIENTE BETWEEN '' AND 'ZZZZZZZZ' AND 
		SC5.C5_LOJACLI BETWEEN '' AND 'ZZ' AND 
		SC5.C5_VEND1 BETWEEN ''  AND 'ZZZZZZ' AND 
		SC5.D_E_L_E_T_ = '' 
		GROUP BY 
		SC5.C5_NUM,SC5.C5_CLIENTE,SC5.C5_LOJACLI, 
		SC5.C5_TIPO,SC5.C5_TRANSP,SC5.C5_EMISSAO,
		SC5.C5_TIPOCLI,SC5.C5_CONDPAG,SC5.C5_VEND1, 
		SC6.C6_ITEM,SC6.C6_PRODUTO,SC6.C6_DESCRI, 
		SC6.C6_XCANC,SC6.C6_QTDVEN,SC6.C6_QTDEMP, 
		SC6.C6_QTDENT,SC9.C9_QTDLIB,SC6.C6_ENTREG,SC6.C6_LOCAL, 
		SC6.C6_VALOR,SC6.C6_VALDESC,SC6.C6_PRCVEN, 
		SC6.C6_TES
	) TST
	GROUP BY PEDIDO,CLIENTE,LOJACLI,TIPO,TRANSP,DTAEMISSAO,TIPOCLI,CONDPAG,
				VENDEDOR,ITEM,PRODUTO,DESCPROD,DTAENTR,ARMAZEM,VALOR,VALDESC,PRCVEN,TES
	ORDER BY PEDIDO,PRODUTO,ITEM	