-- PAGOS
SELECT 
	SWB.WB_HAWB PROCESSO,
	SW6.W6_PO_NUM PONUM,
	SW2.W2_PO_SIGA PEDTOTVS,
	SWB.WB_FOBMOE VLRFOBUSA,
	( SWB.WB_FOBMOE * SW6.W6_TX_US_D ) VLRFOBBR,
	SW6.W6_DI_NUM NUMDI,
	SW6.W6_NF_ENT NOTA,
	SW6.W6_SE_NF SERIE,
	SW6.W6_TX_US_D TXFECH,
	SWB.WB_CA_TX TXDI,
	
	( SWB.WB_FOBMOE * SWB.WB_CA_TX ) VLRFECH,
	ROUND(( SWB.WB_FOBMOE * SW6.W6_TX_US_D ) - ( SWB.WB_FOBMOE * SWB.WB_CA_TX ),2) VARIACAO
FROM 
	SWB010 SWB
INNER JOIN SW6010 SW6 ON 
	SW6.W6_FILIAL = '05' AND
	SW6.W6_HAWB = SWB.WB_HAWB AND 
	SW6.D_E_L_E_T_ = ''
INNER JOIN SW2010 SW2 ON
	SW2.W2_FILIAL = '05' AND
	SW2.W2_PO_NUM = SW6.W6_PO_NUM AND
	SW2.W2_IMPORT = '02' AND
	SW2.D_E_L_E_T_ = ''	
INNER JOIN SW9010 SW9 ON
	SW9.W9_FILIAL = '05' AND
	SW9.W9_HAWB = SWB.WB_HAWB AND
	SW9.D_E_L_E_T_ = ''		
WHERE
	SWB.WB_FILIAL = '05' AND
	SWB.WB_FORN = '05000005' AND
	SWB.WB_LOJA = '01' AND
	SWB.WB_CA_DT BETWEEN '20120101' AND '20150101' AND
	SWB.WB_CA_DT <> '' AND
	SWB.D_E_L_E_T_ = ''
ORDER BY SWB.WB_HAWB		

-- ABERTOS
SELECT 
	SWB.WB_HAWB PROCESSO,
	SW6.W6_PO_NUM PONUM,
	SW2.W2_PO_SIGA PEDTOTVS,
	SWB.WB_FOBMOE VLRTOTAL,
	W6_DT_EMB DTAEMBARQUE,
	SW9.W9_DIAS_PA DIASPA,
	SW6.W6_NF_ENT NOTA,
	SW6.W6_SE_NF SERIE,
	SWB.WB_NUMDUP DUPLI,
	SWB.WB_PARCELA PARC
FROM 
	SWB010 SWB
INNER JOIN SW6010 SW6 ON 
	SW6.W6_FILIAL = '05' AND
	SW6.W6_HAWB = SWB.WB_HAWB AND 
	SW6.D_E_L_E_T_ = ''
INNER JOIN SW2010 SW2 ON
	SW2.W2_FILIAL = '05' AND
	SW2.W2_PO_NUM = SW6.W6_PO_NUM AND
	SW2.W2_IMPORT = '02' AND
	SW2.D_E_L_E_T_ = ''	
INNER JOIN SW9010 SW9 ON
	SW9.W9_FILIAL = '05' AND
	SW9.W9_HAWB = SWB.WB_HAWB AND
	SW9.D_E_L_E_T_ = ''	
INNER JOIN SE2010 SE2 ON
	SE2.E2_FILIAL = '' AND 
	SE2.E2_FORNECE = '05000005' AND 
	SE2.E2_LOJA = '01' AND
	SE2.E2_NUM = SWB.WB_NUMDUP AND 
	SE2.E2_PREFIXO = 'EIC' AND
	SE2.E2_BAIXA = '' AND
	SE2.D_E_L_E_T_ = ''	
WHERE
	SWB.WB_FILIAL = '05' AND
	SWB.WB_FORN = '05000005' AND
	SWB.WB_LOJA = '01' AND
	SWB.WB_FOBMOE > 0 AND
	SWB.WB_TIPOREG = '1' AND
	SWB.WB_CA_DT = '' AND
	SWB.WB_DT_VEN BETWEEN '20120101' AND '20150101' AND
	SWB.D_E_L_E_T_ = ''
ORDER BY SWB.WB_HAWB

-- COMPETENCIA


