SELECT 
	B4.B4_COD,
	B1.B1_COD,
	B1.B1_DESC,
	DA1.DA1_PRVEC1,
	( 
		SELECT 
			BV.BV_DESCRI 
		FROM 
			SBV010 BV 
		WHERE 
			BV.BV_FILIAL = ' ' AND 
			BV.BV_TABELA = B4.B4_LINHA AND 
			BV.BV_CHAVE = B1.B1_01LNGRD AND 
			BV.D_E_L_E_T_ = '' 
	) DESCLIN,
	( SELECT 
			BV.BV_DESCRI 
		FROM 
			SBV010 BV 
		WHERE 
			BV.BV_FILIAL = ' ' AND 
			BV.BV_TABELA = B4.B4_COLUNA AND 
			BV.BV_CHAVE = B1.B1_01CLGRD AND 
			BV.D_E_L_E_T_ = '' 
	) DESCCOL,
	B1.B1_STATUS,
	B1.R_E_C_N_O_ RECNOSB1	
FROM 
	SB1010 B1 
	INNER JOIN SB4010 B4 ON B4.B4_FILIAL = ' ' AND RTRIM(B4.B4_COD) = SUBSTRING(B1.B1_COD,1,6) AND B4.B4_XENVECO = '2' AND B4.B4_XUSAECO = 'S' AND B4.D_E_L_E_T_ = ''
	INNER JOIN DA1010 DA1 ON DA1.DA1_FILIAL = '' AND DA1.DA1_CODTAB = '002' AND ( DA1.DA1_REFGRD = B4.B4_COD OR DA1.DA1_CODPRO = B1.B1_COD) AND DA1.D_E_L_E_T_ = ''
WHERE 
	B1.B1_FILIAL = '' AND 
	B1.B1_XENVECO = '1' AND 
	B1.D_E_L_E_T_ = ''
ORDER BY B1.B1_COD
