-- Retorna registros duplicados
SELECT DA1_CODPRO
FROM
DA1010
WHERE
DA1_CODTAB = '001' AND
D_E_L_E_T_ = '' 
GROUP BY DA1_CODPRO
HAVING COUNT(DA1_CODPRO) > 1

-- Deleta registros duplicados
UPDATE DA1010 SET D_E_L_E_T_ = '*'
FROM 
	DA1010 DA1A 
WHERE
	DA1A.DA1_CODTAB = '001' AND 
	DA1A.D_E_L_E_T_ = '' AND 
	DA1A.R_E_C_N_O_ NOT IN ( 
	SELECT 
		MIN(R_E_C_N_O_) 
	FROM 
		DA1010 DA1B 
	WHERE 
		DA1B.DA1_CODPRO = DA1A.DA1_CODPRO AND 
		DA1B.DA1_CODTAB = DA1A.DA1_CODTAB AND
		DA1B.D_E_L_E_T_ = ''
	)


