SELECT 
 		ZZA.ZZA_NUMERO, 
 		ZZA.ZZA_SEQ,   
 		ZZA.ZZA_TIPO,   
 		ZZA.ZZA_STATUS, 
 		ZZA.ZZA_DTEMIS, 
 		ZZA.ZZA_PEDIDO, 
 		ZZA.ZZA_FILIAL, 
 		ZZA.ZZA_CLIENT, 
 		ZZA.ZZA_LOJACL, 
 		SA2.A2_NREDUZ, 
 		SA2.A2_MUN, 
 		SA2.A2_EST, 
 		SF1.F1_EMISSAO,  
 		ZZB.ZZB_PRODUT, 
 		ZZB.ZZB_ITEM, 
 		ZZB.ZZB_QTDENV, 
 		ZZB.ZZB_QTDRET, 
 		ZZB.ZZB_01PACK, 
 		SD1.D1_VUNIT, 
 		SD1.D1_GRUPO, 
 		SBM.BM_DESC, 
 		SD1.D1_LOCAL, 
 		ARM.X5_DESCRI ARMAZEM, 
 		SD1.D1_CF, 
 		NAT.X5_DESCRI CFOP 
 	FROM 
 		ZZA010 ZZA  
 	INNER JOIN SA2010 SA2 ON SA2.A2_FILIAL = '  ' AND SA2.A2_COD  = ZZA.ZZA_FORNEC  AND SA2.A2_LOJA = ZZA.ZZA_LOJA AND SA2.D_E_L_E_T_ = '' 
 	INNER JOIN SF1010 SF1 ON SF1.F1_FILIAL = '05' AND SF1.F1_DOC  = ZZA.ZZA_NOTA  AND SF1.F1_SERIE = ZZA.ZZA_SERIE AND SF1.F1_FORNECE = ZZA.ZZA_FORNEC AND SF1.F1_LOJA = ZZA.ZZA_LOJA AND SF1.D_E_L_E_T_ = ' ' 
 	INNER JOIN ZZB010 ZZB ON ZZB.ZZB_FILIAL ='05' AND ZZB.ZZB_NUMERO = ZZA_NUMERO AND ZZB.ZZB_SEQ = ZZA.ZZA_SEQ  AND ZZB.D_E_L_E_T_ = '' 
 	INNER JOIN SD1010 SD1 ON SD1.D1_FILIAL = '05' AND SD1.D1_DOC = SF1.F1_DOC AND SD1.D1_SERIE = SF1.F1_SERIE AND SD1.D1_COD = ZZB.ZZB_PRODUT AND SD1.D_E_L_E_T_ = '' 
 	INNER JOIN SBM010 SBM ON SBM.BM_FILIAL = '  ' AND SBM.BM_GRUPO = SD1.D1_GRUPO AND SBM.D_E_L_E_T_ = '' 
 	INNER JOIN SX5010 ARM ON ARM.X5_FILIAL = '  ' AND ARM.X5_CHAVE = SD1.D1_LOCAL AND ARM.X5_TABELA = 'ZD' AND ARM.D_E_L_E_T_ = ''
	INNER JOIN SX5010 NAT ON NAT.X5_FILIAL = '  ' AND NAT.X5_CHAVE = SD1.D1_CF AND NAT.X5_TABELA = '13' AND NAT.D_E_L_E_T_ = ''
 	WHERE 
 		ZZA_FILIAL = '05' 
 		AND ZZA.ZZA_NUMERO BETWEEN '   ' AND 'ZZZZZZ' 
 		AND ZZA.ZZA_PEDIDO BETWEEN '   ' AND 'ZZZZZZ' 
 		AND ZZA.ZZA_FORNEC BETWEEN '   ' AND 'ZZZZZZ' 
 		AND ZZA.ZZA_LOJA BETWEEN '  ' AND 'ZZ'  
 		AND ZZA.ZZA_DTRETO BETWEEN '   ' AND '20141231' 
 		AND ZZA.ZZA_TIPO = 'E' AND ZZA.ZZA_STATUS IN('P','R','D','C','X','F') 
 		AND ZZA.D_E_L_E_T_ = ' '  
 	ORDER BY ZZA_NUMERO,ZZB_PRODUT,ZZB_ITEM  
 	
 	
 	
 	-- SELECT * FROM ZZA010 WHERE ZZA_TIPO = 'E' AND D_E_L_E_T_ = ' ' 
 	-- SELECT * FROM SA2010 WHERE D_E_L_E_T_ = ' ' 