SELECT
	ZZA.ZZA_NUMERO,
	ZZA.ZZA_SEQ,
	ZZA.ZZA_STATUS,
	ZZA.ZZA_DTEMIS,
	ZZA.ZZA_PEDIDO,
	ZZA.ZZA_FILIAL,
	ZZA.ZZA_CLIENT, 
	ZZA.ZZA_FORNEC,
	SA1.A1_NOME ,  
	SA1.A1_MUN ,  
	SA1.A1_EST,  
--	SA2.A2_NOME ,  
--	SA2.A2_MUN ,  
--	SA2.A2_EST  
	SC5.C5_EMISSAO, 
	SC5.C5_VEND1,  
	SUP.A3_NREDUZ, 
	SC5.C5_XVEND1,
	VND.A3_NREDUZ,
	ZZB.ZZB_PRODUT,
	ZZB.ZZB_ITEM,
	ZZB.ZZB_QTDENV,  
	ZZB.ZZB_01PACK,  
	SC9.C9_PRCVEN,
	SC9.C9_GRUPO,
	SBM.BM_DESC,
	SC9.C9_LOCAL,
	ARM.X5_DESCRI,
	SC6.C6_CF,
	NAT.X5_DESCRI	
FROM  ZZA010 ZZA 
INNER JOIN SA1010 SA1 ON SA1.A1_FILIAL = '' AND SA1.A1_COD  = ZZA.ZZA_CLIENT  AND  SA1.A1_LOJA = ZZA.ZZA_LOJACL AND SA1.D_E_L_E_T_ = ' '
--INNER JOIN SA2010 SA2 ON SA2.A2_FILIAL = '' AND SA2.A2_COD  = ZZA.ZZA_FORNEC  AND  SA2.A2_LOJA = ZZA.ZZA_LOJA AND SA2.D_E_L_E_T_ = ' ' 
INNER JOIN SC5010 SC5 ON SC5.C5_FILIAL = '05' AND SC5.C5_NUM  = ZZA.ZZA_PEDIDO  AND SC5.D_E_L_E_T_ = ' '  
INNER JOIN SA3010 SUP ON SUP.A3_FILIAL = '05' AND SUP.A3_COD = SC5.C5_XVEND1 AND SUP.D_E_L_E_T_ = ' '
INNER JOIN SA3010 VND ON VND.A3_FILIAL = '05' AND VND.A3_COD = SC5.C5_VEND1 AND VND.D_E_L_E_T_ = ' '
INNER JOIN ZZB010 ZZB ON ZZB.ZZB_FILIAL = '05' AND ZZB.ZZB_NUMERO = ZZA_NUMERO AND ZZB.ZZB_SEQ = ZZA.ZZA_SEQ  AND ZZB.D_E_L_E_T_ = ' '  
INNER JOIN SC9010 SC9 ON SC9.C9_FILIAL = '05' AND SC9.C9_01PEDOP = ZZA.ZZA_NUMERO AND SC9.C9_01SEQ = ZZA.ZZA_SEQ AND SC9.C9_PRODUTO = ZZB.ZZB_PRODUT AND  SC9.D_E_L_E_T_ = ''
INNER JOIN SC6010 SC6 ON SC6.C6_FILIAL = '05' AND SC6.C6_NUM = SC9.C9_PEDIDO AND SC6.C6_PRODUTO = SC9.C9_PRODUTO AND SC9.C9_ITEM = SC6.C6_ITEM AND  SC6.D_E_L_E_T_ = ''
INNER JOIN SBM010 SBM ON SBM.BM_GRUPO = SC9.C9_GRUPO AND SBM.D_E_L_E_T_ = ''
INNER JOIN SX5010 ARM ON ARM.X5_FILIAL = '' AND ARM.X5_CHAVE = SC9.C9_LOCAL AND ARM.X5_TABELA = 'ZD' AND ARM.D_E_L_E_T_ = '' 
INNER JOIN SX5010 NAT ON NAT.X5_FILIAL = '' AND NAT.X5_CHAVE = SC6.C6_CF AND NAT.X5_TABELA = '13' AND NAT.D_E_L_E_T_ = '' 
WHERE 
	ZZA_FILIAL = '05' 
	AND ZZA.ZZA_NUMERO BETWEEN '' AND 'ZZZZZZ' 
	AND ZZA.ZZA_PEDIDO BETWEEN '' AND 'ZZZZZZ' 
	AND ZZA.ZZA_CLIENT BETWEEN '' AND 'ZZZZZZ' 
	--AND ZZA.ZZA_FORNEC BETWEEN '' AND 'ZZZZZZ' 
	AND ZZA.ZZA_DTRETO BETWEEN '' AND '20131231' 
    --AND ZZA.ZZA_TIPO = 'S' AND ZZA.ZZA_STATUS = 'P'     
    --AND ZZA.ZZA_TIPO = 'S' AND ZZA.ZZA_STATUS IN('R','D')     
    --AND ZZA.ZZA_TIPO = 'S' AND ZZA.ZZA_STATUS IN('C','X')     
    --AND ZZA.ZZA_TIPO = 'S' AND ZZA.ZZA_STATUS ='F'     
    AND ZZA.ZZA_TIPO = 'S' AND ZZA.ZZA_STATUS IN('P','R','D','C','X','F')     
    --AND ZZA.ZZA_TIPO = 'E' AND ZZA.ZZA_STATUS ='N'     
    --AND ZZA.ZZA_TIPO = 'E' AND ZZA.ZZA_STATUS IN('R','D')     
    --AND ZZA.ZZA_TIPO = 'E' AND ZZA.ZZA_STATUS IN('C','X')     
    --AND ZZA.ZZA_TIPO = 'S' AND ZZA.ZZA_STATUS IN('N','R','D','C','X')     
	AND ZZA.D_E_L_E_T_ = ' ' 
ORDER BY ZZA_NUMERO,ZZB_PRODUT,ZZB_ITEM 

--SELECT * FROM SX5010 WHERE X5_TABELA = 'ZD' AND D_E_L_E_T_ = ''
--SELECT * FROM SBM010 WHERE D_E_L_E_T_ = ''
--SELECT * FROM ZZB010 WHERE D_E_L_E_T_ = ''