SELECT DISTINCT
	E2_FILORIG									FILIAL,
	E2_PREFIXO 									PREFIXO,
	E2_NUM 										TITULO,
	E2_PARCELA 									PARCELA,
	E2_TIPO 									TIPO,
	E2_NATUREZ 									NATUREZ,
	E2_FORNECE									FORNECE,
	E2_LOJA										LOJA,
	E2_NOMFOR									NOMEFOR,
	E2_FORMPAG									FORMAPAG,
	E2_HIST										HISTORICO,
	E2_EMISSAO 									DTEMISSAO,
	E2_VENCREA 									DTVENCREA,
	E2_VALOR 									VLR_TIT,
	E2_SALDO 									VLR_SAL,
	(E2_SALDO+E2_JUROS+E2_ACRESC)-E2_DECRESC 	VLR_LIQ,
	A2_BANCO									BANCO,
	A2_AGENCIA									AGENCIA,
	A2_NUMCON 									CONTA, 
	A2_XDIGCC 									DIGITO, 
	E2_NUMBCO									BOLETO,
	E2_NUMBOR									BORDERO,
	E2_IRRF										IRRF,
	E2_INSS										INSS,
	E2_COFINS									COFINS,
	E2_PIS										PIS,
	E2_CSLL										CSLL,
	F1_SERIE  									SERIE, 
	F1_DOC  									DOCUMENTO, 
	F1_XARQ2 									LINK, 
	ED_CONTA 									CCONTABIL, 
	CT1_DESC01 							        DESCCONTA, 
	D1_CC 							        	CCUSTO, 
	CTT_DESC01 							        DESCCUSTO 
FROM SE2010 SE2 (NOLOCK) 
	INNER JOIN SA2010 SA2 (NOLOCK) ON A2_FILIAL  = '  ' AND A2_COD = E2_FORNECE AND A2_LOJA = E2_LOJA  AND SA2.D_E_L_E_T_ = ' ' 
	LEFT  JOIN SF1010 SF1 (NOLOCK) ON F1_FILIAL  = E2_FILORIG AND F1_SERIE = E2_PREFIXO AND F1_DOC = E2_NUM AND F1_FORNECE = E2_FORNECE AND F1_LOJA = E2_LOJA AND SF1.D_E_L_E_T_ = ' ' 
	INNER JOIN SED010 SED (NOLOCK) ON ED_FILIAL  = '  ' AND ED_CODIGO = E2_NATUREZ AND SED.D_E_L_E_T_ = ' ' 
	INNER JOIN CT1010 CT1 (NOLOCK) ON CT1_FILIAL = '  ' AND ED_CONTA = CT1_CONTA AND CT1.D_E_L_E_T_ = ' ' 
	LEFT  JOIN SD1010 SD1 (NOLOCK) ON D1_FILIAL = '01' AND D1_FILIAL  = E2_FILORIG AND D1_DOC = E2_NUM AND D1_SERIE = E2_PREFIXO AND D1_FORNECE = E2_FORNECE AND F1_LOJA = E2_LOJA AND SD1.D_E_L_E_T_ = ' ' 
	LEFT  JOIN CTT010 CTT (NOLOCK) ON CTT_FILIAL = '  ' AND CTT_CUSTO = D1_CC AND ED_CONTA = CT1_CONTA AND CTT.D_E_L_E_T_ = ' ' 
	WHERE 
				E2_FILORIG 	BETWEEN '01' AND '01' AND
				E2_PREFIXO	BETWEEN '' AND 'ZZZ' AND
				E2_NUM 		BETWEEN '000000016' AND '000000016' AND
				E2_PARCELA	BETWEEN '' AND 'ZZ' AND
				E2_TIPO		BETWEEN '' AND 'ZZZ' AND
				E2_FORNECE	BETWEEN '' AND 'ZZZZZZ' AND
				E2_LOJA		BETWEEN '' AND 'ZZ' AND
				E2_EMISSAO  BETWEEN '20150901' AND '20160430' AND
				E2_VENCREA  BETWEEN '20160121' AND '20160121' AND
				E2_SALDO > 0      AND
				SE2.D_E_L_E_T_ = ' '
	ORDER BY E2_FILORIG,E2_PREFIXO,E2_NUM,E2_PARCELA,E2_TIPO,E2_FORNECE,E2_LOJA