SELECT * FROM NCM_LOGCOMEX order by recno

DELETE FROM NCM_LOGCOMEX

DBCC CHECKIDENT('NCM_LOGCOMEX', RESEED, 0)

ALTER TABLE NCM_LOGCOMEX ALTER COLUMN  importadorEndereco VARCHAR(200)
ALTER TABLE NCM_LOGCOMEX ALTER COLUMN  exportadorEndereco VARCHAR(200)
