ALTER DATABASE AP11
SET EMERGENCY
USE AP11
go 
sp_dboption 'AP11', 'dbo Use Only', false


ALTER DATABASE AP11
SET SINGLE_USER


DBCC CHECKDB ('AP11',REPAIR_ALLOW_DATA_LOSS)
go

sp_dboption 'AP11', 'dbo Use Only', false

ALTER DATABASE AP11
SET MULTI_USER