SELECT 
		C7_FILIAL,
		C7_NUM, 
		C7_XORDERN, 
		C7_ITEM, 
		C7_PRODUTO, 
		B1_GRTRIB, 
		A2_GRPTRIB, 
		C7_PICM,
		A2.A2_EST,
        CASE 
			WHEN A2.A2_EST = F7A.F7_EST
				THEN F7A.F7_EST
			WHEN A2.A2_EST <> F7B.F7_EST	
				THEN F7B.F7_EST
			END
				EST_TRIB,
		F7A.F7_ALIQINT ALIQINT_EST, 
		F7B.F7_ALIQEXT ALIQINT_EXT 
	FROM 
		SC7030 C7 
	INNER JOIN SA2030 A2 ON A2_FILIAL = '' AND A2_COD = C7_FORNECE AND A2_LOJA = C7_LOJA  AND A2.D_E_L_E_T_ = ' ' 
	INNER JOIN SB1030 B1 ON B1_FILIAL = '' AND B1_COD = C7_PRODUTO AND B1.D_E_L_E_T_ = ' '  
	LEFT JOIN SF7030 F7A ON F7A.F7_FILIAL = C7_FILIAL  
		AND F7A.F7_GRTRIB = B1_GRTRIB  
		AND F7A.F7_GRPCLI = A2_GRPTRIB  
		AND F7A.D_E_L_E_T_ = ' '  
		AND F7A.F7_EST = A2_EST 
	LEFT JOIN SF7030 F7B ON F7B.F7_FILIAL = C7_FILIAL 
		AND F7B.F7_GRTRIB = B1_GRTRIB 
		AND F7B.F7_GRPCLI = A2_GRPTRIB 
		AND F7B.D_E_L_E_T_ = ' ' 
		AND F7B.F7_EST = '**' 
	WHERE 
		C7.D_E_L_E_T_ = ' '  
		AND ((C7_PICM <> F7A.F7_ALIQINT) 
		OR (C7_PICM <> F7B.F7_ALIQEXT)) 
	ORDER BY C7_FILIAL,C7_NUM, C7_XORDERN, C7_ITEM, C7_PRODUTO 