SELECT 
	FT_EMISSAO DTAEMISS,
	SFT.FT_PDV PDV,
	SD2.D2_PICM ALIQICM,
	SUM(D2_BASEICM) BASED2, 
	SUM(D2_VALICM)  ICMD2,
	SUM(D2_TOTAL) TOTALD2,
	SUM(D2_DESCON) DESCD2,
	COUNT(DISTINCT(D2_DOC)) QTDFAT
FROM 
	SFT010 SFT
INNER JOIN SD2010 SD2 ON 
	SD2.D2_FILIAL = '03' AND 	
	SD2.D2_EMISSAO BETWEEN '20131101' AND '20131130' AND
	SD2.D2_PDV = SFT.FT_PDV AND
	SD2.D2_CLIENTE = SFT.FT_CLIEFOR AND 
	SD2.D2_LOJA = SFT.FT_LOJA AND 
	SD2.D2_DOC = SFT.FT_NFISCAL AND 
	SD2.D2_SERIE = SFT.FT_SERIE AND
	SD2.D2_COD = SFT.FT_PRODUTO AND
	SD2.D2_ITEM = SFT.FT_ITEM AND
 	SD2.D_E_L_E_T_ = ''
WHERE
	SFT.FT_TIPOMOV = 'S' AND
	SFT.FT_FILIAL = '03' AND
	SFT.FT_EMISSAO BETWEEN '20131101' AND '20131130' AND
	SFT.FT_PDV <> '' AND
	SFT.FT_DTCANC = '' AND
	SFT.D_E_L_E_T_ = '' AND
	SFT.FT_OBSERV = ''
GROUP BY FT_EMISSAO,FT_PDV,D2_PICM 
-- DELETADOS 
SELECT 
	FT_EMISSAO DTAEMISS,FT_PDV PDV,SUM(FT_BASEICM) AS BASE, SUM(FT_VALICM) AS ICM
	--D2_EMISSAO EMISSFT,SUM(D2_BASEICM) AS BASED2, SUM(D2_VALICM) AS ICMD2
FROM 
	SFT010 SFT
INNER JOIN SD2010 SD2 ON 
	SD2.D2_FILIAL = '03' AND 	
	SD2.D2_EMISSAO BETWEEN '20131101' AND '20131130' AND
	SD2.D2_PDV = SFT.FT_PDV AND
	SD2.D2_CLIENTE = SFT.FT_CLIEFOR AND 
	SD2.D2_LOJA = SFT.FT_LOJA AND 
	SD2.D2_DOC = SFT.FT_NFISCAL AND 
	SD2.D2_SERIE = SFT.FT_SERIE AND
	SD2.D2_COD = SFT.FT_PRODUTO AND
	SD2.D2_ITEM = SFT.FT_ITEM AND
 	SD2.D_E_L_E_T_ = '*'
WHERE
	SFT.FT_TIPOMOV = 'S' AND
	SFT.FT_FILIAL = '03' AND
	SFT.FT_EMISSAO BETWEEN '20131101' AND '20131130' AND
	SFT.FT_PDV <> '' AND
	SFT.FT_DTCANC <> '' AND
	SFT.D_E_L_E_T_ = '' AND
	SFT.FT_OBSERV <> ''
GROUP BY FT_EMISSAO,FT_PDV
