SELECT 
	FILIAL, 
	CONTA_CONTABIL,
	SLD_INI_DEB, 
	SLD_INI_CR, 
	SLD_ATU_DEB,  
	SLD_ATU_CR,
	SLD_ATUAL
FROM( 
	SELECT 
		CASE 
			WHEN SALDO_INI.FILIAL <> '' THEN 
				SALDO_INI.FILIAL 
			ELSE 
				SALDO_ATU.FILIAL 
		END FILIAL, 
		CT1.CT1_CONTA CONTA_CONTABIL, 
		COALESCE(SALDO_INI.SLD_INI_DEB,0) SLD_INI_DEB, 
		COALESCE(SALDO_INI.SLD_INI_CR,0) SLD_INI_CR, 
		COALESCE(SALDO_ATU.SLD_ATU_DEB,0) SLD_ATU_DEB, 
		COALESCE(SALDO_ATU.SLD_ATU_CR,0) SLD_ATU_CR,
		( COALESCE(SALDO_INI.SLD_INI_DEB,0) - COALESCE(SALDO_INI.SLD_INI_CR,0) ) - 
		CASE  
			WHEN COALESCE(SALDO_ATU.SLD_ATU_DEB,0) < COALESCE(SALDO_ATU.SLD_ATU_CR,0) 
				THEN ( COALESCE(SALDO_ATU.SLD_ATU_DEB,0) - COALESCE(SALDO_ATU.SLD_ATU_CR,0) ) * (-1)
				ELSE ( COALESCE(SALDO_ATU.SLD_ATU_DEB,0) - COALESCE(SALDO_ATU.SLD_ATU_CR,0) ) * (-1)
		END SLD_ATUAL
	FROM 
		CT1010 CT1 
		OUTER APPLY( 
					SELECT 
						COALESCE(CQ1.CQ1_FILIAL,'') FILIAL, 
						SUM(CQ1.CQ1_DEBITO) SLD_INI_DEB, 
						SUM(CQ1.CQ1_CREDIT) SLD_INI_CR 
					FROM 
						CQ1010 CQ1 
					WHERE 
						CQ1.CQ1_FILIAL = '0101' AND 
						CQ1.CQ1_CONTA  = CT1.CT1_CONTA AND 
						CQ1.CQ1_MOEDA = '01' AND 
						CQ1.CQ1_TPSALD = '1' AND 
						(	
							CASE WHEN 	SUBSTRING(CQ1.CQ1_CONTA,1,1) NOT IN('3','4','9') THEN CQ1.CQ1_DATA else '999999999' end  < '20250631' OR 
							CASE WHEN 	SUBSTRING(CQ1.CQ1_CONTA,1,1) IN('1','3','4','9')  THEN CQ1.CQ1_DATA else '999999999' end  between '20241231' and '20250531' 
						)
						AND	CQ1.D_E_L_E_T_ = '' 
						GROUP BY CQ1.CQ1_FILIAL 
			) SALDO_INI 
						
			OUTER APPLY( 
						SELECT 
							COALESCE(CQ1.CQ1_FILIAL,'') FILIAL, 
							SUM(CQ1.CQ1_DEBITO) SLD_ATU_DEB, 
							SUM(CQ1.CQ1_CREDIT) SLD_ATU_CR 
						FROM 
							CQ1010 CQ1 
						WHERE 
							CQ1.CQ1_FILIAL = '0101' AND 
							CQ1.CQ1_CONTA  = CT1.CT1_CONTA AND 
							CQ1.CQ1_MOEDA = '01' AND 
							CQ1.CQ1_TPSALD = '1' AND 
							CQ1.CQ1_DATA BETWEEN '20250601' AND '20250630' AND 
							CQ1.D_E_L_E_T_ = '' 
						GROUP BY CQ1.CQ1_FILIAL 
			) SALDO_ATU 
		WHERE 
			CT1.CT1_CLASSE <> '1' and 
			CT1.CT1_CONTA = '1.010102001'
	) SAFX02 
 WHERE 	
	SLD_INI_DEB > 0 OR 
	SLD_INI_CR > 0 OR 
	SLD_ATU_DEB > 0 OR 
	SLD_ATU_CR > 0 
ORDER BY CONTA_CONTABIL 


--1.010102001
--1.010201003 