SELECT
	CODIGO,
	NOMEPAI,  
	CODSKU,
	NOMESKU,   
	CODBARRA,  
	ARMAZEM,  
	UNIDADE,   
	CODMARCA,   
	PESOLIQ,    
	ALTPRD,    
	ALTEMB,    
	PROPRD,    
	PROEMB,     
	LARGPRD,  
	LARGEMB,  
	IDPROD,   
	IDSKU,  
	STATUSPRD,
	COR,
	TAMANHO,
	PRCVEN,   
	RECNOSB5,
	RECNOWS6
FROM
(
	SELECT   
		B5.B5_COD CODIGO, 
		B5.B5_XNOMPRD NOMEPAI, 
		B5.B5_COD CODSKU,  
		B1.B1_DESC NOMESKU,   
		B1.B1_CODBAR CODBARRA,  
		B1.B1_LOCPAD ARMAZEM,  
		B1.B1_UM UNIDADE,   
		AY2.AY2_IDMARC CODMARCA,   
		B5.B5_PESO PESOLIQ,    
		B5.B5_XALTPRD ALTPRD,    
		B5.B5_XALTEMB ALTEMB,    
		B5.B5_XPROPRD PROPRD,    
		B5.B5_XPROEMB PROEMB,     
		B5.B5_XLARPRD LARGPRD,  
		B5.B5_XLAREMB LARGEMB,  
		B5.B5_XIDPROD IDPROD,   
		B5.B5_XIDSKU IDSKU,  
		B5.B5_STATUS STATUSPRD,
		B1.B1_ZZCOR COR,
		B1.B1_ZZTAM TAMANHO,
		ISNULL(DA1.DA1_PRCVEN,0) PRCVEN,   
		B5.R_E_C_N_O_ RECNOSB5,
		0 RECNOWS6
	FROM 
		SB5010 B5  
		INNER JOIN SB1010 B1 ON B1.B1_FILIAL = '0101' AND B1.B1_COD = B5.B5_COD AND B1.B1_MSBLQL <> '1' AND B1.D_E_L_E_T_ = ''
		INNER JOIN AY2010 AY2 ON AY2.AY2_FILIAL = '' AND AY2.AY2_CODIGO = B5.B5_XCODMAR AND AY2.D_E_L_E_T_ = ''
		LEFT OUTER JOIN DA1010 DA1 ON DA1.DA1_FILIAL = '01  ' AND DA1.DA1_CODTAB = '001' AND DA1.DA1_CODPRO = B1.B1_COD AND DA1.D_E_L_E_T_ = ''
	WHERE
		B5.B5_FILIAL = '0101' AND  
		B5.B5_XUSAECO = 'S' AND 
		B5.B5_XENVECO = '2' AND 
		B5.B5_XENVSKU = '1' AND 
		B5.D_E_L_E_T_ = ' '
	
	UNION 

	SELECT   
		WS5.WS5_CODPRD CODIGO,
		WS5.WS5_NOMPRD NOMEPAI,
		B1.B1_COD CODSKU,  
		B1.B1_DESC NOMESKU,   
		B1.B1_CODBAR CODBARRA,  
		B1.B1_LOCPAD ARMAZEM,  
		B1.B1_UM UNIDADE,   
		AY2.AY2_IDMARC CODMARCA,   
		B1.B1_PESO PESOLIQ,    
		WS5.WS5_ALTPRD ALTPRD,    
		WS5.WS5_ALTEMB ALTEMB,    
		WS5.WS5_PROPRD PROPRD,    
		WS5.WS5_PROEMB PROEMB,     
		WS5.WS5_LARPRD LARGPRD,  
		WS5.WS5_LAREMB LARGEMB,  
		WS5.WS5_IDPROD IDPROD,   
		WS6.WS6_IDSKU IDSKU,  
		WS5.WS5_STATUS STATUSPRD,   
		WS6.WS6_COR COR,
		WS6.WS6_TAMANH TAMANHO,   
		ISNULL(DA1.DA1_PRCVEN,0) PRCVEN,
		0 RECNOSB5,
		WS6.R_E_C_N_O_ RECNOWS6
	FROM 
		WS5010 WS5
		INNER JOIN WS6010 WS6 ON WS6.WS6_FILIAL = '' AND WS6.WS6_CODPRD = WS5.WS5_CODPRD AND WS6.WS6_ENVECO = '1' AND WS6.D_E_L_E_T_ = ''  
		INNER JOIN SB1010 B1 ON B1.B1_FILIAL = '0101' AND B1.B1_COD = WS6.WS6_CODSKU AND B1.B1_MSBLQL <> '1' AND B1.D_E_L_E_T_ = ''
		INNER JOIN AY2010 AY2 ON AY2.AY2_FILIAL = '' AND AY2.AY2_CODIGO = WS5.WS5_CODMA AND AY2.D_E_L_E_T_ = ''
		LEFT OUTER JOIN DA1010 DA1 ON DA1.DA1_FILIAL = '01  ' AND DA1.DA1_CODTAB = '001' AND DA1.DA1_CODPRO = WS6.WS6_CODSKU AND DA1.D_E_L_E_T_ = ''
	WHERE
		WS5.WS5_FILIAL = '' AND  
		WS5.WS5_ENVECO = '2' AND 
		WS5.WS5_USAECO = 'S' AND 
		WS5.D_E_L_E_T_ = '' 
	 
) SKU
ORDER BY CODIGO
