-- FORNECEDOR
SELECT A2_GRUPO,* FROM SA2010 WHERE A2_COD = '05000005' AND D_E_L_E_T_ = ''
-- UNIDADE REQUISITANTE CENTRO DE CUSTO
SELECT * FROM SY3010 WHERE D_E_L_E_T_ = ''
-- ITENS DE CAMBIO
SELECT WB_PO_DI,WB_TIPOREG,* FROM SWB010 WHERE D_E_L_E_T_ = ''
-- PERCENTUAIS DE CENTRO DE CUSTO
SELECT * FROM SYS010 WHERE D_E_L_E_T_ = ''
-- CAPA DECLARA플O DE IMPORTA플O
SELECT * FROM SW6010 WHERE D_E_L_E_T_ = ''
-- ITENS DECLARA플O DE IMPORTA플O
SELECT * FROM SW7010 WHERE D_E_L_E_T_ = ''
-- CAPA DE INVOICES
SELECT * FROM SW9010 WHERE D_E_L_E_T_ = ''
-- CAPA DE P.O
SELECT * FROM SW2010 WHERE D_E_L_E_T_ = ''
-- IMPORTADORES / CONSIGNATORIOS
SELECT * FROM SYT010 WHERE D_E_L_E_T_ = ''