SELECT 
	ZZA.ZZA_CODPRO, 
	B1.B1_DESC, 
	ZZA.ZZA_PALLET, 
	ZZA.ZZA_NUMLOT, 
	ZZA.ZZA_QUANT, 
	ZZA.ZZA_PALLET, 
	ZZA.ZZA_BAIXA, 
	ZZA.ZZA_NUMCX, 
	ZZA.ZZA_NUMNF, 
	ZZA.ZZA_ITEMNF ,
	ZZA.ZZA_NFSAID,
	ZZA.ZZA_SERSAI
FROM 
	ZZA030 ZZA 
	INNER JOIN SB1030 B1 ON B1.B1_FILIAL = '    ' AND B1.B1_COD = ZZA.ZZA_CODPRO AND B1.D_E_L_E_T_ = '' 
WHERE 
	ZZA.ZZA_FILIAL  = '0301' AND 
	ZZA.ZZA_CODBAR = '7898941898915' AND 
	ZZA.ZZA_NUMNF = '000196909' AND 
	ZZA.ZZA_ITEMNF = '0004' AND 
	ZZA.ZZA_NUMLOT = 'TLLI198         ' AND 
	ZZA.ZZA_CODPRO = '7127' AND 
	ZZA.ZZA_NUMCX = '2359' AND 
	ZZA.D_E_L_E_T_ = '' 
