SELECT 
	UA.UA_NUM,
	A1.R_E_C_N_O_ clienteId,
	A1.A1_CGC cnpjCpf,
	A3.R_E_C_N_O_ vendedorId,
	E4.R_E_C_N_O_ condicaoId,
	A4.R_E_C_N_O_ transportadoraId,
	UA.UA_TPFRETE tipoFrete, 
	UA.UA_FRETE frete,
	UA.UA_XVOLUME volume,
	UA.UA_XPESLIQ pesoLiquido,
	UA.UA_XPESBRU pesoBruto,
	UA.UA_XCUBTOT cubagemTotal,
	UA.UA_XMDC margem,
	UA.UA_XAPROVA aprovador,
	UA.UA_XDTAPRO dtAprovacao,
	0 subTotal,
	0 total,
	COALESCE(CAST(CAST(UA.UA_XOBSCO AS BINARY) AS VARCHAR),'') obsComercial,
	COALESCE(CAST(CAST(UA.UA_XOBSFIN AS BINARY) AS VARCHAR),'') obsFinanceira,
	COALESCE(CAST(CAST(UA.UA_XOBSLO AS BINARY) AS VARCHAR),'') obsEntrega,
	COALESCE(CAST(CAST(UA.UA_XOBSEXP AS BINARY) AS VARCHAR),'') obsPedido,
	UB.UB_ITEM item,
	B1.R_E_C_N_O_ productId,
	UB.UB_QUANT quantidade,
	UB.UB_VRUNIT valorUnitario,
	UB.UB_PRCTAB valorTabela,
	UB.UB_XNVLOTE trocaLote,
	UB.UB_LOTE lote
FROM 
	SUA040 UA 
	INNER JOIN SA1040 A1 ON A1.A1_FILIAL = '' AND A1.A1_COD = UA.UA_CLIENTE AND A1.A1_LOJA = UA.UA_LOJA AND A1.D_E_L_E_T_ = ''
	INNER JOIN SA3040 A3 ON A3.A3_FILIAL = '' AND A3.A3_COD = UA.UA_VEND AND A3.D_E_L_E_T_ = ''
	INNER JOIN SA4040 A4 ON A4.A4_FILIAL = '' AND A4.A4_COD = UA.UA_TRANSP AND A4.D_E_L_E_T_ = ''
	INNER JOIN SE4040 E4 ON E4.E4_FILIAL = '' AND E4.E4_CODIGO = UA.UA_CONDPG AND E4.D_E_L_E_T_ = ''
	INNER JOIN SUB040 UB ON UB.UB_FILIAL = UA.UA_FILIAL AND UB.UB_NUM = UA.UA_NUM AND UB.D_E_L_E_T_ = ''
	INNER JOIN SB1040 B1 ON B1.B1_FILIAL = '' AND B1.B1_COD = UB.UB_PRODUTO AND B1.D_E_L_E_T_ = ''
WHERE
	UA_FILIAL = '0404' AND 
	UA_VEND = '000129' AND 
	UA_EMISSAO >= '20220801' AND
	UA_NUMSC5 <> '' AND 
	UA.UA_NUM = '218421' AND 
	UA.D_E_L_E_T_ = ''
ORDER BY UA.UA_NUM,UB.UB_ITEM