CREATE TRIGGER IDWS_CTT_INSERT 
ON CTT010
FOR INSERT
AS 
BEGIN 
	DECLARE 
	@VALOR	INT, 
	@RECNO	INT 
	SELECT @VALOR = ( SELECT MAX(CTT_XIDWS) WSID FROM CTT010 ), @RECNO = R_E_C_N_O_  FROM INSERTED 
	UPDATE CTT010 SET CTT_XIDWS = @VALOR + 1 FROM CTT010 CTT WHERE CTT.R_E_C_N_O_ = @RECNO 
END

CREATE TRIGGER IDWS_CT1_INSERT 
ON CT1010
FOR INSERT
AS 
BEGIN 
	DECLARE 
	@VALOR	INT, 
	@RECNO	INT 
	SELECT @VALOR = ( SELECT MAX(CT1_XIDWS) WSID FROM CT1010 ), @RECNO = R_E_C_N_O_  FROM INSERTED 
	UPDATE CT1010 SET CT1_XIDWS = @VALOR + 1 FROM CT1010 CT1 WHERE CT1.R_E_C_N_O_ = @RECNO 
END

CREATE TRIGGER IDWS_SA2_INSERT 
ON SA2010
FOR INSERT
AS 
BEGIN 
	DECLARE 
	@VALOR	INT, 
	@RECNO	INT 
	SELECT @VALOR = ( SELECT MAX(A2_XIDWS) WSID FROM SA2010 ), @RECNO = R_E_C_N_O_  FROM INSERTED 
	UPDATE SA2010 SET A2_XIDWS = @VALOR + 1 FROM SA2010 A2 WHERE A2.R_E_C_N_O_ = @RECNO 
END

CREATE TRIGGER IDWS_SED_INSERT 
ON SED010
FOR INSERT
AS 
BEGIN 
	DECLARE 
	@VALOR	INT, 
	@RECNO	INT 
	SELECT @VALOR = ( SELECT MAX(ED_XIDWS) WSID FROM SED010 ), @RECNO = R_E_C_N_O_  FROM INSERTED 
	UPDATE SED010 SET ED_XIDWS = @VALOR + 1 FROM SED010 ED WHERE ED.R_E_C_N_O_ = @RECNO 
END

CREATE TRIGGER IDWS_SB1_INSERT 
ON SB1010
FOR INSERT
AS 
BEGIN 
	DECLARE 
	@VALOR	INT, 
	@RECNO	INT 
	SELECT @VALOR = ( SELECT MAX(B1_XIDWS) WSID FROM SB1010 ), @RECNO = R_E_C_N_O_  FROM INSERTED 
	UPDATE SB1010 SET B1_XIDWS = @VALOR + 1 FROM SB1010 B1 WHERE B1.R_E_C_N_O_ = @RECNO 
END