-- PRODUTO PAI
CREATE
TRIGGER TGR_SB4_CATALOGO 
ON SB4010
FOR UPDATE AS
BEGIN
	DECLARE 
	@RECNO 		INT
	SELECT @RECNO = R_E_C_N_O_, @CODPROD = B4_COD FROM INSERTED 
	UPDATE SB4010 SET B4_XECEXP = '',B4_XENVECO = '1' WHERE R_E_C_N_O_ = @RECNO
END

-- SKU
ALTER TRIGGER [dbo].[TGR_SB1_CATALOGO] 
 ON [dbo].[SB1010] 
 FOR UPDATE AS 
 BEGIN 
	IF @@ROWCOUNT = 0 RETURN 
	   DECLARE @RECNO INT, @CODPAI VARCHAR(11)
 		SELECT @CODPAI = B1_01PRODP,@RECNO = R_E_C_N_O_ FROM INSERTED 
		IF NOT UPDATE(B1_XENVECO) 
			BEGIN 		
			UPDATE SB4010 SET B4_XECEXP = '',B4_XENVECO = '1' WHERE B4_COD = @CODPAI 
			UPDATE SB1010 SET B1_XENVECO = '1' WHERE R_E_C_N_O_ = @RECNO 
 	END 
 END 

-- TABELA DE PRECO
CREATE
TRIGGER TGR_DA1_CATALOGO 
ON DA1010
FOR UPDATE AS
BEGIN
	DECLARE 
	@CODPAI	VARCHAR(11)
	SELECT @CODPAI = DA1_REFGRD FROM INSERTED 
	UPDATE SB1010 SET B1_XENVECO = '1' WHERE B1_01PRODP = @CODPAI
	UPDATE SB4010 SET B4_XECEXP = '',B4_XENVECO = '1' WHERE B4_COD = @CODPAI
END

--ESTOQUE
CREATE
TRIGGER TGR_SB2_CATALOGO 
ON SB2010
FOR UPDATE AS
BEGIN
	DECLARE 
	@CODPROD	VARCHAR(16)
	SELECT @CODPROD = B2_COD FROM INSERTED 
	UPDATE SB1010 SET B1_XENVECO = '1' WHERE B1_COD = @CODPROD
END

ALTER  TRIGGER [dbo].[TGR_B2_SALDO] 
 ON [dbo].[SB2010] 
 FOR UPDATE AS 
 BEGIN 
 	DECLARE 
 	@RECNO INT 
 	IF NOT UPDATE (B2_XECEXP) BEGIN 
 		SELECT @RECNO = R_E_C_N_O_ FROM INSERTED 
 		UPDATE SB2010 SET B2_XECEXP = ' ' WHERE R_E_C_N_O_ = @RECNO 
 	END 
 END 