-- PRODUTO PAI
CREATE
TRIGGER TGR_SB4_CATALOGO 
ON SB4010
FOR UPDATE AS
BEGIN
	DECLARE 
	@RECNO 		INT
	SELECT @RECNO = R_E_C_N_O_, @CODPROD = B4_COD FROM INSERTED 
	UPDATE SB4010 SET B4_XECEXP = '',B4_XENVECO = '1' WHERE R_E_C_N_O_ = @RECNO
END

-- SKU
CREATE
TRIGGER TGR_SB1_CATALOGO 
ON SB1010
FOR UPDATE AS
BEGIN
	DECLARE 
	@RECNO 	INT,
	@CODPAI	VARCHAR(16)
	SELECT @RECNO = R_E_C_N_O_, @CODPAI = B1_01PRODP FROM INSERTED 
	UPDATE SB1010 SET B1_XENVECO = '1' WHERE R_E_C_N_O_ = @RECNO
	UPDATE SB4010 SET B4_XECEXP = '',B4_XENVECO = '1' WHERE B4_COD = @CODPROD
END

-- TABELA DE PRECO
CREATE
TRIGGER TGR_DA1_CATALOGO 
ON DA1010
FOR UPDATE AS
BEGIN
	DECLARE 
	@CODPAI	VARCHAR(11)
	SELECT @CODPAI = DA1_REFGRD FROM INSERTED 
	UPDATE SB1010 SET B1_XENVECO = '1' WHERE B1_01PRODP = @CODPAI
	UPDATE SB4010 SET B4_XECEXP = '',B4_XENVECO = '1' WHERE B4_COD = @CODPAI
END

--ESTOQUE
CREATE
TRIGGER TGR_SB2_CATALOGO 
ON SB2010
FOR UPDATE AS
BEGIN
	DECLARE 
	@CODPROD	VARCHAR(16)
	SELECT @CODPROD = B2_COD FROM INSERTED 
	UPDATE SB1010 SET B1_XENVECO = '1' WHERE B1_COD = @CODPROD
END