SELECT 
	PO_NUM, 
	FORNECEDOR, 
	DATA_PO, 
	DT_EMBARQUE, 
	NUM_DI, 
	NF_ENTRADA, 
	STATUS_PO, 
	TOTAL_PO, 
    TAXA_DI, 
	SALDO 
 FROM 
 ( 
	SELECT 
		W6.W6_HAWB PO_NUM, 
		A2.A2_NREDUZ FORNECEDOR, 
		W2.W2_PO_DT DATA_PO, 
		COALESCE(W6.W6_DT_EMB,'') DT_EMBARQUE, 
		COALESCE(W6.W6_DI_NUM,'') NUM_DI, 
		COALESCE(W6.W6_NF_ENT,'') NF_ENTRADA, 
        SUBSTRING(W2.W2_PO_DT,5,2) + '_' + SUBSTRING(W2.W2_PO_DT,1,4) MES_ANO, 
    	CASE 
			WHEN COALESCE(W6.W6_DT_EMB,'') = '' THEN 
				'nao_embarcado' 
			WHEN COALESCE(W6.W6_DT_EMB,'') <> '' AND COALESCE(W6.W6_NF_ENT,'') = '' THEN 
				'embarcado' 
			WHEN COALESCE(W6.W6_DT_EMB,'') <> '' AND COALESCE(W6.W6_NF_ENT,'') <> '' THEN 
				'finalizado' 
		END	STATUS_PO, 
		( W2.W2_FOB_TOT + W2.W2_OUT_DES ) TOTAL_PO, 
        W6.W6_TX_US_D TAXA_DI, 
		( ( W2.W2_FOB_TOT + W2.W2_OUT_DES ) - COALESCE(SWB.SALDO_PO,0) ) VALOR_LIQ, 
	    ( ( W2.W2_FOB_TOT + W2.W2_OUT_DES ) - COALESCE(SWB.SALDO_PO,0) ) SALDO 
	FROM 
		SW6040 W6 
        INNER JOIN SW2040 W2 ON W2.W2_FILIAL = W6.W6_FILIAL AND W2.W2_PO_NUM = W6.W6_PO_NUM AND W2.D_E_L_E_T_ = '' 
		INNER JOIN SA2040 A2 ON A2.A2_FILIAL = '' AND A2.A2_COD = W2.W2_FORN AND A2.A2_LOJA = W2.W2_FORLOJ AND A2.D_E_L_E_T_ = '' 
		OUTER APPLY( 
					SELECT 
						SUM(E2.E2_SALDO) SALDO_PO 
					FROM 
						SWB040 WB  
                        LEFT JOIN SE2040 E2 ON E2.E2_FILIAL = WB.WB_FILIAL AND E2.E2_NUM = WB.WB_NUMDUP AND E2.E2_PREFIXO = WB.WB_PREFIXO AND E2.E2_PARCELA = WB.WB_PARCELA AND E2.D_E_L_E_T_ = '' 
					WHERE 
						WB.WB_FILIAL = W2.W2_FILIAL AND 
						WB.WB_HAWB = W6.W6_HAWB AND 
						WB.WB_NUMDUP <> '' AND 
						WB.D_E_L_E_T_ = '' 
					GROUP BY WB.WB_FILIAL,WB.WB_HAWB 
					) SWB 
	WHERE 
		W6.W6_FILIAL BETWEEN '    ' AND '0404' AND 
		W6.W6_HAWB BETWEEN '' AND 'ZZZZZZZZZZZZZZZ' AND 
		W2.W2_FORN BETWEEN '' AND 'ZZZZZZ' AND 
		W2.W2_FORLOJ BETWEEN '    ' AND 'ZZZZ' AND 
		W2.W2_PO_DT BETWEEN '20250101' AND '20260131' AND 
		W6.D_E_L_E_T_ = '' 
 )VAR_CAMB 
    WHERE 
    SALDO > 0 
 ORDER BY DATA_PO 