WITH META_MENSAL AS (
	SELECT 
		SUBSTRING(CT.CT_DATA, 5,4) AS MES_DIA,
		SUM(CT.CT_VALOR) AS TOTAL_META
	FROM SCT040 CT WITH(NOLOCK)
	WHERE 
		CT.CT_FILIAL = '' 
		AND CT.CT_DATA BETWEEN '20250401' AND '20250431'
		AND CT.D_E_L_E_T_ = ''
	GROUP BY SUBSTRING(CT.CT_DATA, 5,4)
),
FATURAMENTO_DIARIO AS (
	SELECT 
		SUBSTRING(FT.FT_ENTRADA, 5,4) AS MES_DIA,
		SUM(CASE	
				WHEN FT.FT_NATOPER IN ('008','041','043') THEN FT.FT_TOTAL
				WHEN FT.FT_NATOPER = '012' THEN -1 * FT.FT_TOTAL
				ELSE 0
			END
		) AS TOTAL_FATURADO
	FROM 
		SFT040 FT WITH(NOLOCK)
		INNER JOIN SF2040 F2 WITH(NOLOCK)
		ON F2.F2_FILIAL = FT.FT_FILIAL 
		AND F2.F2_DOC + F2.F2_SERIE = 
			CASE 
				WHEN FT.FT_NFORI = '' THEN FT.FT_NFISCAL + FT.FT_SERIE 
				ELSE FT.FT_NFORI + FT.FT_SERORI 
			END 
		AND F2.D_E_L_E_T_ = ''
	INNER JOIN SA3040 A3 WITH(NOLOCK)
		ON A3.A3_FILIAL = '' 
		AND A3.A3_COD = F2.F2_VEND1 
		AND A3.A3_COD NOT IN ('000033','000333') 
		AND A3.A3_TIPO = 'I' 
		AND A3.A3_MSBLQL <> '1' 
		AND A3.D_E_L_E_T_ = ''
	WHERE 
		FT.FT_ENTRADA BETWEEN '20250331' AND '20250429'
		AND FT.FT_DTCANC = ''
		AND FT.FT_NATOPER IN ('008','012','041','043')
		AND FT.D_E_L_E_T_ = ''
	GROUP BY SUBSTRING(FT.FT_ENTRADA, 5,4)
)
SELECT 
	SUBSTRING(FM.MES_DIA,1,2) + '-' + SUBSTRING(FM.MES_DIA,3,2) MES_DIA,
	ISNULL(FM.TOTAL_FATURADO, 0) AS TOTAL_FATURADO
FROM 
	FATURAMENTO_DIARIO FM
ORDER BY FM.MES_DIA;


--SELECT * FROM ZZW040 WHERE ZZW_MESANO = '062025'
--SELECT * FROM SZ4040 WHERE Z4_ANO = '2025' AND Z4_MES = '07'