CREATE VIEW [dbo].[LOCAL_CLIENTES] AS
	SELECT
		SA1.*,

		CASE 
			WHEN SA1.A1_MSEXP IS NULL OR LTRIM(RTRIM(SA1.A1_MSEXP)) = '' THEN 1
			WHEN TRY_CONVERT(DATE, SA1.A1_MSEXP, 112) IS NULL THEN 1
			WHEN CAST(SA1.S_T_A_M_P_ AS DATE) > TRY_CONVERT(DATE, SA1.A1_MSEXP, 112) THEN 1
			ELSE 0
		END AS INTEG_PENDENTE

	FROM SA1040 SA1 WITH (NOLOCK)

	WHERE
		SA1.S_T_A_M_P_ >= DATEADD(HOUR, -1, GETDATE())
		AND SA1.D_E_L_E_T_ = ''
GO