SELECT
	INTERNAL_ID,
	NAME,
	DOCUMENT,
	EMAIL_NFE,
	EMAIL,
	PURCHASER_NAME, 
	ATTACHMENT_LINK,
	ATTACHMENT_EXPIRATION_DATE
FROM 
(
	SELECT 
		A1.A1_XIDCLI INTERNAL_ID,
		A1.A1_NOME NAME,
		A1.A1_CGC DOCUMENT,
		A1.A1_EMAIL EMAIL_NFE,
		A1.A1_EMLCONT EMAIL,
		CASE 
			WHEN COALESCE(U5.U5_CONTAT,'') <> '' THEN 
				U5.U5_CONTAT
			ELSE 
				A1.A1_CONTATO
		END PURCHASER_NAME, 
		A1.A1_XLICA ATTACHMENT_LINK,
		A1.A1_XVLD ATTACHMENT_EXPIRATION_DATE
	FROM 
		SA1010 A1
		LEFT JOIN AC8010 AC8 ON AC8.AC8_FILIAL = A1.A1_FILIAL AND AC8.AC8_CODENT = A1.A1_COD + A1.A1_LOJA AND AC8.D_E_L_E_T_ = ''
		LEFT JOIN SU5010 U5 ON U5.U5_FILIAL = AC8.AC8_FILIAL AND U5.U5_CODCONT =  AC8.AC8_CODCON  AND U5.D_E_L_E_T_ = ''
	WHERE 
		A1.A1_FILIAL = '' AND 
		A1.A1_CGC = '10692530000100' AND 
		A1.D_E_L_E_T_ = ''
) EMPRESA
