SELECT
	AY2.AY2_CODIGO, 
	CAST(CAST(AY2_DESECO AS BINARY) AS VARCHAR) DESCMARCA,
	AY2.AY2_STATUS,
	AY2.R_E_C_N_O_ RECNOAY2
FROM 
	AY2010 AY2 
WHERE 
	AY2.AY2_FILIAL = '' AND 
	AY2.AY2_ENVECO = '1' AND  
	AY2.D_E_L_E_T_ = '' 
ORDER BY AY2.AY2_CODIGO