
SELECT * FROM SAK010 WHERE D_E_L_E_T_ = ''
SELECT * FROM SAL010 WHERE D_E_L_E_T_ = ''
SELECT * FROM SCS010 WHERE D_E_L_E_T_= ''

SELECT C7_ACCPROC,C7_CONAPRO,C7_QUJE,C7_QTDACLA,C7_QUANT,C7_NUM,C7_APROV,C7_USER,* FROM SC7010 WHERE D_E_L_E_T_ = ''
SELECT * FROM SCR010 WHERE D_E_L_E_T_ = ''

UPDATE SC7010 SET C7_ACCPROC = '2' 
WHERE
CR_NUM = '000002                                            '


SELECT 
	SAK.AK_EMAIL,
	SAK.AK_LIMITE, 
	SAK.AK_TIPO,
	SCS.CS_SALDO,
	SCS.CS_DATA
FROM 
	SAL010 SAL 
INNER JOIN SAK010 SAK ON SAK.AK_FILIAL = '  ' AND SAK.AK_COD = SAL.AL_APROV AND SAK.D_E_L_E_T_ = ''
LEFT OUTER JOIN SCS010 SCS ON SCS.CS_FILIAL = '00' AND SCS.CS_APROV = SAL.AL_APROV AND SCS.CS_DATA >= '20140809' AND SCS.D_E_L_E_T_ = ''
WHERE
	SAL.AL_FILIAL = ' ' AND
	SAL.AL_COD = '000001' AND
	SAL.D_E_L_E_T_ = '' 